ZER-138 Update ReadMe.md
ita-social-projects/ZeroWaste pull request #199
Opened 2022-07-22 10:57 UTC by KostiaFed

dev
## JIRA

* [ZER-138 JIRA ticket](https://jira.softserve.academy/browse/ZER-138)

## Summary of issue

Create meaningful and detailed documentation for local setup.

Documentation that will include:

How install and configure postgresql.
How install and configure yarn packages.
Explanation of config files for local setup.
Redis
Common system errors fixes (windows, linux etc.)

2022-07-22 11:17 UTC, PrincTwilig commented on README.md
> +<b>PostgreSQL</b>
In the project, the standard password for Postgresql is "password", maybe add information that you need to change the password in the project or set the postgresql password to "password"

![photo_2022-07-22_13-10-27](https://user-images.githubusercontent.com/93429979/180427359-fe276b57-e4f0-4be5-a9cc-d432e2a05dbe.jpg)

2022-07-22 11:17 UTC, PrincTwilig commented on README.md
>  ## How to run local
In some systems, after restarting them, the postgresql server remains disabled, perhaps at the first start you should enter "sudo service postgresql start"

2022-07-22 11:35 UTC, AndriiStegnytskyi commented on README.md
> +
Please notice about problem with js libraries, and how this command may help:
rm -rf node_modules

2022-07-22 11:35 UTC, AndriiStegnytskyi submitted a review, later dismissed

2022-07-22 11:39 UTC, PrincTwilig submitted a review, later dismissed

2022-07-22 11:42 UTC, denysiuk commented on README.md
> +
Also adding rake db:reset first would help if someone is having troubles with the database.

2022-07-22 11:49 UTC, denysiuk commented on README.md
> +
There were a lot of issues with Postgres, which are worth mentioning. Two of the most popular ones:
https://stackoverflow.com/questions/15301826/psql-fatal-role-postgres-does-not-exist
https://stackoverflow.com/questions/55038942/fatal-password-authentication-failed-for-user-postgres-postgresql-11-with-pg

2022-07-24 14:48 UTC, opazyniuk requested changes
please rename your branch according to the ID and name of your ticket and apply comments requested above

2022-07-25 05:43 UTC, closed without merging