Zer 139 update mob UI calculator
ita-social-projects/ZeroWaste pull request #216
Opened 2022-07-31 17:32 UTC by Beerka1

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @opazyniuk 

### Second Level Review

- [ ] @PavloMS 

## Summary of issue

1) In the mobile version: the logo should be aligned with the blocks on the left edge, the "Support" buttons and the language selection button should be placed one above the other and aligned with the blocks on the right edge.

2) In the mobile version: the text of the data entry block must be located on the same line as the data entry lines (on the left edge).

3) In the mobile version: the data input block and the result display block must be of the same width.

## Summary of change

Before
![image](https://user-images.githubusercontent.com/101131487/182035771-04960eec-984c-45cb-8a16-6085c2bf28c4.png)

After

Width: 767
![image](https://user-images.githubusercontent.com/101131487/182038142-df0e2453-4ef1-4630-a3d4-9ba102e494c7.png)

Width: 575
![image](https://user-images.githubusercontent.com/101131487/182038125-28c426eb-630f-47fe-b327-a8c8a772e677.png)

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-07-31 18:24 UTC, malk1ss approved these changes

2022-08-01 09:36 UTC, anastasiiahryniv approved these changes

2022-08-02 08:05 UTC, opazyniuk requested changes

2022-08-02 08:05 UTC, opazyniuk commented on Gemfile.lock
> +    concurrent-ruby (1.1.10)
remove changes form gemfile

2022-08-02 14:53 UTC, opazyniuk requested changes

2022-08-02 14:53 UTC, opazyniuk commented on package.json
> +    "@rails/webpacker": "^5.4.3",
why do you add this changes?

2022-08-02 14:53 UTC, opazyniuk commented on yarn.lock
> +"@rails/webpacker@^5.4.3":
why do you add this changes?

2022-08-02 14:54 UTC, opazyniuk requested changes
please add screenshots with before/after your changes results

2022-08-02 16:21 UTC, Beerka1 commented on package.json
> +    "@rails/webpacker": "^5.4.3",
Not needed, reverted it.

2022-08-02 16:23 UTC, Beerka1 commented on yarn.lock
> +"@rails/webpacker@^5.4.3":
Not needed, reverted it.

2022-08-02 18:48 UTC, opazyniuk approved these changes

2022-08-02 18:48 UTC, merged