ZER-140 design changes icon
ita-social-projects/ZeroWaste pull request #217
Opened 2022-08-01 15:13 UTC by anastasiiahryniv

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/browse/ZER-140)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

1. Data input block: remove the search icon
2. Data input block: reduce the cross icon
3. "Calculate", "Support", "Calculate result" buttons: remove icons from button names.

## Summary of change

Before

<img width="1428" alt="180832310-00cff55f-5ee3-4e38-89c0-6611ca9a2805" src="https://user-images.githubusercontent.com/90361521/182395435-c82a879e-71d4-4b6d-b895-2ac956787f68.png">
<img width="1440" alt="180832302-46c7b374-1386-40df-ad30-5734d7722f3d" src="https://user-images.githubusercontent.com/90361521/182395509-2e242cc6-3334-4b01-b8de-e2be256fa557.png">

After

<img width="1438" alt="180832340-136f95ca-6181-49ad-a079-be4b78cd448a" src="https://user-images.githubusercontent.com/90361521/182395804-fa47ca82-1492-4ff7-be96-7abf97ef9210.png">
<img width="1435" alt="180832370-34a29083-081e-4149-a742-c0877a50adf4" src="https://user-images.githubusercontent.com/90361521/182395832-b8713438-fab5-475b-912f-6ac5eab13b8a.png">

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-02 08:06 UTC, opazyniuk requested changes
- resolve merge conflicts
- add screenshot with your changes

2022-08-22 15:37 UTC, malk1ss approved these changes

2022-08-26 09:02 UTC, opazyniuk approved these changes

2022-08-26 09:06 UTC, AndriiStegnytskyi approved these changes

2022-08-26 09:07 UTC, merged