RspecSignUp - edited
ita-social-projects/ZeroWaste pull request #240
Opened 2022-08-19 08:52 UTC by malk1ss

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-22 15:33 UTC, anastasiiahryniv approved these changes

2022-08-30 07:41 UTC, opazyniuk requested changes
- specify tests per error
- localization tests
- more errors to cover

2022-09-15 08:23 UTC, opazyniuk submitted a review, later dismissed
localization

2022-09-15 08:23 UTC, opazyniuk commented on spec/features/sing_up_spec.rb
> +      fill_field_sign_up 'users@gmail.com', 'password1', 'password1', 'Margaret', 'Thatcher'
https://medium.com/@sologoubalex/keyword-parameters-in-ruby-e93d7a268151

2022-12-06 08:07 UTC, loqimean approved these changes

2022-12-06 12:56 UTC, merged