Fix feature tests for AdminLoginPage
ita-social-projects/ZeroWaste pull request #245
Opened 2022-08-22 15:55 UTC by PrincTwilig

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

Fix feature tests for AdminLoginPage

## Summary of change

There is 4 tests for "admin sign in"
- login and password is correct
- login and password is incorrect
- password is incorrect
- login is incorrect

![image](https://user-images.githubusercontent.com/93429979/185964913-10adc2e3-b0d2-4aa6-8f40-7c05ff406268.png)

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-08-22 19:20 UTC, Beerka1 approved these changes

2022-08-30 07:36 UTC, opazyniuk requested changes
add tests on ukrainian version

2022-08-30 07:36 UTC, opazyniuk commented on spec/features/admin_login_spec.rb
> +    subject { create(:user, :admin) }
let

2022-08-30 07:36 UTC, opazyniuk commented on spec/features/admin_login_spec.rb
> +    end
spaces between contexts

2022-09-03 21:03 UTC, KostiaFed approved these changes

2022-09-06 08:18 UTC, opazyniuk requested changes
add this
https://stackoverflow.com/questions/37799296/ruby-what-does-the-comment-frozen-string-literal-true-do

2022-09-14 18:06 UTC, opazyniuk approved these changes

2022-09-14 18:06 UTC, merged