Zer 155 cover diapers price category via new feature flag
ita-social-projects/ZeroWaste pull request #256
Opened 2022-09-02 12:37 UTC by AndriiStegnytskyi

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-09-02 17:24 UTC, Beerka1 approved these changes

2022-09-02 19:07 UTC, opazyniuk requested changes

2022-09-02 19:07 UTC, opazyniuk commented on spec/models/feature_flag_spec.rb
> +  let(:flag) { FeatureFlag.create(name: 'Some_name', enabled: true) }
please use factorybot here

2022-09-03 16:54 UTC, opazyniuk approved these changes

2022-09-03 16:54 UTC, merged