Get Started
ita-social-projects/ZeroWaste pull request #261
Opened 2022-09-12 16:35 UTC by PrincTwilig

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

+ Categories should be stored in DB as values "BUDGETARY", "MEDIUM", "PREMIUM".
+ price field should be in cents
+ update unit tests according to this changes

## Summary of change

Enum categories changes

![image](https://user-images.githubusercontent.com/93429979/189708162-dce78c15-7dbd-4d6c-86f9-21ac9b3c118c.png)

And change price to integer (in cents)

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-09-13 20:37 UTC, AndriiStegnytskyi approved these changes

2022-09-14 08:55 UTC, opazyniuk commented
red pipeline

2022-09-14 08:58 UTC, opazyniuk requested changes
PR is not finished

2022-09-14 08:58 UTC, opazyniuk commented on db/migrate/20220728162718_create_product_prices.rb
>        t.integer :category
category should be string

2022-09-14 13:02 UTC, KostiaFed approved these changes

2023-07-13 08:12 UTC, closed without merging