ZER-198 Add CRUD for SiteSettings in Admin
ita-social-projects/ZeroWaste pull request #308
Opened 2022-12-22 12:00 UTC by popovycj

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-01-08 16:39 UTC, VasylenchukMischa commented
зроби так, щоб сайт сетінги були завжди єдині на сторінці, якщо їх нема, то створювалися find_or_create_by, в адмінці зроби щоб їх можна було едітати, і створи метод-хелпер в аплікейшн контролер current_site де будуть діставатися цей екземпляр сайт сетінгів з бази

2023-01-11 07:28 UTC, VasylenchukMischa commented on app/helpers/application_helper.rb
> +        io: File.open("app/assets/images/logo_zerowaste.png"),
Ти при кожному ріквесті будеш відкривати цю картинку?

2023-01-30 13:13 UTC, VasylenchukMischa commented on .circleci/config.yml
> +          command: bundle exec rails db:create db:schema:load db:seed --trace
нащо сідів?

2023-01-30 15:56 UTC, popovycj commented on .circleci/config.yml
> +          command: bundle exec rails db:create db:schema:load db:seed --trace
changed

2023-02-05 16:55 UTC, loqimean commented on app/controllers/account/categories_controller.rb
> +  load_and_authorize_resource
не подобається мені ця штука з пандіт, але вже нехай буде

2023-02-05 16:55 UTC, loqimean commented on app/javascript/js/account/handle_browser_tab.js
> +})
давай це на стімулус)

2023-02-05 16:55 UTC, loqimean commented on app/controllers/account/site_settings_controller.rb
> +    SiteSetting.instance
молодець)

2023-02-05 16:55 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +  = simple_form_for @site_setting, url: { action: 'update' }, html: { novalidate: false } do |f|
ееее, пропиши норм url )

2023-02-05 16:55 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +  = simple_form_for @site_setting, url: { action: 'update' }, html: { novalidate: false } do |f|
і навіщо `novalidate: false` ?

2023-02-05 16:55 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +        = f.input :title, class: 'form-control', required: true
якщо буде валідація в модельці, то `simple_form` сам покаже, що то реквайред

2023-02-05 16:55 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +    = f.submit "", value: t('.update_button'), class: 'btn btn-success mr-2'
замість пустої строки передай просто `nil`

2023-02-05 16:55 UTC, loqimean commented on app/views/layouts/account.html.slim
> +    = favicon_link_tag(url_for(current_site_setting.favicon))
мало б так спрацювати
```suggestion
    = favicon_link_tag(current_site_setting.favicon.url)
```

2023-02-05 16:55 UTC, loqimean commented on app/views/layouts/application.html.slim
> +    = favicon_link_tag(url_for(current_site_setting.favicon))
вище писав

2023-02-05 16:55 UTC, loqimean commented on spec/controllers/account/site_setting_spec.rb
> +  end
у нас же є шерид контексти

2023-02-05 16:55 UTC, loqimean commented on spec/controllers/account/site_setting_spec.rb
> +      sign_in @admin
шерид контекст)

2023-02-05 16:55 UTC, loqimean commented on spec/controllers/account/site_setting_spec.rb
> +      put :update, params: { site_setting: { title: "Test Title", favicon: @file }}
не гуд, юзай фекторі

2023-02-05 16:55 UTC, loqimean commented on spec/helpers/application_helper_spec.rb
> +      end
вище писав

2023-02-05 16:55 UTC, loqimean commented on spec/models/site_setting_spec.rb
> +end
це все факторі

2023-02-05 18:12 UTC, VasylenchukMischa commented on app/controllers/account/site_settings_controller.rb
> +    SiteSetting.instance
ага, але перейменуй в current

2023-02-05 18:13 UTC, VasylenchukMischa commented on app/javascript/css/browser_tab.css.scss
> +}
щось багато піксель пьорфекта, зазвичай використовуємо значення кратні 2-х як мінімум

2023-02-12 10:47 UTC, VasylenchukMischa commented on app/javascript/js/account/handle_browser_tab.js
> +})
давай перше Влада пр замерджимо а потім дамо вже некст академії це на стімулус переписувати

2023-02-12 10:48 UTC, VasylenchukMischa commented on app/javascript/js/account/handle_browser_tab.js
> +})
бо зараз буде кожен в пр-і стімулус підключати

2023-02-25 18:33 UTC, annakynutsya commented on app/helpers/application_helper.rb
> +        io: File.open("app/assets/images/logo_zerowaste.png"),
переробила

2023-02-25 18:34 UTC, annakynutsya commented on app/javascript/js/account/handle_browser_tab.js
> +})
переробила

2023-02-25 18:34 UTC, annakynutsya commented on app/controllers/account/site_settings_controller.rb
> +    SiteSetting.instance
от тут не поняла, що саме перейменувати

2023-02-25 18:35 UTC, annakynutsya commented on app/views/account/site_settings/edit.html.slim
> +  = simple_form_for @site_setting, url: { action: 'update' }, html: { novalidate: false } do |f|
переробила

2023-02-25 18:36 UTC, annakynutsya commented on app/views/account/site_settings/edit.html.slim
> +        = f.input :title, class: 'form-control', required: true
прибрала

2023-02-25 18:36 UTC, annakynutsya commented on app/views/account/site_settings/edit.html.slim
> +    = f.submit "", value: t('.update_button'), class: 'btn btn-success mr-2'
зробила

2023-02-25 18:37 UTC, annakynutsya commented on app/views/layouts/account.html.slim
> +    = favicon_link_tag(url_for(current_site_setting.favicon))
так не працює(

2023-02-25 18:37 UTC, annakynutsya commented on spec/controllers/account/site_setting_spec.rb
> +  end
заюзала

2023-02-25 18:37 UTC, annakynutsya commented on spec/controllers/account/site_setting_spec.rb
> +      sign_in @admin
заюзала

2023-02-25 18:38 UTC, annakynutsya commented on spec/controllers/account/site_setting_spec.rb
> +      put :update, params: { site_setting: { title: "Test Title", favicon: @file }}
заюзала (правда нз чи правильно))

2023-02-25 18:38 UTC, annakynutsya commented on spec/helpers/application_helper_spec.rb
> +      end
+

2023-02-25 18:38 UTC, annakynutsya commented on spec/models/site_setting_spec.rb
> +end
+

2023-02-25 18:38 UTC, annakynutsya commented on app/javascript/css/browser_tab.css.scss
> +}
поправила

2023-02-25 18:43 UTC, VasylenchukMischa commented on app/controllers/account/site_settings_controller.rb
> +    SiteSetting.instance
SiteSetting.current щоб було

2023-02-25 18:43 UTC, VasylenchukMischa commented on app/javascript/js/account/handle_browser_tab.js
> +})
якщо переробила то можна цей файл видалити

2023-02-25 18:44 UTC, annakynutsya commented on app/controllers/account/site_settings_controller.rb
> +    SiteSetting.instance
поняла

2023-02-27 08:06 UTC, loqimean requested changes

2023-02-27 08:06 UTC, loqimean commented on app/helpers/application_helper.rb
> +      unless site_setting.favicon.attached?
це не тут має бути і мають бути заюзані дефолтні параметри, як от наступне:
`attribute :sent_at, default: -> { Time.now.utc }`

2023-02-27 08:06 UTC, loqimean commented on spec/controllers/account/site_setting_spec.rb
> +        expect(response).to render_template("edit")
be_successful, include(current_settings.title) і тд, де?)

2023-02-27 08:06 UTC, loqimean commented on spec/controllers/account/site_setting_spec.rb
> +      let(:site_setting_params) { FactoryBot.attributes_for(:site_setting, :with_favicon) }
якщо на те пішло, то де тут розбивання по-ролям?)

2023-02-27 08:06 UTC, loqimean commented on spec/controllers/account/site_setting_spec.rb
> +        expect(response).to render_template(:edit)
де перевірка на статус код?)

2023-02-27 08:06 UTC, loqimean commented on spec/helpers/application_helper_spec.rb
> +        current_site_setting = helper.current_site_setting
не треба того

2023-02-27 08:06 UTC, loqimean commented on spec/helpers/application_helper_spec.rb
> +        SiteSetting.instance.update((site_setting_params))
біфор

2023-02-27 08:06 UTC, loqimean commented on spec/helpers/application_helper_spec.rb
> +        current_site_setting = helper.current_site_setting
не треба

2023-02-27 08:06 UTC, loqimean commented on spec/helpers/application_helper_spec.rb
> +        current_site_setting = helper.current_site_setting
і мав би бути `let`, але знову ж таки, то тут не треба)

2023-02-28 18:20 UTC, annakynutsya commented on app/helpers/application_helper.rb
> +      unless site_setting.favicon.attached?
виправила

2023-03-01 14:00 UTC, annakynutsya commented on app/views/account/site_settings/edit.html.slim
> +        = render 'browser_tab', title: @site_setting.title, favicon: @site_setting.favicon
не зовсім розумію, що ти маєш наувазі, в паршалі ж не можна інстанс використовувати

2023-03-01 14:03 UTC, annakynutsya commented on app/views/account/site_settings/edit.html.slim
> +    = f.submit nil, value: t('.update_button'), class: 'btn btn-success mr-2'
value задає який надпис на кнопці буде, а навіщо там тайт ніл було написано я взагалі не знаю, прибрала його і все ок

2023-03-01 14:03 UTC, annakynutsya commented on app/javascript/controllers/handle_browser_tab_controller.js
> +    if (event.target.files && event.target.files[0]) {
+

2023-03-01 14:03 UTC, annakynutsya commented on app/javascript/controllers/index.js
> +application.register("handle-browser-tab", HandleBrowserTabController)
змінила

2023-03-01 14:05 UTC, annakynutsya commented on spec/controllers/account/site_setting_spec.rb
> +        expect(response).to render_template("edit")
додала

2023-03-01 14:06 UTC, annakynutsya commented on spec/controllers/account/site_setting_spec.rb
> +        expect(response).to render_template(:edit)
додала

2023-03-01 14:06 UTC, annakynutsya commented on spec/helpers/application_helper_spec.rb
> +        current_site_setting = helper.current_site_setting
+

2023-03-01 14:08 UTC, annakynutsya commented on spec/helpers/application_helper_spec.rb
> +        SiteSetting.instance.update((site_setting_params))
зробила

2023-03-01 14:17 UTC, annakynutsya commented on app/helpers/application_helper.rb
> +      unless site_setting.favicon.attached?
додала

2023-03-01 14:18 UTC, annakynutsya commented on spec/support/shared/context/site_setting_context.rb
> +end
використала той шерид контекст, що був)

2023-03-01 19:21 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +        = render 'browser_tab', title: @site_setting.title, favicon: @site_setting.favicon
ну інстанс юзати ні, а що тобі заважає передати його, як локал варіейбл?) `render "some/path", hello: @hello`

2023-03-01 20:14 UTC, loqimean commented on app/controllers/account/site_settings_controller.rb
> +    SiteSetting.instance
?)

2023-03-01 20:14 UTC, loqimean commented on app/helpers/application_helper.rb
> +        io: File.open("app/assets/images/logo_zerowaste.png"),
я казав то зробити в модельці), задати дефолтним атрібютом), приклад кидав)

2023-03-01 20:14 UTC, loqimean commented on app/javascript/controllers/handle_browser_tab_controller.js
> +    this.input.addEventListener('change', this.readURL.bind(this))
а звідки у тебе метод `readURL`?

2023-03-01 20:14 UTC, loqimean commented on db/schema.rb
> +    t.datetime "updated_at", precision: 6, default: "2023-03-01 14:17:21", null: false
щось не гуд, тут не має бути дата

2023-03-01 20:14 UTC, loqimean commented on spec/helpers/application_helper_spec.rb
> +        SiteSetting.instance.update((site_setting_params))
не зробила)

2023-03-01 20:14 UTC, loqimean commented on spec/requests/site_setting_spec.rb
> +        get edit_account_site_setting_path
```suggestion
        get edit_account_site_setting_path

```

2023-03-01 20:14 UTC, loqimean commented on spec/requests/site_setting_spec.rb
> +      include_context :authorize_admin
```suggestion
      include_context :authorize_admin

```

2023-03-01 20:14 UTC, loqimean commented on spec/requests/site_setting_spec.rb
> +      include_context :authorize_admin
і так далі

2023-03-01 20:14 UTC, loqimean commented on spec/requests/site_setting_spec.rb
> +      let(:params) { { site_setting: site_setting_params } }
чому не відразу?

2023-03-01 20:14 UTC, loqimean commented on spec/requests/site_setting_spec.rb
> +        put account_site_setting_path, params: params
пут? і чому ти не перевіряєш, що помінявся тайтл?

2023-03-01 20:14 UTC, loqimean commented on spec/requests/site_setting_spec.rb
> +        expect(response).not_to have_http_status(:error)
або successful, або ерора)

2023-03-01 22:29 UTC, annakynutsya commented on app/controllers/account/site_settings_controller.rb
> +    SiteSetting.instance
перейменувала

2023-03-01 22:43 UTC, annakynutsya commented on spec/helpers/application_helper_spec.rb
> +        SiteSetting.instance.update((site_setting_params))
ой, тепер точно зробила)

2023-03-01 22:56 UTC, annakynutsya commented on spec/requests/site_setting_spec.rb
> +      let(:params) { { site_setting: site_setting_params } }
переробила

2023-03-02 08:08 UTC, mykhailovasylenchuk commented on app/models/site_setting.rb
> +end
і анотейт нема

2023-03-02 20:27 UTC, annakynutsya commented on spec/requests/site_setting_spec.rb
> +        put account_site_setting_path, params: params
вже перевіряю

2023-03-02 20:27 UTC, annakynutsya commented on spec/requests/site_setting_spec.rb
> +        expect(response).not_to have_http_status(:error)
змінила

2023-03-03 22:53 UTC, annakynutsya commented on app/javascript/controllers/handle_browser_tab_controller.js
> +    this.input.addEventListener('change', this.readURL.bind(this))
переробила

2023-03-03 22:56 UTC, annakynutsya commented on app/models/site_setting.rb
> +end
додала

2023-03-04 12:07 UTC, mykhailovasylenchuk commented on app/javascript/css/browser_tab.css.scss
> +}
зроби як в scss) .tab{ &-text {} ... }

2023-03-04 12:11 UTC, mykhailovasylenchuk commented on app/models/site_setting.rb
> +  end
постав це після колбеків

2023-03-04 12:12 UTC, mykhailovasylenchuk commented on app/views/account/site_settings/_browser_tab.html.slim
> +
навіщо цей пробіл?

2023-03-04 12:16 UTC, mykhailovasylenchuk commented on app/views/account/site_settings/edit.html.slim
> +few
що за тег такий?)

2023-03-04 12:17 UTC, mykhailovasylenchuk commented on app/javascript/controllers/handle_browser_tab_controller.js
> +  }
```suggestion
}
```

2023-03-04 14:58 UTC, annakynutsya commented on app/javascript/css/browser_tab.css.scss
> +}
зробила

2023-03-04 14:59 UTC, annakynutsya commented on app/models/site_setting.rb
> +  end
зробила

2023-03-04 15:00 UTC, annakynutsya commented on app/views/account/site_settings/_browser_tab.html.slim
> +
прибрала

2023-03-04 15:02 UTC, annakynutsya commented on app/views/account/site_settings/edit.html.slim
> +few
прибрала

2023-03-04 15:03 UTC, annakynutsya commented on app/javascript/controllers/handle_browser_tab_controller.js
> +  }
+

2023-03-04 15:34 UTC, mykhailovasylenchuk commented on app/javascript/packs/application.js
> +import "../js/account/handle_browser_tab"
цей імпорт навіщо якщо ти файл видалила?

2023-03-04 19:57 UTC, mykhailovasylenchuk commented on app/javascript/controllers/handle_browser_tab_controller.js
> +  }
не поправила

2023-03-05 09:52 UTC, mykhailovasylenchuk commented on app/javascript/controllers/handle_browser_tab_controller.js
> +  readURL(event) {
```suggestion
  }

  readURL(event) {
```

2023-03-05 12:23 UTC, annakynutsya commented on spec/support/shared/context/site_setting_context.rb
> +end
прибрала

2023-03-05 12:27 UTC, annakynutsya commented on app/helpers/application_helper.rb
> +  end
оок

2023-03-05 13:25 UTC, annakynutsya commented on app/javascript/controllers/handle_browser_tab_controller.js
> +        $('.tab-icon').attr('src', e.target.result)
переписала

2023-03-05 13:25 UTC, annakynutsya commented on app/javascript/controllers/handle_browser_tab_controller.js
> +    this.input.addEventListener('input', this.setTitle.bind(this))
переробила

2023-03-05 13:40 UTC, annakynutsya commented on app/models/site_setting.rb
> +  after_initialize :set_default_favicon
я пробувала робити ось так: attribute :favicon, default: -> { File.open(Rails.root.join("app", "assets", "images", "logo_zerowaste.png")) } але так не працює. Тому я знайшла такий спосіб, використати колбек

2023-03-05 13:44 UTC, annakynutsya commented on app/models/site_setting.rb
> +  end
можна ще ніби просто ось так писати: alias :current :instance, але була помилка

2023-03-05 14:15 UTC, annakynutsya commented on app/helpers/application_helper.rb
> +  end
це треба лишити бо тести падають

2023-03-05 14:38 UTC, annakynutsya commented on app/helpers/application_helper.rb
> +  end
бо цей метод використовується в account.html.slim

2023-03-07 07:22 UTC, loqimean requested changes

2023-03-07 07:22 UTC, loqimean commented on app/helpers/application_helper.rb
> +  end
видаляй, він не треба

2023-03-07 07:22 UTC, loqimean commented on app/javascript/controllers/handle_browser_tab_controller.js
> +    this.input.addEventListener('input', this.setTitle.bind(this))
не переробила 🙂

2023-03-07 07:22 UTC, loqimean commented on app/javascript/controllers/handle_browser_tab_controller.js
> +        $('.tab-icon').attr('src', e.target.result)
і це не переписала

2023-03-07 07:22 UTC, loqimean commented on app/javascript/controllers/index.js
> +application.load(definitions)
чому це у двох файлах?

2023-03-07 07:22 UTC, loqimean commented on app/models/site_setting.rb
> +  after_initialize :set_default_favicon
ну ок

2023-03-07 07:22 UTC, loqimean commented on app/models/site_setting.rb
> +  end
ну та а яка помилка? не має ьути помилки

2023-03-07 07:22 UTC, loqimean commented on app/views/account/site_settings/_browser_tab.html.slim
> +    = image_tag(current_site_setting.favicon, class: 'tab-icon')
де альт атрибут? де srcset?

2023-03-07 07:22 UTC, loqimean commented on app/views/layouts/account.html.slim
> +    = favicon_link_tag(url_for(current_site_setting.favicon))
ти дивилася документацію? там пише так робити?

2023-03-07 07:22 UTC, loqimean commented on db/schema.rb
> +    t.string "title", default: "ZeroWaste"
а якщо юзер пошле пусту стрінгу??

2023-03-07 07:22 UTC, loqimean commented on spec/support/shared/context/site_setting_context.rb
> +end
не прибрала 🙂

2023-03-07 12:35 UTC, mykhailovasylenchuk commented on app/models/site_setting.rb
> +    alias_method :current, :instance
https://stackoverflow.com/questions/17792184/why-alias-method-is-an-instance-method

2023-03-07 16:50 UTC, loqimean commented on app/javascript/controllers/stimulus_application.js
> +import { Application } from "@hotwired/stimulus";
назву файлу просто "application"

2023-03-07 16:50 UTC, loqimean commented on app/javascript/controllers/stimulus_application.js
> +application.load(definitionsFromContext(context));
```suggestion
import { Application } from "@hotwired/stimulus"

const application = Application.start()

// Configure Stimulus development experience
application.debug = false
window.Stimulus = application

export { application }
```

2023-03-07 16:50 UTC, loqimean commented on db/schema.rb
> +    t.string "title", default: "ZeroWaste"
??

2023-03-07 16:50 UTC, loqimean commented on spec/models/site_setting_spec.rb
> +    end
be_persisted чи типу того

2023-03-08 20:23 UTC, loqimean submitted a review, later dismissed

2023-03-12 16:14 UTC, loqimean approved these changes

2023-03-12 16:24 UTC, BarryLev approved these changes
Все гуд, напевно

2023-03-12 16:25 UTC, merged