Added dashboard controller, view and route for account namespace
ita-social-projects/ZeroWaste pull request #343
Opened 2023-02-19 14:10 UTC by annakynutsya

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

The task was to create a dashboard page for /account namespace and make it root for it.

## Summary of change

The dashboard controller, view and route were created. Now if we enter url ".../account" - the root page for account namespace (which is dashboard page) opens.

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-02-19 20:05 UTC, VasylenchukMischa commented on app/views/account/dashboard/index.html.slim
> +  h1 Hello!
в цей неймспейс можуть попасти неавторизовані користувачі? Ти впевнена?

2023-02-19 20:06 UTC, annakynutsya commented on app/views/account/dashboard/index.html.slim
> +  h1 Hello!
блін, точно

2023-02-20 07:16 UTC, loqimean requested changes

2023-02-20 07:16 UTC, loqimean commented on spec/controllers/account/dashboard_spec.rb
> +RSpec.describe Account::DashboardController do
тест має бути `request` типу

2023-02-20 07:16 UTC, loqimean commented on spec/controllers/account/dashboard_spec.rb
> +      expect(response).to be_successful
де перевірка рендера темплейту?

2023-02-20 07:16 UTC, loqimean commented on app/views/account/dashboard/index.html.slim
> +h1 Hello
hello current_user.full_name

2023-02-20 07:16 UTC, loqimean commented on spec/controllers/account/dashboard_spec.rb
> +      expect(response).to be_successful
як у тебе цей тест проходить?

2023-02-20 07:16 UTC, loqimean commented on app/controllers/account/dashboard_controller.rb
> +class Account::DashboardController < ApplicationController
чому аплікейшин контроллер?

2023-02-20 07:16 UTC, loqimean commented on config/routes.rb
> +      root "dashboard#index"
```suggestion
      root "dashboard#index"

```

2023-02-20 07:16 UTC, loqimean commented on spec/controllers/account/dashboard_spec.rb
> +      expect(response).to be_successful
де перевірка на певний контент?

2023-02-20 18:48 UTC, annakynutsya commented on spec/controllers/account/dashboard_spec.rb
> +RSpec.describe Account::DashboardController do
переробила

2023-02-20 18:48 UTC, annakynutsya commented on spec/controllers/account/dashboard_spec.rb
> +      expect(response).to be_successful
changed

2023-02-20 18:48 UTC, annakynutsya commented on app/views/account/dashboard/index.html.slim
> +h1 Hello
changed

2023-02-20 18:48 UTC, annakynutsya commented on app/controllers/account/dashboard_controller.rb
> +class Account::DashboardController < ApplicationController
changed

2023-02-20 18:50 UTC, loqimean requested changes

2023-02-20 18:50 UTC, loqimean commented on app/models/user.rb
> +  def full_name
в чаті відписав

2023-02-20 18:50 UTC, loqimean commented on spec/support/shared/context/dashboard_context.rb
> +end
в чаті відписав

2023-02-20 18:50 UTC, loqimean commented on spec/requests/dashboard_request_spec.rb
> +        get account_root_path
має бути логічне розділення коду

2023-02-20 18:50 UTC, loqimean commented on spec/requests/dashboard_request_spec.rb
> +        get account_root_path
```suggestion
        get account_root_path

```

2023-02-20 19:31 UTC, annakynutsya commented on app/models/user.rb
> +  def full_name
Я попробувала зробити так як ти написав в чаті, то так рубокоп свариться і не проходить перевірка. Рубокоп запропонував використати [first_name, last_name].compact_blank.join(" ") то я поки так зробила

2023-02-20 19:33 UTC, annakynutsya commented on spec/requests/dashboard_request_spec.rb
> +        get account_root_path
changed

2023-02-21 07:44 UTC, loqimean requested changes

2023-02-21 07:44 UTC, loqimean commented on app/models/user.rb
> +  def full_name
ну для того напевно і був доданий рубокоп). Все гуд)

2023-02-21 07:44 UTC, loqimean commented on app/models/user.rb
> +  def full_name
тепер)

2023-02-21 07:44 UTC, loqimean commented on spec/requests/dashboard_request_spec.rb
> +        get account_root_path
я ж написав нижче, що має бути логічне розділення коду

```suggestion
        get account_root_path

```

2023-02-21 07:44 UTC, loqimean commented on spec/requests/dashboard_request_spec.rb
> +        get account_root_path
так само і в інших тестах

2023-02-21 07:44 UTC, loqimean commented on spec/requests/dashboard_request_spec.rb
> +        get account_root_path
щось нічого тут не чейнджет)

2023-02-21 07:44 UTC, loqimean commented on spec/requests/dashboard_request_spec.rb
> +        expect(response).to redirect_to(new_user_session_path)
а перевірка на месидж?

2023-02-21 07:44 UTC, loqimean commented on spec/requests/dashboard_request_spec.rb
> +        expect(response.body).to include("hello #{current_user.full_name}")
закинь то все в попередній тест, нема сенсу то розділяти

2023-02-21 07:44 UTC, loqimean commented on spec/requests/dashboard_request_spec.rb
> +        expect(response.body).to include("hello #{current_user.full_name}")
ну як, є, але то зараз не так важливо

2023-02-21 22:33 UTC, annakynutsya commented on spec/requests/dashboard_request_spec.rb
> +        get account_root_path
тепер чейнджет)

2023-02-21 22:34 UTC, annakynutsya commented on spec/requests/dashboard_request_spec.rb
> +        get account_root_path
зробила

2023-02-21 22:34 UTC, annakynutsya commented on spec/requests/dashboard_request_spec.rb
> +        expect(response).to redirect_to(new_user_session_path)
зробила

2023-02-21 22:34 UTC, annakynutsya commented on spec/requests/dashboard_request_spec.rb
> +        expect(response.body).to include("hello #{current_user.full_name}")
зробила

2023-02-23 00:00 UTC, merged