CRUD for Products
ita-social-projects/ZeroWaste pull request #358
Opened 2023-02-25 19:20 UTC by heroisaprinciple

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

Added CRUD for Products and products for translation in locales.

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-17 14:48 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    @ordered_categories = Category.ordered_categories
ordered_by назви краще по чому сортується

2023-03-17 14:48 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    binding.pry
для кого лишила?)

2023-03-17 14:49 UTC, mykhailovasylenchuk commented on app/javascript/controllers/price_input_controller.js
> +    let prices = document.querySelectorAll(".hidden-sum")
є така штука як multi targets в стімулусі

2023-03-17 14:50 UTC, mykhailovasylenchuk commented on app/models/category.rb
> +  scope :ordered_categories, -> { Category.order(:name) }
self не потрібно тут вказувати, прибери назву класу

2023-03-17 14:51 UTC, mykhailovasylenchuk commented on app/models/price.rb
> +  accepts_nested_attributes_for :category
після валідацій нестед атрибути

2023-03-17 14:51 UTC, mykhailovasylenchuk commented on app/views/account/products/edit.html.slim
> +          li= error_message
так є ж флеші по ідеї? Тостр чи щось таке

2023-03-17 14:51 UTC, mykhailovasylenchuk commented on app/views/account/products/edit.html.slim
> +few
що це за тег?)

2023-03-17 14:52 UTC, mykhailovasylenchuk commented on app/views/account/products/index.html.slim
> +    = link_to new_account_product_path(id: @products), class: 'btn btn-success px-4 ml-1' do
```suggestion
    = link_to new_account_product_path(@products), class: 'btn btn-success px-4 ml-1' do
```

2023-03-17 14:52 UTC, mykhailovasylenchuk commented on app/views/account/products/index.html.slim
> +    = link_to new_account_product_path(id: @products), class: 'btn btn-success px-4 ml-1' do
має так працювати

2023-03-17 14:53 UTC, mykhailovasylenchuk commented on app/views/account/products/new.html.slim
> +few
тег, і вже раз таке зробила, то виноси в паршал, але має бути на лейауті щось типу share/partial або загалом тостр

2023-03-17 14:54 UTC, mykhailovasylenchuk commented on app/views/account/products/new.html.slim
> +      /       = label_tag category.name # matches the id of the check_box
не треба - видаляй

2023-03-17 14:54 UTC, mykhailovasylenchuk commented on app/views/account/products/show.html.slim
> +    .d-flex
що тут відбувається?

2023-03-17 14:55 UTC, mykhailovasylenchuk commented on spec/requests/products_spec.rb
> +  # end
дропни якщо не треба

2023-03-17 14:58 UTC, mykhailovasylenchuk commented on spec/requests/products_spec.rb
> +  end
навіщо врапити в біфор екшн

2023-03-17 15:01 UTC, mykhailovasylenchuk commented on spec/requests/products_spec.rb
> +  # make a patch request
не треба

2023-03-17 15:02 UTC, mykhailovasylenchuk commented on spec/requests/products_spec.rb
> +        expect(response).to be_unprocessable # to have http_status
прибери комент, тут явний тест

2023-03-17 15:02 UTC, mykhailovasylenchuk commented on spec/requests/products_spec.rb
> +  # make a delete request
не треба

2023-03-17 15:03 UTC, mykhailovasylenchuk commented on app/javascript/controllers/price_input_controller.js
> +    let checkboxes = Array.from(document.querySelectorAll('input')).filter((el) => el.type == 'checkbox')
а можеш на сам чекбокс навісити таргет?

2023-03-17 15:03 UTC, mykhailovasylenchuk commented on app/javascript/controllers/price_input_controller.js
> +    let submit = document.querySelector('#submit')
таргет навішай, є така штука в стімулус

2023-03-17 15:08 UTC, mykhailovasylenchuk commented on app/javascript/controllers/price_input_controller.js
> +      })
теж перепиши на екшни стімулуса, і почитай уважно доку стімулуса

2023-03-19 15:57 UTC, heroisaprinciple commented on app/models/category.rb
> +  scope :ordered_categories, -> { Category.order(:name) }
done

2023-03-19 15:57 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    @ordered_categories = Category.ordered_categories
done

2023-03-19 15:59 UTC, heroisaprinciple commented on app/models/price.rb
> +  accepts_nested_attributes_for :category
done

2023-03-19 16:30 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +        th scope="col"  =t('.table.actions')
done

2023-03-19 16:34 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +  # end
done

2023-03-19 16:35 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +    # to create a product before testing
done

2023-03-19 17:21 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +          # binding.pry
)))

2023-03-19 17:21 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +  # make a patch request
done

2023-03-19 17:21 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +        expect(response).to be_unprocessable # to have http_status
done

2023-03-19 17:21 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +  # make a delete request
done

2023-03-19 17:21 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +  # make a post request
done

2023-03-19 17:34 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +    = link_to new_account_product_path(id: @products), class: 'btn btn-success px-4 ml-1' do
done

2023-03-19 18:53 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +    = link_to new_account_product_path(id: @products), class: 'btn btn-success px-4 ml-1' do
done

2023-03-19 18:54 UTC, heroisaprinciple commented on app/views/account/products/edit.html.slim
> +few
done

2023-03-19 18:54 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +  end
done

2023-03-19 18:58 UTC, heroisaprinciple commented on app/views/account/products/new.html.slim
> +      /       = label_tag category.name # matches the id of the check_box
done

2023-03-19 19:00 UTC, heroisaprinciple commented on app/views/account/products/new.html.slim
> +few
few видалила вже, еррорки винесу в паршал

2023-03-19 20:51 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +div class="container home"
.container.home )))))

2023-03-19 20:57 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +    .d-flex
deleted

2023-03-19 20:58 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +div class="container home"
це калька з .erb (який був спочатку), соррі)))

2023-03-19 21:00 UTC, heroisaprinciple commented on app/javascript/controllers/price_input_controller.js
> +    })
))))

2023-03-19 21:01 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +        expect(response).to be_unprocessable # to have http_status
done

2023-03-26 16:46 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +    = link_to new_account_product_path(id: @products), class: 'btn btn-success px-4 ml-1' do
написала тобі, що так не можна :(

2023-03-26 16:52 UTC, mykhailovasylenchuk commented on app/models/product.rb
> +    attributes[:sum].blank?
покрий тестом в моделі

2023-03-26 17:56 UTC, heroisaprinciple commented on app/models/product.rb
> +    attributes[:sum].blank?
done :)

2023-03-26 18:08 UTC, mykhailovasylenchuk approved these changes

2023-03-27 08:26 UTC, loqimean commented on app/controllers/account/products_controller.rb
> +    Product.all
оредеред має бути

2023-03-27 08:26 UTC, loqimean commented on app/models/product.rb
> +  belongs_to :product_type, optional: true
можеш закоментувати поки

2023-03-27 08:26 UTC, loqimean commented on spec/requests/products_spec.rb
> +      expect(response).to be_successful
де рендер темплейту? де перевірка, що є контент?

2023-03-27 10:19 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    Product.all
done

2023-03-27 16:10 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +      expect(response).to be_successful
done

2023-03-30 09:51 UTC, loqimean commented on app/models/product.rb
> +  # belongs_to :product_type, optional: true
якщо не треба, то видаляй

2023-03-30 09:51 UTC, loqimean commented on app/javascript/controllers/form_controller.js
> +    for (const target of this.priceTargets) {
forEach

2023-03-30 09:51 UTC, loqimean commented on app/javascript/controllers/form_controller.js
> +    for (const target of this.priceTargets) {
forEach

2023-03-30 16:44 UTC, heroisaprinciple commented on app/models/product.rb
> +  # belongs_to :product_type, optional: true
done

2023-03-30 17:50 UTC, heroisaprinciple commented on app/javascript/controllers/form_controller.js
> +    for (const target of this.priceTargets) {
done

2023-03-30 17:50 UTC, heroisaprinciple commented on app/javascript/controllers/form_controller.js
> +    for (const target of this.priceTargets) {
done

2023-03-30 18:59 UTC, mykhailovasylenchuk commented on config/locales/uk/uk.yml
> +    product_created: "Продукт був успішно створений."
DRY, могла зробити щоб діставати цей транслейту через product.updated

2023-03-30 21:15 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    end
щось це костильно виглядає, потім в тебе це контролер продакт, треба щоб параметр :id був id продукту а не прайсу, і я думаю що тут краще написати колбек який буде видаляти продукт з nil значенням, бо така логіка в контролері не ок

2023-03-30 21:16 UTC, mykhailovasylenchuk commented on app/javascript/controllers/form_controller.js
> +        target.querySelector('input').value = ''
чому на інпут не повісиш таргет?

2023-03-30 21:16 UTC, mykhailovasylenchuk commented on app/javascript/controllers/form_controller.js
> +      if (el.hidden || el.querySelector('input').value == '') {
тут теж

2023-03-30 21:16 UTC, mykhailovasylenchuk commented on app/models/category.rb
> +  has_one :price, dependent: :destroy
вище хез мені має бути

2023-03-30 21:17 UTC, heroisaprinciple commented on app/javascript/controllers/form_controller.js
> +        target.querySelector('input').value = ''
не вийде, бо тоді інпут приймає нейм дата тарджету

2023-03-30 21:20 UTC, heroisaprinciple commented on app/models/category.rb
> +  has_one :price, dependent: :destroy
done

2023-03-30 21:21 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    end
окей!

2023-03-30 21:21 UTC, mykhailovasylenchuk commented on app/javascript/controllers/form_controller.js
> +        target.querySelector('input').value = ''
ну ок

2023-03-30 21:22 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    end
думаю найкраще це винести в хелпер, і коменти видали якщо не треба, і неймінг кей вел'ю зміни

2023-03-31 06:40 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    end
в чаті вже сказали що нестид атрибути це вміють

2023-03-31 07:05 UTC, loqimean requested changes

2023-03-31 07:05 UTC, loqimean commented on app/models/product.rb
> +  def blank_prices(attributes)
чому це не прайвет?

2023-03-31 07:05 UTC, loqimean commented on spec/models/product_spec.rb
> +  end
не гуд тест, ти тестуєш те, що 2 це 2, а не що дія виконується)

2023-03-31 07:05 UTC, loqimean commented on spec/requests/products_spec.rb
> +  let!(:product) { create(:product, :diaper) }
це тобі точно в кожному тесті треба?

2023-03-31 07:05 UTC, loqimean commented on spec/requests/products_spec.rb
> +    context "does not create a product" do
```suggestion
    context "with invalid attributes" do
```

2023-03-31 07:05 UTC, loqimean commented on spec/requests/products_spec.rb
> +      it "a product without price and category" do
```suggestion
      it "does not create a product" do
```

2023-03-31 07:05 UTC, loqimean commented on spec/requests/products_spec.rb
> +        expect(price.sum).to eq(18.2)
`expect do .. end.to change` це юзай

2023-03-31 07:42 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    @product = Product.new(products_params)
?

2023-03-31 07:45 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    @product = Product.new(products_params)
поняф, done

2023-03-31 07:46 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +                                    prices_attributes: [:id, :sum, :category_id])
done

2023-03-31 07:57 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +    context "does not create a product" do
done

2023-03-31 07:58 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +  let!(:product) { create(:product, :diaper) }
перепишу

2023-03-31 07:59 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +      it "a product without price and category" do
done

2023-03-31 08:14 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +        expect(price.sum).to eq(18.2)
done

2023-04-05 11:26 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    change_attributes
done

2023-04-05 11:26 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    end
done

2023-04-05 11:26 UTC, heroisaprinciple commented on app/models/product.rb
> +  accepts_nested_attributes_for :prices, reject_if: :blank_prices
done

2023-04-05 13:45 UTC, heroisaprinciple commented on spec/models/product_spec.rb
> +  end
done

2023-04-05 16:03 UTC, heroisaprinciple commented on app/javascript/controllers/form_controller.js
done

2023-04-05 18:56 UTC, heroisaprinciple commented on app/views/account/products/edit.html.slim
> +                = prices_form.input :sum, as: :decimal, label: false, input_html: {placeholder: 'Sum'}
done

2023-04-05 18:57 UTC, heroisaprinciple commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, url: { action: 'create' }, data: {controller: "form" } do |f|
)))

2023-04-05 18:58 UTC, heroisaprinciple commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, url: { action: 'create' }, data: {controller: "form" } do |f|
done

2023-04-05 19:15 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +    = link_to new_account_product_path(id: @products), class: 'btn btn-success px-4 ml-1' do
done

2023-04-05 19:26 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +  = form_tag account_product_path(id: @products), method: :get, class: 'd-flex justify-content-end mb-5' do
done

2023-04-05 19:52 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +                    data: { confirm: t('.confirm_delete') } do
так

2023-04-05 20:26 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          = link_to edit_account_product_path(id: @product) do
done

2023-04-05 20:26 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          = link_to account_product_path(id: @product), method: :delete,
done

2023-04-05 20:26 UTC, heroisaprinciple commented on app/models/product.rb
> +  def blank_prices(attributes)
done

2023-04-08 14:53 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          = link_to edit_account_product_path(id: @product) do
тут якщо не вказати, то буде route error

2023-04-08 14:53 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          = link_to account_product_path(id: @product), method: :delete,
route error

2023-04-08 20:13 UTC, heroisaprinciple commented on spec/factories/products.rb
> +    trait :no_title do
invalid_title підійде?

2023-04-09 10:34 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +            br
done

2023-04-09 10:34 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +              span = price.sum
done

2023-04-09 10:35 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          = link_to edit_account_product_path(id: @product) do
розбираюсь чому замість локаль береться айдішка ;(

2023-04-09 10:36 UTC, heroisaprinciple commented on spec/factories/products.rb
> +    trait :no_title do
ти сказав, що ок)

2023-04-09 10:37 UTC, heroisaprinciple commented on spec/models/product_spec.rb
> +  let!(:product) { build(:product) }
повернула

2023-04-09 10:37 UTC, heroisaprinciple commented on spec/models/product_spec.rb
> -  subject { build(:product) }
тепер так))

2023-04-09 10:37 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +  let!(:product) { create(:product, :diaper) }
ти казав повернути)))

2023-04-09 11:12 UTC, heroisaprinciple commented on spec/models/product_spec.rb
> +  end
йду писати ріквест тест

2023-04-13 21:04 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    if @product.save
та просто апдейт роби

2023-04-13 21:13 UTC, mykhailovasylenchuk commented on app/javascript/controllers/price_form_controller.js
> +    return price.querySelector('input').value
в сімпл формі на скільки пам'ятаю можна повісити таргет на інпут і позбутися цього методу

2023-04-14 04:37 UTC, loqimean commented on app/controllers/account/products_controller.rb
> +    end
порефактори це, щоб була одна кверя

2023-04-14 04:37 UTC, loqimean commented on app/controllers/account/products_controller.rb
> +    if @product.save
ага

2023-04-14 04:37 UTC, loqimean commented on app/controllers/account/products_controller.rb
> +    if @product.save
тоді і асайн атрібютс нафіг треба

2023-04-14 04:37 UTC, loqimean commented on app/controllers/account/products_controller.rb
> +  def products_params
```suggestion
  def product_params
```

2023-04-14 04:37 UTC, loqimean commented on app/javascript/controllers/price_form_controller.js
> +    return price.querySelector('input').value
так, можна

2023-04-14 04:37 UTC, loqimean commented on app/javascript/controllers/price_form_controller.js
> +  get checkboxes() {
для таких штук, є геттери

2023-04-14 04:37 UTC, loqimean commented on app/views/account/products/edit.html.slim
> +                = prices_form.hidden_field :_destroy, value: 0, data: { price_form_target: 'hiddenField' }
тут це велʼю взагалі потрібне?

2023-04-14 04:37 UTC, loqimean commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, method: :create, url: account_products_path, data: { controller: "price-form" } do |f|
у тебе на edit та на new має використовуватися одна і та ж форма

2023-04-14 04:37 UTC, loqimean commented on spec/models/product_spec.rb
> -  subject { build(:product) }
)))

2023-04-14 04:37 UTC, loqimean commented on spec/models/product_spec.rb
> -  subject { build(:product) }
і нафіга ти дала йому нейм?)

2023-04-14 04:37 UTC, loqimean commented on spec/requests/products_spec.rb
> +  let!(:product) { create(:product, :diaper) }
що повернути), моє питання все те ж) - воно тобі точно треба в кожному тесті?

2023-04-14 04:37 UTC, loqimean commented on spec/requests/products_spec.rb
> +    let(:invalid_product_attributes) { attributes_for(:product, :invalid_title) }
не invalid_title, а просто invalid

2023-04-15 11:12 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +    let(:invalid_product_attributes) { attributes_for(:product, :invalid_title) }
done

2023-04-15 11:18 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +    let(:invalid_product_attributes) { attributes_for(:product, :invalid_title) }
done

2023-04-15 11:29 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +    let(:invalid_product_attributes) { attributes_for(:product, :invalid_title) }
done

2023-04-15 11:33 UTC, heroisaprinciple commented on spec/models/product_spec.rb
> -  subject { build(:product) }
ой

2023-04-15 11:36 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +  def products_params
done

2023-04-16 17:43 UTC, heroisaprinciple commented on app/views/account/products/edit.html.slim
> +                = prices_form.hidden_field :_destroy, value: 0, data: { price_form_target: 'hiddenField' }
вже видалила

2023-04-16 17:44 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    if @product.save
done

2023-04-17 17:27 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    end
done

2023-04-17 17:38 UTC, heroisaprinciple commented on app/javascript/controllers/price_form_controller.js
> +  get checkboxes() {
?))

2023-04-17 18:44 UTC, heroisaprinciple commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, method: :create, url: account_products_path, data: { controller: "price-form" } do |f|
так не вийде
бо simple_fields_for рендериться стільки разів, скільки є прайсів 
тому в мене трохи змінена форма на едіті
якщо робити як ти пропонуєш, то в мене буде на сторінці декілька однакових категорій

2023-04-17 18:44 UTC, heroisaprinciple commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, method: :create, url: account_products_path, data: { controller: "price-form" } do |f|
написала тобі

2023-04-17 19:05 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          = link_to edit_account_product_path(id: @product) do
done

2023-04-17 19:06 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          = link_to account_product_path(id: @product), method: :delete,
done

2023-04-17 19:19 UTC, mykhailovasylenchuk commented on app/javascript/controllers/price_form_controller.js
> +  }
навіщо ці гетери взагалі? Сильно читабельність спортиться якщо ти їх не будеш юзати?

2023-04-17 19:19 UTC, mykhailovasylenchuk commented on app/javascript/controllers/price_form_controller.js
> +  }
і цей

2023-04-18 07:28 UTC, heroisaprinciple commented on app/javascript/controllers/price_form_controller.js
> +  }
done

2023-04-18 07:28 UTC, heroisaprinciple commented on app/javascript/controllers/price_form_controller.js
> +  }
done

2023-04-18 10:05 UTC, heroisaprinciple commented on config/locales/uk/uk.yml
> +    product_created: "Продукт був успішно створений."
done

2023-04-18 10:14 UTC, mykhailovasylenchuk commented on app/javascript/controllers/price_form_controller.js
> +    return price.querySelector('input').value
добре б було цей хак теж позбутися, але цей пр затягнувся

2023-04-18 10:14 UTC, mykhailovasylenchuk approved these changes

2023-04-19 16:28 UTC, loqimean commented on app/javascript/controllers/price_form_controller.js
> +    return price.querySelector('input').value
так, але треба гуд код писати))

2023-04-19 16:28 UTC, loqimean commented on app/views/account/products/show.html.slim
> +          - @product.prices.map do |price|
N+1

2023-04-19 16:28 UTC, loqimean commented on app/views/account/products/show.html.slim
> +            span = "#{price.category.name}: #{price.sum}"
N+1

2023-04-19 16:28 UTC, loqimean commented on app/views/account/products/show.html.slim
> +          = link_to account_product_path(I18n.locale, @product), method: :delete,
чому локаль передаєш?

2023-04-19 16:28 UTC, loqimean commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, method: :create, url: account_products_path, data: { controller: "price-form" } do |f|
ок, пофіг поки

2023-04-19 16:28 UTC, loqimean commented on app/views/account/products/index.html.slim
> +            = link_to account_product_path(I18n.locale, product), method: :delete, data: { confirm: t('.confirm_delete') } do
чому локаль?

2023-04-19 16:28 UTC, loqimean commented on spec/requests/products_spec.rb
> +    let(:valid_product_attributes) { attributes_for(:product, :diaper, { id: 1, sum: "" }) }
а чому це валідні параметри?) сума ж пуста

2023-04-19 16:31 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +                  notice: t(".created")
done

2023-04-19 16:31 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +                notice: t(".deleted")
done

2023-04-19 16:34 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +            = link_to account_product_path(I18n.locale, product), method: :delete, data: { confirm: t('.confirm_delete') } do
в мене без локалі був шлях /id:/products/:id, тому я додала локаль, бо замість en або ukr бралась айдішка

написала тобі в тг

2023-04-19 18:05 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +    let(:valid_product_attributes) { attributes_for(:product, :diaper, { id: 1, sum: "" }) }
done

2023-04-24 13:32 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    @product.destroy
done

2023-04-24 13:36 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          - @product.prices.map do |price|
done

2023-04-24 13:36 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +            span = "#{price.category.name}: #{price.sum}"
done

2023-04-24 14:08 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +              span = "#{price.category.name}: #{price.sum}"
done

2023-04-24 14:36 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    categories = @product.prices.map(&:category)
done

2023-04-24 19:46 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    non_existing_categories = Category.where.not(id: @product.categories_by_prices.select(:id))
scope

2023-04-24 19:46 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    @product.prices.build(non_existing_categories.map { |category| { category: category } })
створи метод класу

2023-04-24 19:55 UTC, mykhailovasylenchuk commented on app/controllers/account/products_controller.rb
> +    @product.prices.build(non_existing_categories.map { |category| { category: category } })
і там роби білд

2023-04-24 19:56 UTC, mykhailovasylenchuk commented on app/models/product.rb
> +  has_many :categories_by_prices, through: :prices, source: :category
```suggestion
  has_many :prices, as: :priceable, dependent: :destroy
  has_many :categories_by_prices, through: :prices, source: :category
```

2023-04-24 19:59 UTC, mykhailovasylenchuk commented on app/views/account/products/index.html.slim
> +            - product.prices.includes(:category).map do |price|
може each? Яка різниця між ними?

2023-04-24 20:00 UTC, mykhailovasylenchuk commented on app/views/account/products/show.html.slim
> +          - @product.prices.includes(:category).map do |price|
і тут

2023-04-24 20:01 UTC, mykhailovasylenchuk commented on app/views/account/products/show.html.slim
> +          = link_to account_product_path(I18n.locale, @product), method: :delete,
ну має бути :locale/products/:id, щось не добре загалом в конфігах апки якщо тобі не виходить прокинути

2023-04-25 06:21 UTC, loqimean commented on app/views/account/products/index.html.slim
> +            = link_to account_product_path(I18n.locale, product), method: :delete, data: { confirm: t('.confirm_delete') } do
ну так це тому, що нема дефолт констрейнта

2023-04-25 06:21 UTC, loqimean commented on app/views/account/products/index.html.slim
> +            = link_to account_product_path(I18n.locale, product), method: :delete, data: { confirm: t('.confirm_delete') } do
давай фіксай)

2023-04-25 14:31 UTC, heroisaprinciple commented on app/views/account/products/show.html.slim
> +          - @product.prices.includes(:category).map do |price|
done

2023-04-25 14:32 UTC, heroisaprinciple commented on app/models/product.rb
> +  has_many :categories_by_prices, through: :prices, source: :category
done

2023-04-25 14:32 UTC, heroisaprinciple commented on app/models/product.rb
> +  # has_many :categories, through: :category_categoryables
done

2023-04-25 14:41 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
> +    non_existing_categories = Category.where.not(id: @product.categories_by_prices.select(:id))
done

2023-04-25 20:49 UTC, mykhailovasylenchuk commented on app/models/category.rb
> +  scope :not_existing_categories, ->(product) { where.not(id: product.categories_by_prices.select(:id)) }
селект не використовуй в скоупі, тому що скоупи мають з'єднуватися з іншими скоупами

2023-04-25 21:05 UTC, heroisaprinciple commented on app/views/account/products/index.html.slim
> +            = link_to account_product_path(I18n.locale, product), method: :delete, data: { confirm: t('.confirm_delete') } do
написала тобі знову)))

2023-04-27 07:32 UTC, loqimean commented on app/models/category.rb
> +  scope :not_existing_categories, ->(product) { where.not(id: product.categories_by_prices.select(:id)) }
`unsigned_categories`, щось таке

2023-04-27 07:32 UTC, loqimean commented on app/models/product.rb
> +    not_existing_categories = Category.not_existing_categories(self)
```suggestion
    not_existing_categories = Category.not_existing_categories(self)

```

2023-04-27 07:32 UTC, loqimean commented on app/views/account/products/show.html.slim
> +          = link_to edit_account_product_path(id: @product) do
але айдішка досі тут)

2023-04-27 07:32 UTC, loqimean commented on spec/requests/products_spec.rb
> +        end.not_to change { price.priceable.title }.from("diaper")
Яка різниця, з чого воно не поміняє, головне, що воно НЕ поміняє велʼю
```suggestion
        end.not_to change(price.priceable, :title)
```

2023-04-28 12:08 UTC, heroisaprinciple commented on app/models/category.rb
> +  scope :not_existing_categories, ->(product) { where.not(id: product.categories_by_prices.select(:id)) }
done

2023-04-28 12:10 UTC, heroisaprinciple commented on app/models/product.rb
> +    not_existing_categories = Category.not_existing_categories(self)
done

2023-04-28 12:17 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +        end.not_to change { price.priceable.title }.from("diaper")
done

2023-04-28 13:09 UTC, loqimean commented on app/controllers/account/products_controller.rb
от тепер контроллер гарно виглядає, як і має, skinny

2023-04-28 13:09 UTC, loqimean commented on app/views/account/products/new.html.slim
> +    = f.submit t('.create_button'), class: 'btn btn-success mr-2', id: 'submit', data: { action: "click->price-form#submit" }
анвіщо айдішка? вона сама не сетається?

2023-04-28 13:09 UTC, loqimean commented on app/views/account/products/show.html.slim
> +          = link_to account_product_path(id: @product), method: :delete,
досі тут))

2023-04-28 13:09 UTC, loqimean commented on spec/requests/products_spec.rb
> +    let(:valid_product_attributes) { attributes_for(:product, :diaper, { id: 1, sum: 10.4 }) }
навіщо цей хеш? і взагалі можна прописати неявним хешом

2023-04-28 13:09 UTC, loqimean commented on spec/requests/products_spec.rb
> +      expect { product.to change(Product, :count).by(-1) }
а це ще що таке, щось максимально дивне

2023-04-28 13:14 UTC, heroisaprinciple commented on app/views/account/products/new.html.slim
> +    = f.submit t('.create_button'), class: 'btn btn-success mr-2', id: 'submit', data: { action: "click->price-form#submit" }
до того категорі айді не будуть передаватись в параметрах так як треба, разом з цінами
говорила тобі про це давно

2023-04-28 13:17 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +      expect { product.to change(Product, :count).by(-1) }
переробила, зараз подивишся

2023-04-28 13:32 UTC, heroisaprinciple commented on spec/requests/products_spec.rb
> +    let(:valid_product_attributes) { attributes_for(:product, :diaper, { id: 1, sum: 10.4 }) }
done

2023-04-28 13:33 UTC, heroisaprinciple commented on app/controllers/account/products_controller.rb
ставлю тобі лайк

2023-04-29 11:01 UTC, loqimean commented on app/models/category.rb
> +  scope :unsigned_categories, ->(product) { where.not(id: product.categories_by_prices.select(:id)) }
можна без селекта, воно саме візьме айдішки

2023-04-30 17:22 UTC, heroisaprinciple commented on app/models/category.rb
> +  scope :unsigned_categories, ->(product) { where.not(id: product.categories_by_prices.select(:id)) }
done

2023-05-01 06:37 UTC, loqimean approved these changes

2023-05-01 18:31 UTC, merged