Zer 344 correct the algorithm of drop down lists for years and months
ita-social-projects/ZeroWaste pull request #386
Opened 2023-03-08 18:03 UTC by Arturbednarskiy

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

correct the algorithm of drop-down lists for years and months, after changing the number for years, the last chosen months should be dropped.

## Summary of change

- after changing the input_child_info_controller.js file, the algorithm started to drop the month when the year changes.
- created the file reset_month_value_spec.rb to test this change in the algorithm

## Testing approach

Capybara test

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-08 20:34 UTC, loqimean requested changes

2023-03-09 07:49 UTC, mykhailovasylenchuk commented on app/javascript/controllers/input_child_info_controller.js
> +    const previous_month_value = this.monthTarget.value;
і в js ми юзаємо кемл кейс

2023-03-09 09:22 UTC, Arturbednarskiy commented on spec/features/reset_month_value_spec.rb
> +RSpec.describe "Year changed", request: true do
додав, тип тесту. а реквест був зайвий, дякую

2023-03-09 09:49 UTC, Arturbednarskiy commented on app/javascript/controllers/input_child_info_controller.js
>      for (let i = 0; i <= amount_options; i++) {
оке, дякую

2023-03-09 09:54 UTC, Arturbednarskiy commented on spec/features/reset_month_value_spec.rb
> +    month_select = find("#child_months")
добре,

2023-03-09 11:02 UTC, Arturbednarskiy commented on app/javascript/controllers/input_child_info_controller.js
> +    (e.target.value !== '')
виправлю

2023-03-09 12:40 UTC, mykhailovasylenchuk approved these changes

2023-03-09 12:47 UTC, merged