Create sitemap.xml
ita-social-projects/ZeroWaste pull request #396
Opened 2023-03-23 21:45 UTC by Userlastname

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @loqimean 
- [ ] @VasylenchukMischa

## Summary of issue

Create sitemap.xml

## Summary of change

Created sitemap.xml(uk/en)

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-25 17:26 UTC, mykhailovasylenchuk commented on config/routes.rb
> +    get "/en/sitemap.xml", to: "sitemap#show", defaults: { format: "xml", locale: "en" }
А скоуп з локалями для чого?

2023-03-25 18:11 UTC, loqimean requested changes
коменти в чаті - прав

2023-03-25 18:11 UTC, loqimean commented on spec/requests/sitemap.spec.rb
> +    end
прав

2023-03-25 18:11 UTC, loqimean commented on config/routes.rb
> +    get "/en/sitemap.xml", to: "sitemap#show", defaults: { format: "xml", locale: "en" }
ага

2023-03-27 18:22 UTC, loqimean commented on spec/requests/sitemap.spec.rb
> +  describe "GET /show" do
```suggestion
  describe "GET #show" do
```

2023-03-27 18:22 UTC, loqimean commented on config/routes.rb
> +    get "/sitemap.xml", to: "sitemap#show", defaults: { format: "xml" }, as: :sitemap
навіщо дефолт

2023-03-27 18:22 UTC, loqimean commented on app/controllers/sitemap_controller.rb
> +  end
де тести?

2023-03-27 18:22 UTC, loqimean commented on app/controllers/sitemap_controller.rb
> +  end
чому я бачу месидж, що нема тестів?

2023-03-30 07:35 UTC, loqimean commented on config/routes.rb
> +    get "/sitemap", to: "sitemap#index", constraints: { format: /(html|xml)/ }
навіщо ці констрейнти?

2023-03-30 07:35 UTC, loqimean commented on app/views/sitemap/index.xml.builder
> +      xml.changefreq "weekly"
ні

2023-03-30 11:22 UTC, loqimean approved these changes

2023-03-30 11:24 UTC, merged