Add migration createCalculators
ita-social-projects/ZeroWaste pull request #4
Opened 2021-04-09 13:25 UTC by PavloMS

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-04-09 13:31 UTC, maksymst requested changes
Also, change your commit message and PR title to conform a format "TICKET_ID COMMIT_MESSAGE"

2021-04-09 13:31 UTC, maksymst commented on db/migrate/20210409131859_create_calculators.rb
> +      t.timestamps
Please fix indentation

2021-04-09 13:38 UTC, PavloMS commented on db/migrate/20210409131859_create_calculators.rb
> +      t.timestamps
Made requested changes

2021-04-09 13:43 UTC, PavloMS commented on db/migrate/20210409131859_create_calculators.rb
> +      t.timestamps
Change commit to correct format

2021-04-09 13:55 UTC, PavloMS commented
> Also, change your commit message and PR title to conform a format "TICKET_ID COMMIT_MESSAGE"

Change commit to correct format

2021-04-09 20:35 UTC, maksymst approved these changes

2021-04-10 13:14 UTC, maksymst approved these changes

2021-04-11 11:51 UTC, merged