Feature/add new calcucator design
ita-social-projects/ZeroWaste pull request #417
Opened 2023-06-17 17:49 UTC by AndriyAndriyovuch

## Code reviewers

- @loqimean 

## Summary of issue

fix calculator's old and new designs

## Summary of change

- move designes to partials
- rewrite old design (now it works like new under hood)
- replace exit bu
- fix downgrade in migration
- replace cross (exit) with arrow (like back) in calculator and move it to the left

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-06-21 07:45 UTC, loqimean commented
стрілочку чуть меньшу зроби і дай текст, щось типу "На головну"

2023-06-21 18:39 UTC, loqimean commented on app/assets/stylesheets/pages/calculator.scss
> +  width: auto!important;
```suggestion
  width: auto !important;
```

2023-06-21 18:39 UTC, loqimean commented on app/assets/stylesheets/pages/calculator.scss
> +  width: 30px;
парні числа мають бути

2023-06-21 18:39 UTC, loqimean commented on app/assets/stylesheets/pages/calculator.scss
> +  width: 100%!important;
```suggestion
  width: 100% !important;
```

2023-06-21 18:39 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +    (-1..2).map { |year| "#{year} #{t("datetime.prompts.year").downcase.pluralize(count: year, locale: I18n.locale)}" }
а чому з мінус один?

2023-06-21 18:39 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +    (-1..2).map { |year| "#{year} #{t("datetime.prompts.year").downcase.pluralize(count: year, locale: I18n.locale)}" }
щось дивно виглядає

2023-06-21 18:39 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +    (-1..11).map { |month| "#{month} #{t("datetime.prompts.month").downcase.pluralize(count: month, locale: I18n.locale)}" }
чому мінус один?)

2023-06-21 18:39 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +    (-1..11).map { |month| "#{month} #{t("datetime.prompts.month").downcase.pluralize(count: month, locale: I18n.locale)}" }
month_number - називай змінні тим, що вони містять

2023-06-21 18:39 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +  end
не то щось, винеси туди юзай просто `Flipper[:new_calculator_design].enabled?`

2023-06-21 18:39 UTC, loqimean commented on app/views/calculators/_old_calculator.html.slim
> +                        selected: months_collection[1],
чому 1 а не перший?)

2023-06-21 18:39 UTC, loqimean commented on app/views/calculators/_old_calculator.html.slim
> +                        selected: years_collection[1],
те ж

2023-06-21 18:39 UTC, loqimean commented on app/views/calculators/_old_calculator.html.slim
> +                        selected: years_collection[1],
най нічого не буде вибране взагалі

2023-06-22 20:48 UTC, AndriyAndriyovuch commented on app/views/calculators/_old_calculator.html.slim
> +                        selected: years_collection[1],
changes to prompt, it will help user

2023-06-22 20:50 UTC, AndriyAndriyovuch commented on app/helpers/calculators_helper.rb
> +    (-1..2).map { |year| "#{year} #{t("datetime.prompts.year").downcase.pluralize(count: year, locale: I18n.locale)}" }
there was a bug with selected, after i had removed it there is no reason to set negative data

2023-06-26 16:30 UTC, loqimean requested changes

2023-06-26 16:30 UTC, loqimean commented on app/views/calculators/calculator.html.slim
> +    = t 'calculators.show.to_main'
і чому текст у тебе поза лінкою?))

2023-06-26 16:30 UTC, loqimean commented on app/views/calculators/_old_calculator.html.slim
> +                                           data:{ controller: "input-child-info",
```suggestion
                                           data: { controller: "input-child-info",
```

2023-06-28 07:02 UTC, loqimean commented on app/views/calculators/calculator.html.slim
> +    = image_tag "arrow-left.svg", class:"z-1"
```suggestion
    = image_tag "arrow-left.svg", class: "z-1"
```

2023-06-30 05:50 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +    when "new" then (0..11).map(&:to_s)
```suggestion
    when "new" then (0..11).to_a
```
цього мало б бути достатньо

2023-06-30 05:50 UTC, loqimean commented on app/views/calculators/_new_calculator.html.slim
> +                              collection: 0..11,
тут хелпер теж юзани

2023-06-30 06:38 UTC, AndriyAndriyovuch commented on app/helpers/calculators_helper.rb
> +    when "new" then (0..11).map(&:to_s)
done

2023-06-30 06:55 UTC, loqimean approved these changes

2023-06-30 07:20 UTC, merged