Add localization for the Ukrainian language in the calculator feature#419
ita-social-projects/ZeroWaste pull request #422
Opened 2023-07-04 18:26 UTC by lbeketl

dev

* [Localization for the Ukrainian language in the calculator feature#419](https://github.com/ita-social-projects/ZeroWaste/issues/419)

## Code reviewers

- [ ] @loqimean

## Summary of change
* add  localization for the Ukrainian language in the calculator feature

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

![image](https://github.com/ita-social-projects/ZeroWaste/assets/55595579/ee4b744a-4a14-4d9a-937f-443d87e7ac00)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/55595579/207d1da4-7112-4d7c-bed2-f92190b7bbf3)

2023-07-05 15:04 UTC, AndriyAndriyovuch requested changes

2023-07-05 15:04 UTC, AndriyAndriyovuch commented on app/models/calculator.rb
>                     uniqueness: true
"ґрунт, підгузник, бур'ян, єнот, Їжак"

There names are not valid

2023-07-05 18:19 UTC, lbeketl commented on app/models/calculator.rb
>                     uniqueness: true
resolved

2023-07-05 19:25 UTC, AndriyAndriyovuch requested changes

2023-07-05 19:25 UTC, AndriyAndriyovuch commented on spec/requests/calculators_spec.rb
> +
also add validation to error message you wrote in model's validation

2023-07-05 20:34 UTC, AndriyAndriyovuch approved these changes

2023-07-06 07:32 UTC, loqimean commented on app/models/calculator.rb
> +                   format: { with: /\A[a-zA-Zа-яієїґ'А-ЯІЄЇҐ0-9\s]+\z/, message: :name_format_validation },
а навіщо тут кавичка?

2023-07-06 07:32 UTC, loqimean commented on spec/requests/calculators_spec.rb
> +  describe "POST /account/calculators" do
describe "METHOD #action"

2023-07-06 07:36 UTC, lbeketl commented on app/models/calculator.rb
> +                   format: { with: /\A[a-zA-Zа-яієїґ'А-ЯІЄЇҐ0-9\s]+\z/, message: :name_format_validation },
Це апостроф, типу якшо хтось схоче назвати калькулятор словом в якому буде '

2023-07-06 13:18 UTC, loqimean commented on app/models/calculator.rb
> +                   format: { with: /\A[a-zA-Zа-яієїґ'А-ЯІЄЇҐ0-9\s]+\z/, message: :name_format_validation },
а, окі, ну насправді я б не робив цієї валідації.., але нехай вже буде

2023-07-07 15:28 UTC, loqimean approved these changes

2023-07-08 12:57 UTC, merged