Move controller specs to requests folder
ita-social-projects/ZeroWaste pull request #423
Opened 2023-07-05 10:30 UTC by HoshkoS

## Code reviewers

@loqimean

## Summary of issue

Move controller specs to requests folder.

## Summary of change

Rewrote controller specs to request (type: :request)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-07-05 18:47 UTC, AndriyAndriyovuch requested changes

2023-07-05 18:47 UTC, AndriyAndriyovuch commented on spec/requests/calculators_spec.rb
>    describe "GET /calculator" do
```suggestion
  describe "GET /calculator" do
    before do
      get calculator_path
    end

```

2023-07-05 18:47 UTC, AndriyAndriyovuch commented on spec/requests/calculators_spec.rb
> +
```suggestion
```

2023-07-05 18:47 UTC, AndriyAndriyovuch commented on spec/requests/calculators_spec.rb
```suggestion
```

2023-07-05 18:47 UTC, AndriyAndriyovuch commented on spec/requests/diaper_calculators_spec.rb
>          expect(response.status).to eq(422)
```suggestion
        expect(response).to be_unprocessable
```

change it as you already here

2023-07-05 18:47 UTC, AndriyAndriyovuch commented on spec/requests/calculators_spec.rb
>    describe "POST /receive_recomendations" do
remove there recieve_recomendations tests, they are useless, this feature is not available at the moment

2023-07-05 18:47 UTC, AndriyAndriyovuch commented on spec/requests/calculators_spec.rb
also fix ```have_http_status(200)``` to ```be_successful```

2023-07-05 20:29 UTC, AndriyAndriyovuch approved these changes

2023-07-06 07:29 UTC, loqimean commented on spec/requests/calculators_spec.rb
> +    end
що це за тест?

2023-07-06 07:29 UTC, loqimean commented on spec/requests/calculators_spec.rb
> +    end
та не тре його сюди

2023-07-06 07:29 UTC, loqimean commented on spec/requests/calculators_spec.rb
> +    end
в цьому випадку

2023-07-06 07:29 UTC, loqimean commented on spec/requests/calculators_spec.rb
>        expect(response).to render_template(:calculator)
інклуд контент якийсь

2023-07-06 08:59 UTC, HoshkoS commented on spec/requests/calculators_spec.rb
> +    end
Це тест перенесений з файлу, що знаходився в папці controllers. Наскільки я розумію це перевірка на те, щоб при даному запиті не створювався новий об'єкт типу Calculator.
В теорії його можна видалити, оскільки запит get логічно не повинен створювати нові об'єкти.

2023-07-10 16:51 UTC, loqimean approved these changes

2023-07-11 08:18 UTC, loqimean approved these changes

2023-07-11 08:19 UTC, merged