Feature/admin/button products
ita-social-projects/ZeroWaste pull request #429
Opened 2023-07-06 08:55 UTC by glckfndr

## Code reviewers

- @loquimean

## Summary of issue

Add button Products to header on Adnin Page

## Summary of change

- add list item Products in app/views/layouts/_account_navbar.html.slim

2023-07-06 11:22 UTC, AndriyAndriyovuch requested changes
UK locale is missing

![Знімок екрану з 2023-07-06 14-21-25](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/8e336813-ee03-43d6-9432-833ad09a33a1)

2023-07-06 17:19 UTC, AndriyAndriyovuch approved these changes

2023-07-07 12:17 UTC, loqimean commented on config/locales/uk/uk.yml
> +      products: "Продукти"
а англійський текст є?

2023-07-07 12:17 UTC, loqimean commented on Gemfile.lock
> +    zeitwerk (2.6.8)
забери це зараз

2023-07-07 12:22 UTC, glckfndr commented on config/locales/uk/uk.yml
> +      products: "Продукти"
Звичайно, Андрій робив зауваження, що нема українського тексту.

2023-07-07 12:30 UTC, glckfndr commented on Gemfile.lock
> +    zeitwerk (2.6.8)
забрав, це саме якось виставилось. Я нічого не міняв.

2023-07-07 12:31 UTC, glckfndr commented on config/locales/uk/uk.yml
> +      products: "Продукти"
![image](https://github.com/ita-social-projects/ZeroWaste/assets/24854291/cb955c42-85f5-4189-936b-bbfa570376bf)

2023-07-07 13:40 UTC, loqimean commented on Gemfile.lock
> +   2.3.26
де нова строка?

2023-07-07 13:40 UTC, loqimean commented on config/locales/en/en.yml
> +      products: "Products"
ну от не було

2023-07-07 13:40 UTC, loqimean commented on config/locales/uk/uk.yml
> +      products: "Продукти"
ну от не було

2023-07-07 13:49 UTC, glckfndr commented on Gemfile.lock
> +   2.3.26
Ніби не повинно бути там нової строки, бо її нема на develop.

2023-07-07 13:53 UTC, glckfndr commented on Gemfile.lock
> +   2.3.26
![image](https://github.com/ita-social-projects/ZeroWaste/assets/24854291/9e4cefac-c558-4b4b-808c-fa4cbe8d5d62)

2023-07-07 13:55 UTC, glckfndr commented on Gemfile.lock
> +   2.3.26
![image](https://github.com/ita-social-projects/ZeroWaste/assets/24854291/217cc560-acc2-432a-94ba-f8e5aea9301f)

2023-07-07 14:19 UTC, glckfndr commented on Gemfile.lock
> +   2.3.26
додав пусту стрічку

2023-07-10 17:54 UTC, loqimean approved these changes

2023-07-10 18:14 UTC, merged