ZER-17 Implement simple formula field evaluating
ita-social-projects/ZeroWaste pull request #47
Opened 2021-04-27 13:10 UTC by PavloMS

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-04-28 08:54 UTC, maksymst requested changes

2021-04-28 08:54 UTC, maksymst commented on spec/models/calculation_spec.rb
> +    it 'Should be valid' do
Here and below https://github.com/rubocop/rspec-style-guide#should-in-example-docstrings

2021-04-28 08:54 UTC, maksymst commented on spec/models/calculation_spec.rb
> +      calculation = Calculation.new(value: 'P1 + 2')
use factory to build Calculation

2021-04-29 06:01 UTC, maksymst requested changes

2021-04-29 06:01 UTC, maksymst commented on spec/models/calculation_spec.rb
> +    subject(:result) { calculation.result(parameters) }
```suggestion
    subject { calculation.result(parameters) }
```

2021-04-29 06:01 UTC, maksymst commented on spec/models/calculation_spec.rb
> +    subject(:calculation) { create(:calculation, value: value) }
```suggestion
    let(:calculation) { create(:calculation, value: value) }
```

2021-04-29 06:01 UTC, maksymst commented on spec/models/calculation_spec.rb
> +      it { expect(result).to eq 4 }
```suggestion
      it { is_expected.to eq 4 }
```

2021-04-29 09:40 UTC, PavloMS commented on spec/models/calculation_spec.rb
> +      it { expect(result).to eq 4 }
Done

2021-04-29 10:48 UTC, maksymst approved these changes

2021-04-29 10:48 UTC, ochupa approved these changes

2021-04-29 10:49 UTC, merged