chore: Update Bootstrap to 5.0 (in package.json)
ita-social-projects/ZeroWaste pull request #478
Opened 2023-07-12 12:53 UTC by glckfndr

## Code reviewers

- @loqimean 

## Summary of issue

Update Bootstrap to version 5.0

## Summary of change

1. In file package.json set "dependencies": { ...
        "bootstrap": "^5.0.0",  ...}
2. Execute in CLI 
        yarn install

2023-07-12 17:56 UTC, AndriyAndriyovuch requested changes
![Знімок екрану з 2023-07-12 20-55-25](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/6aa531a6-b85e-43c4-9d84-aa2d9d0867dd)

Fix it

2023-07-19 19:28 UTC, glckfndr commented
> 

![image](https://github.com/ita-social-projects/ZeroWaste/assets/24854291/fa00fd53-8a97-4309-8152-32f5b6d7139f)

2023-07-27 11:29 UTC, AndriyAndriyovuch commented on app/assets/stylesheets/application.scss
> +}
remove this AI comments

2023-07-27 11:29 UTC, AndriyAndriyovuch commented on app/assets/stylesheets/application.scss
> +}
empty line

2023-07-27 11:35 UTC, AndriyAndriyovuch requested changes
![Знімок екрану з 2023-07-27 14-33-35](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/2cd24596-402c-4dfb-91d5-a13f6f034417)

You need to update your branch from fresh version of develop and fix conflicts
also it's needed for GitHub actions (your branch doesn't have those)

![Знімок екрану з 2023-07-27 14-30-44](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/cd1ddbf8-0c3a-4ae2-a038-4067bd8dfad7)

Selector arrows are not the same as before

2023-08-01 16:51 UTC, AndriyAndriyovuch commented on app/javascript/controllers/handle_browser_tab_controller.js
> +        this.iconTarget.setAttribute('src', e.target.result);
```suggestion
        this.iconTarget.setAttribute('src', e.target.result);
```

2023-08-01 16:51 UTC, AndriyAndriyovuch commented on app/javascript/controllers/handle_browser_tab_controller.js
> +  }
```suggestion
  } 
```

2023-08-01 16:59 UTC, AndriyAndriyovuch commented on app/views/account/site_settings/edit.html.slim
> +        = ""
```suggestion
            .d-inline-flex.align-items-baseline
        = f.label t(".file_select"), for: :site_setting_favicon, class: "btn btn-success me-2 mb-4"
        div[data-handle-browser-tab-target="faviconFile"]     

```

2023-08-02 07:55 UTC, AndriyAndriyovuch commented on app/views/account/categories/edit.html.slim
> +      i.fa.fa-times-circle
![Знімок екрану з 2023-08-02 10-55-11](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/16e29ed8-ef6e-471e-9702-861f5ad21b2f)

2023-08-02 10:20 UTC, glckfndr commented on app/views/account/categories/edit.html.slim
> +      i.fa.fa-times-circle
це автоматично виправилось коли я назвав кнопку apply_button

2023-08-02 10:43 UTC, AndriyAndriyovuch approved these changes

2023-08-04 08:25 UTC, loqimean commented on app/assets/images/selector-arrow.svg
що це таке маленьке?

2023-08-04 08:25 UTC, loqimean commented on app/views/account/calculators/edit.html.slim
> +            span.me-1 =t('.form.cancel_button')
а це чому поміняв? давай повертай локалізацію

2023-08-04 08:25 UTC, loqimean commented on app/views/account/categories/edit.html.slim
> +      span.me-1 =t('.cancel_button')
теж повертай

2023-08-04 08:25 UTC, loqimean commented on app/views/account/categories/edit.html.slim
> +    = f.submit "", value: t('.update_button'), class: 'btn btn-success me-2'
а це ще що таке? чому велʼю є, а кнопка нічого не має? це ще для чого?

2023-08-04 08:25 UTC, loqimean commented on yarn.lock
> +"@popperjs/core@^2.11.8":
а нам це точно тре?

2023-08-04 08:25 UTC, loqimean commented on config/initializers/simple_form_bootstrap.rb
> -CUSTOM_CONTROL_LABEL   = "custom-control-label"
а це навіщо видалялося-мінялося?

2023-08-04 08:34 UTC, glckfndr commented on config/initializers/simple_form_bootstrap.rb
> -CUSTOM_CONTROL_LABEL   = "custom-control-label"
для 5 Bootstrap

2023-08-04 08:34 UTC, glckfndr commented on yarn.lock
> +"@popperjs/core@^2.11.8":
точно тре, бо інакше помилки вилязять.

2023-08-04 08:34 UTC, glckfndr commented on app/views/account/categories/edit.html.slim
> +    = f.submit "", value: t('.update_button'), class: 'btn btn-success me-2'
це я змерджив із двевлора. Це не моя творчість.

2023-08-04 08:35 UTC, glckfndr commented on app/views/account/categories/edit.html.slim
> +      span.me-1 =t('.cancel_button')
Це я змерджив із девелопа. Не моя творчість.

2023-08-04 08:35 UTC, glckfndr commented on app/views/account/calculators/edit.html.slim
> +            span.me-1 =t('.form.cancel_button')
Це я змерджив із девелопа. Не моя творчість.

2023-08-04 08:36 UTC, glckfndr commented on app/assets/stylesheets/application.scss
> +}
це для того, щоб коли клікаємо на пусте поле то не з'являлося віно завантаження файлу.

2023-08-04 08:37 UTC, glckfndr commented on app/assets/images/selector-arrow.svg
Андрій загадав винести подвійну стрілку в окремий файл.

2023-08-05 13:18 UTC, loqimean commented on app/assets/images/selector-arrow.svg
не загадав, а казав, і норм, тік вона якась дуже мала, це не ок

2023-08-05 13:23 UTC, loqimean commented on app/assets/images/selector-arrow.svg
де ти взяв її?

2023-08-05 13:23 UTC, loqimean commented on app/assets/images/selector-arrow.svg
> +<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns='http://www.w3.org/2000/svg' width="4" height="5" viewBox='-4 0 10 5'><path fill='%23343a40' d='M2 0L0 2h4zm0 5L0 3h4z'/></svg>
нова строка

2023-08-05 13:23 UTC, loqimean commented on app/assets/stylesheets/application.scss
> +}
всм виніс, якщо воно тут

2023-08-05 13:23 UTC, loqimean commented on app/assets/stylesheets/application.scss
> +}
це костиль, видаляй

2023-08-05 13:23 UTC, loqimean commented on app/views/account/calculators/edit.html.slim
> +            span.me-1 =t('.form.cancel_button')
всм не твоя творчість? з мастера прийшло "buttons.cancel", а ти його видалив, ну чи з девелопа прийшло

2023-08-05 13:23 UTC, loqimean commented on app/views/account/categories/edit.html.slim
> +    = f.submit "", value: t('.update_button'), class: 'btn btn-success me-2'
всм не твоя творчість, якщо воно пише твої зміни, і знову код, який внесли бачу видалили??

2023-08-05 13:23 UTC, loqimean commented on app/views/account/categories/edit.html.slim
> +      span.me-1 =t('.cancel_button')
повертай давай

2023-08-05 13:23 UTC, loqimean commented on app/views/account/categories/edit.html.slim
> +      i.fa.fa-times-circle
давай вертай, ти погано замерджив

2023-08-07 09:58 UTC, closed without merging

2023-08-07 09:58 UTC, AndriyAndriyovuch commented
reopened in https://github.com/ita-social-projects/ZeroWaste/pull/537