CRUD methods for users on admin side
ita-social-projects/ZeroWaste pull request #481
Opened 2023-07-12 13:34 UTC by HoshkoS

## Code reviewers

 @loqimean 
 @AndriyAndriyovuch 

## Summary of change

- Added missing CRUD methods for users on admin side
- Created view for creating new users
- Added neccessary fuctionality on front-end for new methods

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-07-12 17:27 UTC, AndriyAndriyovuch reviewed
![Знімок екрану з 2023-07-12 19-56-26](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/cdd5821e-d02c-42b5-bd10-30c8f4d74e58)

fix width of the button

![Знімок екрану з 2023-07-12 19-56-35](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/efecbefa-4b4f-4d3c-8e4f-bd48771eecbd)

mark please these fields (first name ans last name) as required

![Знімок екрану з 2023-07-12 20-20-03](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/5c2f20ef-e2c0-4ce3-b138-7ec3c237dac2)

missed locale

2023-07-12 17:27 UTC, AndriyAndriyovuch commented on app/controllers/account/users_controller.rb
> +      render "new"
```suggestion
      render :new
```

2023-07-12 17:27 UTC, AndriyAndriyovuch commented on app/controllers/account/users_controller.rb
>        render "edit"
```suggestion
      render :edit
```

2023-07-12 17:27 UTC, AndriyAndriyovuch commented on app/controllers/account/users_controller.rb
use "resource" and without before action, just in methods where you need it

2023-07-12 17:27 UTC, AndriyAndriyovuch commented on app/controllers/account/users_controller.rb
> +      render "new"
also it returns 200 status code, even if failed

2023-07-12 17:27 UTC, AndriyAndriyovuch commented on app/models/user.rb
```suggestion
```

2023-07-12 19:12 UTC, AndriyAndriyovuch approved these changes

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +    @user = User.new(user_params.merge(confirmed_at: DateTime.current))
https://www.rubydoc.info/github/plataformatec/devise/Devise%2FModels%2FConfirmable:skip_confirmation!

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      UserMailer.with(user: @user).welcome_email.deliver_now if user_params[:send_credentials_email]
```suggestion
      UserMailer.with(user: @user).welcome_email.deliver_now if user_params[:send_credentials_email]

```

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      redirect_to account_user_path(id: @user), notice: t("notifications.user_created")
```suggestion
      redirect_to account_user_path(@user), notice: t("notifications.user_created")
```

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +    update_user_params = user_params
а це що і навіщо?

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +    update_user_params = user_params
задайс resource тут в конкретну змінну, а не роби 20 запитів до БД викликаючи той метод

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      update_user_params = update_user_params.merge(skip_password_validation: true)
в парамсах роби

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      redirect_to account_user_path(id: resource), notice: t("notifications.user_updated")
навіщо айді передавати?

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +    resource.destroy
```suggestion
    resource.destroy

```

2023-07-17 12:22 UTC, loqimean commented on app/controllers/account/users_controller.rb
>      @user ||= User.find(params[:id])
забери мемоізацію звідси, вона тут не працює

2023-07-17 12:22 UTC, loqimean commented on app/mailers/user_mailer.rb
> +    @user = params[:user]
передавай все, що тре так, як в метод, не тре цього всього

2023-07-17 12:22 UTC, loqimean commented on app/mailers/user_mailer.rb
> +    @url  = "https://zerowastelviv.org.ua"
а це навіщо ще?

2023-07-17 12:22 UTC, loqimean commented on app/views/account/users/index.html.slim
> +            td = link_to account_user_path(id: user.id), method: :delete,
```suggestion
            td = link_to account_user_path(user), method: :delete,
```

2023-07-17 12:22 UTC, loqimean commented on app/views/user_mailer/welcome_email.html.erb
> +  <body>
це ще що таке? не тре цього всього

2023-07-17 12:22 UTC, loqimean commented on app/mailers/user_mailer.rb
> +    @user = params[:user]
і де взагалі тести на це все? на мейлери, на контроллери, де це все?

2023-07-17 12:22 UTC, loqimean commented on app/views/user_mailer/welcome_email.html.erb
> +      password:<%= @user.password%>
а відступ?

2023-07-17 12:22 UTC, loqimean commented on app/views/user_mailer/welcome_email.html.erb
> +      To login to the site, just follow this link: <%= @url %>.
домен задається лиш раз і у конфігах, шукай способи його дістати

2023-07-17 18:44 UTC, HoshkoS commented on app/controllers/account/users_controller.rb
> +      redirect_to account_user_path(id: resource), notice: t("notifications.user_updated")
Без айді воно вибиває помилку missing required keys: [:id]. І це в будь-якому з методів

2023-07-25 06:01 UTC, loqimean commented on spec/mailers/user_mailer_spec.rb
> +      expect(mail.body).to include(I18n.t("user_mailer.welcome_email.to_login"))
не тре прям все перевіряти, тік ключове

2023-07-25 06:01 UTC, loqimean commented on spec/mailers/user_mailer_spec.rb
> +      expect(mail.body).to include(I18n.t("user_mailer.welcome_email.thanks"))
і тут

2023-07-25 06:01 UTC, loqimean commented on spec/mailers/user_mailer_spec.rb
> +      expect(mail.body).to include("ZeroWaste")
і тут

2023-07-25 06:01 UTC, loqimean commented on spec/mailers/user_mailer_spec.rb
> +    let(:mail) { UserMailer.welcome_email(user) }
а це я взагалі не певен, що потрібно, це де ти бачила так робити?

2023-07-25 06:01 UTC, loqimean commented on app/views/user_mailer/welcome_email.html.erb
> +      <br> <%= t('.password', password: @user.password) %>
два пробіли

2023-07-25 06:01 UTC, loqimean commented on app/views/user_mailer/welcome_email.html.erb
> +<%= t('.to_login') %>: <%= link_to "ZeroWaste", @url %>.
а тут де відступи?

2023-07-25 06:01 UTC, loqimean commented on app/views/user_mailer/welcome_email.html.erb
і де плейн текст меіл?

2023-07-25 13:18 UTC, HoshkoS commented on spec/mailers/user_mailer_spec.rb
> +    let(:mail) { UserMailer.welcome_email(user) }
https://rspec.info/features/6-0/rspec-rails/mailer-specs/

2023-07-26 16:55 UTC, loqimean requested changes

2023-07-26 16:55 UTC, loqimean commented on spec/mailers/user_mailer_spec.rb
> +    let(:mail) { UserMailer.welcome_email(user) }
найс тоді

2023-07-26 16:55 UTC, loqimean commented on app/views/user_mailer/welcome_email.html.erb
> +</p>
ну та зроби дівом і відповідними параграфами

2023-07-26 16:55 UTC, loqimean commented on app/mailers/user_mailer.rb
> +    @url  = root_url
```suggestion
    @url  = root_url

```

2023-07-26 16:55 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      redirect_to account_user_path(id: @user), notice: t("notifications.user_created")
stiiil actual

2023-07-27 15:33 UTC, HoshkoS commented on app/controllers/account/users_controller.rb
> +      redirect_to account_user_path(id: @user), notice: t("notifications.user_created")
Якщо прописати account_user_path(@user), то воно сприймає юзера як locale і вибиває помилку.

2023-07-28 10:26 UTC, loqimean approved these changes

2023-07-28 10:26 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      redirect_to account_user_path(id: @user), notice: t("notifications.user_created")
тоді ок

2023-07-28 10:26 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +          patch account_user_path(user), params: { user: { email: "" }}
```suggestion
          patch account_user_path(user), params: { user: { email: "" }}

```

2023-07-28 10:26 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +          patch account_user_path(user), params: { user: { email: "" }}
і так скрізь

2023-08-02 14:50 UTC, merged