Set the same size for buttons create and cancel in add and update categories pages
ita-social-projects/ZeroWaste pull request #489
Opened 2023-07-12 18:37 UTC by kos-nastiia

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-07-12 18:46 UTC, kos-nastiia commented
![Screenshot from 2023-07-12 21-45-07](https://github.com/ita-social-projects/ZeroWaste/assets/115086501/40564322-86df-4d56-a1d2-2321ad6e9bee)
![Screenshot from 2023-07-12 21-45-11](https://github.com/ita-social-projects/ZeroWaste/assets/115086501/3091524e-a8cc-4032-9cfd-0ad3d708f237)

2023-07-12 18:59 UTC, AndriyAndriyovuch requested changes

2023-07-12 18:59 UTC, AndriyAndriyovuch commented on app/views/account/categories/edit.html.slim
> +        = f.submit "", value: t('.update_button'), class: 'btn btn-success mr-2 height w-auto'
why there empty name and setted value?
when you tap button like this on little part of a second button becomes tiny and empty, better fix this

2023-07-13 07:02 UTC, loqimean approved these changes

2023-07-13 07:46 UTC, merged