wrong error message on page product when user try to create product without title
ita-social-projects/ZeroWaste pull request #490
Opened 2023-07-12 20:57 UTC by Vlad1kent1

## Code reviewers

@loqimean
@AndriyAndriyovuch

## Summary of issue

wrong error message on page product when user try to create product without title

## Summary of change

- change url link to the action create
- add commit

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-07-13 12:02 UTC, AndriyAndriyovuch requested changes
![Знімок екрану з 2023-07-13 14-51-45](https://github.com/ita-social-projects/ZeroWaste/assets/95449986/eb644897-7503-4022-9c64-b4e0f7107079)

And where's ukrainian locale?

Also you can fix buttons style (hint: look at @kos-nastiia previous PR)

2023-07-13 14:58 UTC, AndriyAndriyovuch commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, url: { action: 'create'}, data: { controller: "price-form" } do |f|
```suggestion
  = simple_form_for @product, url: { action: 'create'}, data: { controller: "price-form" } do |f|
```

rubocop should show you error fot this, use it before push

2023-07-13 22:32 UTC, Vlad1kent1 commented on config/locales/en/en.yml
>      form_errors:
Line 579 has an error format consisting of %{attribute} and %{message}. In this case, %{attribute} is 'Title', and %{message} - these three lines or other messages below line 580. And if these three lines are not commented or deleted, then the result will be: 
![Screenshot from 2023-07-14 01-12-19](https://github.com/ita-social-projects/ZeroWaste/assets/111977759/258ac376-3a6d-46c0-a575-b7f9cd7034a2)

2023-07-17 12:12 UTC, loqimean commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, url: { action: 'create'}, data: { controller: "price-form" } do |f|
який ще екшин, передавай норм урлу

2023-07-17 12:53 UTC, Vlad1kent1 commented on app/views/account/products/new.html.slim
> +  = simple_form_for @product, url: { action: 'create'}, data: { controller: "price-form" } do |f|
виправив

2023-07-18 09:41 UTC, loqimean approved these changes

2023-07-18 09:42 UTC, merged