Add external link icons to all links on the customer's website
ita-social-projects/ZeroWaste pull request #501
Opened 2023-07-17 14:51 UTC by lbeketl

dev

* [Add external link icons to all links on the customer's website.#445](https://github.com/ita-social-projects/ZeroWaste/issues/445)

## Code reviewers

- [ ] @loqimean

### Second Level Review

- [ ] @AndriyAndriyovuch

## Summary of change

* Add external link icons to all links on the customer's website

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

![image](https://github.com/ita-social-projects/ZeroWaste/assets/55595579/7b3f1571-33e0-463c-9fb2-bf232af5710c)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/55595579/a4ba62c7-8bb6-4b10-9a4d-1579ea3ac85e)

2023-07-17 16:50 UTC, loqimean commented on app/assets/stylesheets/pages/calculator.scss
> +    svg {
а якщо я додам ще одну свг-шку?

2023-07-17 16:50 UTC, loqimean commented on app/assets/stylesheets/pages/calculator.scss
> +    svg {
а для спейсінга між елементами юзай флекс і геп

2023-07-17 16:50 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +    if locale
`present?`

2023-07-17 16:50 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +    end
щось не гуд, тип не тре аж такої інтерполяції, а також знову ж таки ,це все дуже абстрактно, давай от `link_to_external` чи типу того

2023-07-17 16:50 UTC, loqimean commented on app/views/layouts/_description_block.html.slim
> +- en_calc_url = zero_waste_url(:en, "diaper-calculator-method-en/")
скоріш `link_to_main_site` чи типу того, бо зараз конфлікт з роут хелперами рельси

2023-07-17 16:50 UTC, loqimean commented on app/views/layouts/_description_block.html.slim
> +          contact_link: link_to_with_icon(zero_waste_url(:en, "contacts/"), t(".contact_us_link")))
ну тип щось таке, бо я щось взагалі не зрозумів, що це тут таке коїться

2023-07-17 16:55 UTC, lbeketl commented on app/helpers/calculators_helper.rb
> +  def zero_waste_url(locale = nil, href)
я думав може пізніше буде необхідність десь заюзати цю іконку без тексту того передав ніл шоб можна було метод використати без тексту

2023-07-26 05:16 UTC, loqimean commented on app/assets/stylesheets/pages/main.scss
> +    }
так а чому ці стилі дублюються?

2023-07-26 05:16 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +      "#{link_text} <i class='fas fa-external-link-alt'></i>".html_safe
тут тобі вже казали, що може бути певна проблема, XSS, перепиши юзаючи щось типу `tag.i`

2023-07-26 05:16 UTC, loqimean commented on app/views/layouts/_description_block.html.slim
> +- ua_link_to_main_site  = zero_waste_url(href: "diaper-calculator-method/")
а це ще навіщо, давай забирай

2023-07-26 05:16 UTC, loqimean commented on app/views/layouts/_description_button.html.slim
> += link_to_external "#{I18n.locale == :en ? 'https://zerowastelviv.org.ua/en/zero-waste-nappies-en/' : 'https://zerowastelviv.org.ua/zero-waste-nappies/'}",
в хелпер отримання урли перенеси

2023-11-16 19:00 UTC, loqimean requested changes

2023-11-16 19:00 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +  end
це трошки не оптимально, зроби можливість передавати ключові параметри, а також додатково щось таке: `def some(text:, **options)`, бо може виникнути потреба передавати наприклад дата атрибути)

2023-11-16 19:00 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +  end
тре писати відразу флексібл код)

2023-11-16 20:51 UTC, loqimean requested changes

2023-11-16 20:51 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +    link_to(url, target: "_blank", rel: "noopener", class: options[:class]) do
а навіщо передавати явно клас?))) передай всі опшини відразу, та і всьо)

2023-11-16 20:51 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +  def link_to_external(link_text, url, **options)
і перші два параметри зроби неймед

2024-08-02 14:58 UTC, iryna-borniak approved these changes

2024-08-07 11:06 UTC, loqimean approved these changes

2024-08-07 11:06 UTC, loqimean commented on app/assets/stylesheets/components/description_block.css
> +  .description-section{
```suggestion
  .description-section {
```

2024-08-08 17:02 UTC, merged