remove "Access Admin Menu" checkbox from site settings
ita-social-projects/ZeroWaste pull request #521
Opened 2023-07-23 11:08 UTC by Vlad1kent1

## Code reviewers

- @loqimean 
- @AndriyAndriyovuch 

## Summary of issue

The "Access to admin menu" checkbox should be removed from the site settings page

## Summary of change

remove "Access Admin Menu" checkbox from site settings

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-07-23 11:11 UTC, Vlad1kent1 commented
Don't know whether to completely remove access_admin_menu feature flag or no

2023-07-23 14:29 UTC, AndriyAndriyovuch approved these changes

2023-07-25 06:19 UTC, loqimean commented
> Don't know whether to completely remove access_admin_menu feature flag or no

yes, remove

2023-07-25 06:20 UTC, loqimean requested changes

2023-07-25 06:20 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +      = Flipper[:new_calculator_design].description
і що це таке? а якщо я додам ще 100 фіча-влагів? що тоді? задача була конкретна - забрати фіча-флаг на адмін аксес

2023-08-06 07:29 UTC, loqimean approved these changes

2023-08-07 09:58 UTC, merged