ZER-6 Create calclator value entry page
ita-social-projects/ZeroWaste pull request #53
Opened 2021-05-04 16:18 UTC by haliapats

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-05-04 19:35 UTC, haliapats commented on config/locales/en.yml
> -      calculate_result_button: "CALCULATE RESULT"
I had to rename the button to Ukrainian, so I localized it in uk.yml

2021-05-06 15:41 UTC, maksymst requested changes

2021-05-06 15:41 UTC, maksymst commented on app/javascript/ajax/result_button.js
> +      baby_weight: $("#weight").val()
this is not required

2021-05-06 15:41 UTC, maksymst commented on app/views/calculators/show.html.erb
> +            <input id="weight" type="text" class="col datepick" />
remove this field

2021-05-06 15:41 UTC, maksymst commented on app/views/calculators/show.html.erb
> +        <button type="submit" id = "result_button" class="btn btn-success ml-3 mt-4">
do you need this change?

2021-05-06 15:41 UTC, maksymst commented on config/locales/en.yml
> -      calculate_result_button: "CALCULATE RESULT"
I understand, but shouldn't it be also in en.yml?

2021-05-06 16:16 UTC, haliapats commented on config/locales/en.yml
> -      calculate_result_button: "CALCULATE RESULT"
Ok, I understood, added back
Thanks)

2021-05-06 16:29 UTC, maksymst approved these changes

2021-05-06 16:32 UTC, merged