Bootstrap5
ita-social-projects/ZeroWaste pull request #537
Opened 2023-08-06 13:53 UTC by glckfndr

## Code reviewers

- [ ] @loqimean 

### Second Level Review

- [ ] @AndriyAndriyovuch 

## Summary of issue

Update code and pages from Bootsrap 4 to Boostrap 5

## Summary of change

2023-08-06 14:01 UTC, AndriyAndriyovuch approved these changes

2023-08-07 18:48 UTC, loqimean requested changes

2023-08-07 18:48 UTC, loqimean commented on app/assets/images/selector-arrow.svg
the same issue, why this icon is so small? where you found it? it should be at least 16px

2023-08-07 18:48 UTC, loqimean commented on app/assets/stylesheets/components/buttons.css
> +   @apply text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-l
what is it..? do you know, that TailwindCSS doesn't have `me` style?

2023-08-07 18:48 UTC, loqimean commented on app/assets/stylesheets/pages/calculator.scss
> +  background-image: url("selector-arrow.svg");
place it under `icons` directory

2023-08-07 18:48 UTC, loqimean commented on app/assets/stylesheets/pages/site_setting.scss
> +}
remove it

2023-08-07 18:48 UTC, loqimean commented on app/views/account/app_configs/edit.html.slim
> +        = f.label :first_price, t('.price')
why this is changed?

2023-08-07 18:48 UTC, loqimean commented on app/views/calculators/old_calculator.html.slim
> +                            class: 'rounded custom-select calc-item',
`calc-item`?

2023-08-07 18:48 UTC, loqimean commented on config/locales/uk/uk.yml
> +        file_select:  'Обери файл'
*оберіть

2023-08-07 18:48 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +          div[data-handle-browser-tab-target="faviconFile"]
div for text content? why not label..?

2023-08-07 20:00 UTC, glckfndr commented on app/assets/stylesheets/components/buttons.css
> +   @apply text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-l
Я не звернув уваги що це TailwindCSS. Повернув назад.

2023-08-07 20:11 UTC, glckfndr commented on app/assets/stylesheets/pages/calculator.scss
> +  background-image: url("selector-arrow.svg");
такого каталогу в проекті не було, тому я створив його в images. Перемістив туди файл.

2023-08-07 20:13 UTC, glckfndr commented on app/assets/stylesheets/pages/site_setting.scss
> +}
це неможливо зробити, бо тоді не вдасться прибрати баг. Коли тиснемо на пусте місце а вискакує меню вибору файла. Я зробив так за порадою Андрія.

2023-08-07 20:15 UTC, glckfndr commented on app/views/account/app_configs/edit.html.slim
> +        = f.label :first_price, t('.price')
якщо подивится нижче, то видно, що усі інші рядки зроблені аналогічно. Тут робробник допустив помилку при копіюванні.

2023-08-07 20:24 UTC, glckfndr commented on app/views/calculators/old_calculator.html.slim
> +                            class: 'rounded custom-select calc-item',
Виправив. Дивно, звідки воно взялося.

2023-08-07 20:24 UTC, glckfndr commented on config/locales/uk/uk.yml
> +        file_select:  'Обери файл'
Виправив

2023-08-07 20:36 UTC, glckfndr commented on app/assets/images/selector-arrow.svg
посилання дав Андрій. Розмір підганявся так, щоб вид був такий як в Bootstrap 4. Для цього я поміняв координати всередині файлу, щоб зовні нічого не задавати.

2023-08-08 08:09 UTC, loqimean commented on app/assets/images/selector-arrow.svg
ну та міняй, heroicons.com тобі в поміч, причому тут розмір соурсу картинки, якщо ти маєш лиш адаптувати картинку під себе там, дле тре

2023-08-08 08:09 UTC, loqimean commented on app/assets/stylesheets/components/buttons.css
> +   @apply text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-l
ну так а тре

2023-08-08 08:09 UTC, loqimean commented on app/assets/stylesheets/pages/calculator.scss
> +  background-image: url("selector-arrow.svg");
ну та яка різниця, був чи не був

2023-08-08 08:10 UTC, loqimean commented on app/assets/stylesheets/pages/site_setting.scss
> +}
яке не можливо, це ізі робиться, якщо трошки уяви проявити та часу приділити без приховання

2023-08-08 08:10 UTC, loqimean commented on app/views/account/app_configs/edit.html.slim
> +        = f.label :first_price, t('.price')
який розробник?

2023-08-08 08:12 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +          div[data-handle-browser-tab-target="faviconFile"]
Я НІКОЛИ НЕ ПРИЙМУ ВАРІАНТ ПО ПРИНЦИПУ ЛИШ БИ ПРАЦЮЄ! Є загально прийняті норми, усні чи ні, де чорним по білому сказано, осьо текст теги, осьо теги для всього іншого. Роби з лейбою

2023-08-08 08:13 UTC, loqimean requested changes

2023-08-08 08:13 UTC, loqimean commented on app/assets/images/icons/selector-arrow.svg
still actual issue

2023-08-08 18:39 UTC, glckfndr commented on app/assets/images/icons/selector-arrow.svg
виправив

2023-08-08 18:40 UTC, glckfndr commented on app/views/account/site_settings/edit.html.slim
> +          div[data-handle-browser-tab-target="faviconFile"]
зробив з label

2023-10-10 19:28 UTC, loqimean commented on app/assets/stylesheets/pages/site_setting.scss
> +}
досі актально

2023-10-10 19:28 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +        = f.input :favicon, class: "form-control", input_html: {id: "site_setting_favicon", data: {  action: "change->handle-browser-tab#setIcon"} }
```suggestion
        = f.input :favicon, class: "form-control", input_html: { id: "site_setting_favicon", data: { action: "change->handle-browser-tab#setIcon" }}

```

2023-10-10 19:28 UTC, loqimean commented on app/views/account/site_settings/edit.html.slim
> +    = f.submit t(".apply_button")
а ще мені цікаво, яким боком ці зміни до оновлення бутстрапу, про що говорить назва ПР-у

2023-11-10 14:41 UTC, merged