Upgrade to rails 7
ita-social-projects/ZeroWaste pull request #541
Opened 2023-08-07 20:18 UTC by kos-nastiia

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-08-08 08:06 UTC, loqimean commented on .rubocop.yml
> +
пише нема нової строки

2023-08-08 08:06 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@tailwind utilities;
так а це чому поміняла?

2023-08-08 08:06 UTC, loqimean commented on app/assets/stylesheets/components/buttons.css
чому видалила?

2023-08-08 08:06 UTC, loqimean commented on config/boot.rb
> -# frozen_string_literal: true
те ж питання

2023-08-08 08:06 UTC, loqimean commented on db/schema.rb
ці зміни я б відмінив

2023-08-08 08:06 UTC, loqimean commented on spec/rails_helper.rb
> +ActiveJob::Base.queue_adapter = :test
а нам це потрібно?

2023-08-08 08:06 UTC, loqimean commented on app/assets/stylesheets/components/buttons.css
чому видалено?

2023-08-08 08:06 UTC, loqimean commented on bin/rails
> -# frozen_string_literal: true
чому нема?

2023-08-08 08:06 UTC, loqimean commented on bin/rails
> -load File.expand_path('spring', __dir__)
чому це видалила?

2023-08-08 08:06 UTC, loqimean commented on bin/rake
> -load File.expand_path('spring', __dir__)
чому нема?

2023-08-08 08:06 UTC, loqimean commented on config/application.rb
> -    config.assets.css_compressor = nil
чому це видалено?

2023-08-08 08:06 UTC, loqimean commented on config/environments/production.rb
> -  }
а це чому видалено?

2023-08-08 08:10 UTC, kos-nastiia commented on app/assets/stylesheets/components/buttons.css
також була помилка на  precompile в при підключенні в application.tailwind.css, а ця кнопка і так ніде не застосовується

2023-08-08 08:11 UTC, kos-nastiia commented on config/environment.rb
> -# frozen_string_literal: true
при апгрейді рельси за замовчуванням видалилось. потрібно повернути?

2023-08-08 08:12 UTC, kos-nastiia commented on spec/rails_helper.rb
> +ActiveJob::Base.queue_adapter = :test
так, без цього тест не проходив

2023-08-08 08:12 UTC, kos-nastiia commented on app/assets/stylesheets/components/buttons.css
ніде не застосовувалось, а хіба викликало помилку на precompile

2023-08-08 08:15 UTC, kos-nastiia commented on config/application.rb
> -    config.assets.css_compressor = nil
також видалилось при апгрейді рельси

2023-08-08 08:16 UTC, kos-nastiia commented on config/environments/production.rb
> -  }
як і це

2023-09-03 19:28 UTC, loqimean requested changes

2023-09-03 19:28 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@tailwind utilities;
але мало би гуд компілитися, ти перевірила, чи версія теілвінда не застара?

2023-09-03 19:28 UTC, loqimean commented on app/assets/stylesheets/components/buttons.css
чому цей файл видалений?

2023-09-03 19:28 UTC, loqimean commented on config/application.rb
> -    config.assets.css_compressor = nil
а це норм, що видалилося? воно нам дійсно не потрібно?

2023-09-03 19:28 UTC, loqimean commented on config/environment.rb
> -# frozen_string_literal: true
ну що означає питання потрібно повернути? ти маєш сама розуміти навіщо ти видалила, чи не видалила

2023-09-03 19:28 UTC, loqimean commented on config/environments/development.rb
> -  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }
це точно нам не тре?

2023-09-03 19:28 UTC, loqimean commented on config/environments/production.rb
> -  }
а ти впевнена, що раз воно ивдалило, то так і має бути?

2023-09-03 19:28 UTC, loqimean commented on config/environments/production.rb
> -  }
ну нам потрібні ці конфіги теж? чи воно саме буде виконувати цей код?))

2023-09-03 19:28 UTC, loqimean commented on config/environments/test.rb
> -  config.eager_load = false
а ці штуки?) теж не потрібні? чи може потрібні? ти перевіряла, чи це ок, що воно це видалило?

2023-09-03 19:28 UTC, loqimean commented on config/initializers/assets.rb
> -Rails.application.config.assets.paths << Rails.root.join("node_modules")
у тебе тут ноди вже нема?

2023-09-03 19:28 UTC, loqimean commented on spec/rails_helper.rb
> +ActiveJob::Base.queue_adapter = :test
який?

2023-10-10 19:25 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@tailwind utilities;
досі актуально

2023-10-10 19:25 UTC, loqimean commented on app/assets/stylesheets/components/buttons.css
досі актуально))

2023-11-11 19:27 UTC, closed without merging