512 favicon validations
ita-social-projects/ZeroWaste pull request #567
Opened 2023-11-17 19:45 UTC by dafeys

dev
## ZeroWaste project

* [ticket 511](https://github.com/ita-social-projects/ZeroWaste/issues/511)
* [ticket 512](https://github.com/ita-social-projects/ZeroWaste/issues/512)

## Code reviewers

- [ ] @kisiohlova 
- [ ] @loqimean 

## Summary of issue

Add validations with error messages for favicon

## Summary of change
Validations of favicon on the Site Settings page allow files:
- size up to 1kb
- resolution up to 180x180
-  aspect ratio only square
-  file type .png or .ico

![messages](https://github.com/ita-social-projects/ZeroWaste/assets/36037839/44168939-e7d8-4b6e-a1c8-729d16660625)

2023-11-18 14:21 UTC, kisiohlova requested changes

2023-11-18 14:21 UTC, kisiohlova commented on config/locales/en/active_storage.yml
> +      file_size_out_of_range: "file too large, please upload file up to 1KB"
```suggestion
      file_size_out_of_range: "file is too big, please upload file up to 1KB"
```

2023-11-18 16:00 UTC, kisiohlova approved these changes

2023-11-28 07:48 UTC, loqimean approved these changes

2023-11-28 07:48 UTC, merged