ZER-60 Create Users page for admins
ita-social-projects/ZeroWaste pull request #59
Opened 2021-05-12 17:13 UTC by ochupa

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-05-12 17:30 UTC, VictoriaBryz submitted a review, later dismissed

2021-05-13 07:02 UTC, maksymst requested changes

2021-05-13 09:42 UTC, ochupa commented on app/views/admin/index.html.erb
> +</div>
Thank you for link. It's really shorter than ordinary html.

2021-05-13 09:42 UTC, ochupa commented on config/locales/en.yml
> +      last_visit: "Last visit"
I've tried to change it.

2021-05-13 09:43 UTC, ochupa commented on spec/requests/admin_spec.rb
> +RSpec.describe "Admin", type: :request do
Ok. I've deleted this testsuite.

2021-05-13 10:43 UTC, maksymst approved these changes

2021-05-13 10:50 UTC, PavloMS approved these changes

2021-05-13 10:55 UTC, merged