584 sandbox
ita-social-projects/ZeroWaste pull request #603
Opened 2023-12-03 21:17 UTC by DmytroStoliaruk

dev
## Zerowaste

* [Issue #584](https://github.com/ita-social-projects/ZeroWaste/issues/584)

## Code reviewers

- [ ] @loqimean
- [ ] @obniavko 

## Summary of issue

Create 'sandbox' mode for Zerowaste database that cancels all database changes after leaving 'sandbox'. It is useful for users or testers who want to add temporally changes to datadase.

## Summary of change

1. Add a new future flag 'Enable sandbox mode' on Site Settings page (not for Production environment)
2. Create class SandBox which implements enable and disable 'sandbox'. For implementing this future is necessary to create  database backup and restore from it.

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

Closes #584

2023-12-13 11:04 UTC, loqimean requested changes

2023-12-13 11:04 UTC, loqimean commented on app/views/account/site_settings/edit.html.erb
> +      </div>
ти можеш задефайнити ці елементи в твоєму контроллері

2023-12-13 11:04 UTC, loqimean commented on app/views/account/site_settings/edit.html.erb
> +      </div>
щоб не писати їх скрізь самому

2023-12-13 11:04 UTC, loqimean commented on app/services/update_feature_flags_service.rb
> +      is_enabled = DatabaseService.sandbox_enable(is_enabled) if feature_name == "sandbox_mode"
а це навіщо?

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    backup_file = File.join(backup_directory, BACKUP_SANDBOX_NAME)
```suggestion
    backup_file = File.join(backup_directory, BACKUP_SANDBOX_NAME)

```

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    backup_file = File.join(backup_directory, BACKUP_SANDBOX_NAME)
і так скрізь

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    dump_flag
тут ти можеш заюзати `tap`

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    BACKUP_DIR
а навіщо ти це повертаєш, якщо у тебе є константа і нічого з нею тут не відбувається

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    BACKUP_DIR
інша справа, що ти тут робиш `init_backup_dir`

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    oldest_file = files.min_by { |f| File.mtime(File.join(BACKUP_ARCHIVE_DIR, f)) }
```suggestion
    oldest_file = files.min_by { |f| File.mtime(File.join(BACKUP_ARCHIVE_DIR, f)) }

```

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    prune_old_backups if Dir.entries(BACKUP_ARCHIVE_DIR).count > 10
число в константу

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    FileUtils.mkdir_p(BACKUP_ARCHIVE_DIR)
от бач, ти те ж саме робив в `backup_directory`

2023-12-13 11:04 UTC, loqimean commented on app/services/database_service.rb
> +    FileUtils.mkdir_p(BACKUP_ARCHIVE_DIR)
а можеш навіть колбеки зробити перед цими методами

2023-12-13 14:08 UTC, DmytroStoliaruk commented on app/javascript/controllers/button_controller.js
> +    loaderMask.style.zIndex = 100;
поправив. лоадер контроллер )

2023-12-13 14:12 UTC, DmytroStoliaruk commented on config/initializers/flipper/flipper.rb
> +  require_relative "../../../app/services/database_service"
поправив

2023-12-13 14:20 UTC, DmytroStoliaruk commented on config/initializers/flipper/flipper.rb
> +  if Rails.env.production?
поправив. поки буде і в prodaction. Після створення staging треба буде розкоменутвати строку 
  # Flipper.remove(:sandbox_mode) if Rails.env.production?
для видалення фліпера з переліку

2023-12-13 14:33 UTC, DmytroStoliaruk commented on lib/tasks/db_task.rake
> +    cmd = "pg_dump -F c -d #{DatabaseService.database_name} -f #{DatabaseService.backup_full_path(args[:filename])}"
додав опис опцій

2023-12-13 14:42 UTC, DmytroStoliaruk commented on spec/support/shared/context/feature_flags.rb
> +end
переробив. Сподіваюсь правильно. Ці писав по зразку попередніх. Якщо нова версія ок, то тести до інших фліперів перероблю...

2023-12-13 15:00 UTC, DmytroStoliaruk commented on spec/services/feature_flags_spec.rb
> +      expect(Flipper).not_to receive(:disable).with("feature_2")
Залишив поки.
Оскільки логіка обробки визову UpdateFeatureFlagsService.new(params).call змінена, (не оновлюється стан фліперу якщо його новий і потосний стан однаковий), то цім тестом я перевіряю, що дійсно стан не оновлюється.
Логіку змінив, щоб виклювити дублювання дій, що мають виконуватися при зміні стану фліперу. наприклад створення повторного бекапу...
можна взагалі прибрати цю строку тесту.

2023-12-13 15:39 UTC, DmytroStoliaruk commented on app/views/account/site_settings/edit.html.erb
> +      </div>
зробив

2023-12-13 15:55 UTC, DmytroStoliaruk commented on app/services/update_feature_flags_service.rb
> +      is_enabled = DatabaseService.sandbox_enable(is_enabled) if feature_name == "sandbox_mode"
спростив логіку - зміна режиму пісочниці тільки у раз зміни стану флагу

2023-12-13 16:11 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +    BACKUP_DIR
поправив на init_backup_dir

2023-12-13 16:11 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +    oldest_file = files.min_by { |f| File.mtime(File.join(BACKUP_ARCHIVE_DIR, f)) }
поправив

2023-12-13 16:13 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +    prune_old_backups if Dir.entries(BACKUP_ARCHIVE_DIR).count > 10
зробив

2023-12-13 16:22 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +    FileUtils.mkdir_p(BACKUP_ARCHIVE_DIR)
зробив

2023-12-13 18:18 UTC, DmytroStoliaruk commented on app/assets/stylesheets/components/loader.css
> +@keyframes loader {
виправленнЯ в процесі...

2023-12-19 19:19 UTC, loqimean requested changes
дуже багато методів не покрито тестами, фіксай

2023-12-19 19:19 UTC, loqimean commented on lib/tasks/db_task.rake
> +    backup_dir = DatabaseService.init_backup_directory
```suggestion
    backup_dir = DatabaseService.init_backup_directory

```

2023-12-19 19:19 UTC, loqimean commented on app/services/database_service.rb
> +  def self.generate_backup_filename
не все тестами покрито

2023-12-19 21:00 UTC, DmytroStoliaruk commented on lib/tasks/db_task.rake
> +    backup_dir = DatabaseService.init_backup_directory
поправив

2023-12-19 21:21 UTC, DmytroStoliaruk commented on app/assets/stylesheets/components/loader.css
> +  border-left-color: green;
в офіційній доці не знійшов. на стековерфлоу також непрацюючі варіанти.
А поза лейером тому ще це стиль CSS а не Tailwind

2023-12-20 19:25 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +  def self.generate_backup_filename
додав тести

2023-12-24 11:06 UTC, mdotvasylenchuk commented on app/assets/stylesheets/components/loader.css
> +  border-left-color: green;
а створити цей колір в конфігах тейлвінда не варік?

2023-12-24 11:06 UTC, mdotvasylenchuk commented on app/assets/stylesheets/components/loader.css
> +  border-left-color: green;
тим більше можна border-l-color-[green]

2023-12-24 11:07 UTC, mdotvasylenchuk commented on app/assets/stylesheets/components/loader.css
> +  border-left-color: green;
але краще в конфігах задати

2023-12-24 11:08 UTC, mdotvasylenchuk commented on app/javascript/controllers/loader_controller.js
> +  static targets = ["loader_mask"];
не тут, в верху контролера пишуться таргети вел'юси і тд

2023-12-24 11:08 UTC, mdotvasylenchuk commented on app/javascript/controllers/loader_controller.js
> +  static targets = ["loader_mask"];
і неймінг має буде в кемл кейсі

2023-12-24 11:09 UTC, mdotvasylenchuk commented on app/services/database_service.rb
> +  end
напиши тест, тут 5 хв роботи

2023-12-24 11:11 UTC, mdotvasylenchuk commented on app/services/database_service.rb
> +  end
в тебе всі методи клас методи, а як ще можна зробити окремий спейс, де всі методи будуть методами класу?

2023-12-24 12:09 UTC, DmytroStoliaruk commented on app/javascript/controllers/loader_controller.js
> +  static targets = ["loader_mask"];
поправив

2023-12-24 12:12 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +  end
поправив

2023-12-24 12:20 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +  end
можна зробити замість класа модуль.
Переробити в модуль?

2023-12-24 12:42 UTC, DmytroStoliaruk commented on app/assets/stylesheets/components/loader.css
> +  border-left-color: green;
border-l-color- пробував, не працює. пошук також на дав працюючого результату...

2023-12-24 12:58 UTC, mdotvasylenchuk commented on app/services/database_service.rb
> +  end
Ні, лиши клас, але тут більше робота з контекстом

2023-12-24 12:58 UTC, mdotvasylenchuk commented on app/services/database_service.rb
> +  end
https://dev.to/vitaliipaprotskyi/what-does-class-self-actually-do-in-ruby-2on1

2023-12-24 12:59 UTC, mdotvasylenchuk commented on app/services/database_service.rb
> +  end
Хелпану на цей раз

2023-12-24 13:24 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +  end
Дякую! переробив з class << self

2023-12-24 13:59 UTC, DmytroStoliaruk commented on app/assets/stylesheets/components/loader.css
> +  border-left-color: green;
змінив колір на кастомний колір tailwind для zerowaste   border-left-color: theme("colors.dark_green");

2023-12-26 08:12 UTC, loqimean requested changes

2023-12-26 08:12 UTC, loqimean commented on app/services/database_service.rb
> +      FileUtils.rm(backup_file)
а ти не пробав юзанути `mv`?

2023-12-26 08:12 UTC, loqimean commented on app/services/database_service.rb
> +      new_file_name = "#{timestamp}_#{File.basename(backup_file)}"
так у тебе для того є метод

2023-12-26 08:12 UTC, loqimean commented on app/services/database_service.rb
> +      ensure_directory_exists(BACKUP_DIR)
а що повертає цей метод?

2023-12-26 08:12 UTC, loqimean commented on app/services/database_service.rb
якась у тебе занадто абстрактна назва),  у тееб ж не просто якісь дії з БД відбуваються, а ти по-факту з `sandbox mode` щось робиш)

2023-12-26 08:12 UTC, loqimean commented on lib/tasks/db_task.rake
щодо назви таски те ж саме), у тебе не просто рестор і тд робиться, а рестор для сендбокса і тд)

2023-12-26 08:12 UTC, loqimean commented on lib/tasks/db_task.rake
> +    puts system(cmd) ? "Database dump created..." : "Error to create database dump!!!"
```suggestion
    puts system(cmd) ? "Database dump was created successfully" : "Error to create database dump!"
```

2023-12-26 08:12 UTC, loqimean commented on lib/tasks/db_task.rake
> +    puts system(cmd) ? "Database restored..." : "Error to restore database!!!"
з месиджами тут те ж саме

2023-12-27 08:11 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +  BACKUP_ARCHIVE_DIR  = Rails.root.join(BACKUP_DIR, "archive").freeze
поправив

2023-12-27 08:11 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +      prune_old_backups if Dir.entries(BACKUP_ARCHIVE_DIR).count > MAX_NUMBER_BACKUP
зробив

2023-12-27 08:12 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +      FileUtils.rm(backup_file)
використовую mv )

2023-12-27 08:12 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +      new_file_name = "#{timestamp}_#{File.basename(backup_file)}"
поправив

2023-12-27 08:12 UTC, DmytroStoliaruk commented on app/services/database_service.rb
> +      ensure_directory_exists(BACKUP_DIR)
змінив логіку. метод прибрав

2023-12-27 08:13 UTC, DmytroStoliaruk commented on app/services/database_service.rb
перейменував в DatabaseBackupService

2023-12-27 08:14 UTC, DmytroStoliaruk commented on lib/tasks/db_task.rake
також перейменував:
db:backup:create[filename]         # Create the database dump
db:backup:list                                # Show the existing database backups
db:backup:restore[filename]        # Restores the database dump

2023-12-27 08:15 UTC, DmytroStoliaruk commented on lib/tasks/db_task.rake
> +    puts system(cmd) ? "Database dump created..." : "Error to create database dump!!!"
уточнив

2023-12-27 08:16 UTC, DmytroStoliaruk commented on lib/tasks/db_task.rake
> +    puts system(cmd) ? "Database restored..." : "Error to restore database!!!"
поправив

2023-12-29 10:39 UTC, loqimean requested changes

2023-12-29 10:39 UTC, loqimean commented on config/initializers/flipper/flipper.rb
> +  require "./app/services/database_backup_service"
це щось взагалі мені не подобається, мало б автоматом підтягнути

2023-12-29 10:39 UTC, loqimean commented on spec/services/database_backup_spec.rb
> +        allow(DatabaseBackupService).to receive(:generate_backup_filename).and_return("generated_filename.dump")
от ти мені скахи, нашо ти застабив штуку, яку можна не стабити, бо вона нічого не міняє?))

2023-12-29 10:39 UTC, loqimean commented on spec/services/database_backup_spec.rb
> +        allow(DatabaseBackupService).to receive(:generate_backup_filename).and_return("generated_filename.dump")
і так у всх місцях

2023-12-29 10:39 UTC, loqimean commented on spec/services/database_backup_spec.rb
> +        allow(DatabaseBackupService).to receive(:generate_backup_filename).and_return("generated_filename.dump")
стаб ти маєш юзати, щоб не кликати якісь зовнішні сервіси, АПІ всякі та от наприклад створення файлів

2023-12-30 17:53 UTC, DmytroStoliaruk commented on spec/services/database_backup_spec.rb
> +        allow(DatabaseBackupService).to receive(:generate_backup_filename).and_return("generated_filename.dump")
прибрав зайве..

2023-12-30 17:53 UTC, DmytroStoliaruk commented on config/initializers/flipper/flipper.rb
> +  require "./app/services/database_backup_service"
залишив, оскільки інакше не працює

2024-01-09 18:43 UTC, merged