ZER-63 Move IN function usage from RangeField to Calculation
ita-social-projects/ZeroWaste pull request #61
Opened 2021-05-13 20:36 UTC by ochupa

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-05-13 20:39 UTC, PavloMS approved these changes

2021-05-14 09:57 UTC, maksymst requested changes

2021-05-14 09:57 UTC, maksymst commented on app/models/calculation_resolver.rb
> +  def self.generate_since_function(calculator)
What is the purpose of this method?

2021-05-14 09:57 UTC, maksymst commented on app/models/calculation_resolver.rb
> +  def self.generate_from_list_function(calculator)
same as above

2021-05-14 09:57 UTC, maksymst commented on app/models/calculation_resolver.rb
> +  def self.generate_calculator
do you really generate anything?

2021-05-14 13:34 UTC, maksymst requested changes

2021-05-14 13:34 UTC, maksymst commented on app/models/calculator_resolver.rb
> +
do you need this?

2021-05-14 15:16 UTC, ochupa commented on app/models/calculator_resolver.rb
> +
No, I don't :-) 
Deleted.
Thanks.

2021-05-16 09:48 UTC, maksymst approved these changes

2021-05-16 09:52 UTC, aboriiisova approved these changes

2021-05-16 09:54 UTC, merged