ZER-59 Add login page for Admin user
ita-social-projects/ZeroWaste pull request #62
Opened 2021-05-13 22:59 UTC by haliapats

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-05-14 08:00 UTC, maksymst requested changes
1. Leave only templates required for sign in
2. Use https://github.com/slim-template/slim for templates. It is already in the master branch

2021-05-18 06:29 UTC, maksymst requested changes

2021-05-18 06:29 UTC, maksymst commented on db/migrate/20210513165126_devise_create_admins.rb
> +      # t.datetime :locked_at
you have these features enabled in Admin model

2021-05-22 10:12 UTC, maksymst requested changes

2021-05-22 10:12 UTC, maksymst commented on app/controllers/admins/sessions_controller.rb
> +  skip_before_action :check_user, only: :destroy
Why do you need this?

2021-05-22 10:12 UTC, maksymst commented on app/views/admins/confirmations/new.html.slim
> +  | Resend confirmation instructions
All texts in templates must be localized

2021-05-25 11:43 UTC, maksymst approved these changes

2021-05-25 11:43 UTC, maksymst commented on app/controllers/admins/sessions_controller.rb
> +  end
https://stackoverflow.com/questions/31943125/how-to-correctly-use-guard-clause-in-ruby

2021-05-25 11:51 UTC, IvanShvets42 approved these changes

2021-05-25 12:27 UTC, merged