Enable Password Visibility During
ita-social-projects/ZeroWaste pull request #649
Opened 2023-12-07 17:53 UTC by Natali-Kotelnitska

dev
Ticket  #609 

## Code reviewers

- [ ] @loqimean 
- [x] @DmytroStoliaruk 

## Summary of issue

Add a new feature in the login page that allows the user to toggle the visibility of their password.

## Summary of change
1. Add an eye icon in the password field in the pages with password fields.
2. Add styles for eye-icon.
3. Add enable password visibility logic using Stimulus.

![Знімок екрана (251)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/9fa13bd5-fb93-4e15-87ba-8f67981172d5)
![Знімок екрана (250)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/d8563b6a-0946-4ad6-bbd4-90d302d8ece5)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-12-07 19:33 UTC, DmytroStoliaruk approved these changes

2023-12-19 18:16 UTC, loqimean requested changes

2023-12-19 18:16 UTC, loqimean commented on app/javascript/controllers/password_visibility_controller.js
> +    const passwordField = this.passwordTarget
а навіщо ця тавтологія?))

2023-12-19 18:16 UTC, loqimean commented on app/views/account/users/new.html.erb
> +        <%= f.input :password, input_html: { data: { 'password-visibility-target': 'password' } }, hint: t('.form.password_hint'), required: true %>
```suggestion
        <%= f.input :password, input_html: { data: { password_visibility_target: 'password' } }, hint: t('.form.password_hint'), required: true %>
```

2023-12-19 18:16 UTC, loqimean commented on app/views/account/users/new.html.erb
> +        <%= f.input :password_confirmation, input_html: { data: { 'password-visibility-target': 'password' } }, required: true %>
тут те ж саме в `data`

2023-12-19 18:16 UTC, loqimean commented on app/views/account/users/new.html.erb
> +        <%= f.input :password_confirmation, input_html: { data: { 'password-visibility-target': 'password' } }, required: true %>
і так скрізь

2023-12-19 19:06 UTC, Natali-Kotelnitska commented on app/views/account/users/new.html.erb
> +        <%= f.input :password, input_html: { data: { 'password-visibility-target': 'password' } }, hint: t('.form.password_hint'), required: true %>
без лапок вибиває синтаксичну помилку, а з лапками працює.

2023-12-19 19:15 UTC, Natali-Kotelnitska commented on app/javascript/controllers/password_visibility_controller.js
> +    const passwordField = this.passwordTarget
Removed.

2023-12-19 19:36 UTC, Natali-Kotelnitska commented on app/views/account/users/new.html.erb
> +        <%= f.input :password_confirmation, input_html: { data: { 'password-visibility-target': 'password' } }, required: true %>
Готово.

2023-12-20 09:59 UTC, loqimean approved these changes

2023-12-20 09:59 UTC, loqimean commented on app/assets/stylesheets/components/form.css
> +
```suggestion
```

2023-12-20 09:59 UTC, loqimean commented on app/javascript/controllers/password_visibility_controller.js
> +    const PASSWORD_INPUT = 'password';
```suggestion
    const TEXT_INPUT_TYPE = 'text';
    const PASSWORD_INPUT_TYPE = 'password';
```

2023-12-20 10:00 UTC, merged