The About us page has been redesigned
ita-social-projects/ZeroWaste pull request #666
Opened 2023-12-10 10:30 UTC by iambrozjak

dev
https://github.com/ita-social-projects/ZeroWaste/issues/663
https://github.com/ita-social-projects/ZeroWaste/issues/655

## Code reviewers

- [ ] @DmytroStoliaruk

- [ ] @loqimean 

## Summary of issue
The text of the page is not displayed in English. Styles do not match the overall style of the project.
## Summary of change
The About Us page has been redesigned. The text of the page is displayed in English
<img width="949" alt="fix page about" src="https://github.com/ita-social-projects/ZeroWaste/assets/129009813/e964bb3d-95c2-4341-b43a-9b068bfd1235">

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-12-10 10:36 UTC, DmytroStoliaruk approved these changes

2023-12-19 18:21 UTC, loqimean requested changes

2023-12-19 18:21 UTC, loqimean commented on config/routes.rb
> +    get "about-us", to: "home#about", as: "about"
де тести?)

2023-12-19 18:21 UTC, loqimean commented on app/views/home/about.html.erb
> +<body>
навіщо це все?))

2023-12-19 18:21 UTC, loqimean commented on app/assets/stylesheets/pages/main.scss
> +}
чому не теілвінд?))

2023-12-24 11:39 UTC, mdotvasylenchuk commented on app/views/sitemap/index.xml.builder
> +      xml.loc about_path
не гуд, знаєш як сайтмапа працює? Чому тут має бути юрл а не патч?

2023-12-24 12:13 UTC, iambrozjak commented on config/routes.rb
> +    get "about-us", to: "home#about", as: "about"
тести додала)

2023-12-24 12:13 UTC, iambrozjak commented on app/views/home/about.html.erb
> +<body>
виправила)

2023-12-24 12:14 UTC, iambrozjak commented on app/assets/stylesheets/pages/main.scss
> +}
вже тейлвінд)

2023-12-24 12:14 UTC, iambrozjak commented on app/views/sitemap/index.xml.builder
> +      xml.loc about_path
виправила)

2023-12-26 06:46 UTC, loqimean requested changes

2023-12-26 06:46 UTC, loqimean commented on app/views/home/about.html.erb
> +  <main>
а це ще навіщо? це ж не правильний html на виході буде

2023-12-26 06:46 UTC, loqimean commented on app/views/sitemap/index.html.slim
> +            = link_to t('.about_us'), about_url, class: "text-white"
```suggestion
            = link_to t('.about_us'), about_path, class: "text-white"
```

2024-01-05 10:46 UTC, iambrozjak commented on app/views/home/about.html.erb
> +  <main>
Done!

2024-01-16 18:48 UTC, loqimean requested changes

2024-01-16 18:48 UTC, loqimean commented on app/views/home/about.html.erb
> +  <%= image_tag "softserve_academy_logo.png", class: "logo-zerowaste" %>
вони мають бути лінками на сайти

2024-01-17 23:15 UTC, iambrozjak commented on app/views/home/about.html.erb
> +  <p><%= t('footer_about') %> <a href="https://zerowastelviv.org.ua/"> https://zerowastelviv.org.ua</a></p>
я видалила цей футер, щоб не було дублювання,тому що логотипи  переходять за посиланням

2024-01-17 23:17 UTC, iambrozjak commented on app/views/home/about.html.erb
> +<section>
додала, проте не знаю чи так правильно

2024-01-18 13:07 UTC, loqimean requested changes

2024-01-18 13:07 UTC, loqimean commented on app/views/home/about.html.erb
> +<section>
meta-tags

2024-01-18 13:07 UTC, loqimean commented on app/views/home/about.html.erb
> +<section>
юзай цей гем

2024-01-29 18:18 UTC, loqimean approved these changes

2024-01-29 18:18 UTC, loqimean commented on app/views/home/about.html.erb
> +})%>
```suggestion
})%>

```

2024-01-31 11:48 UTC, merged