add a dropdown
ita-social-projects/ZeroWaste pull request #671
Opened 2023-12-11 23:33 UTC by iryna-borniak

dev
## ZeroWaste project

* [Project ticket #592](https://github.com/ita-social-projects/ZeroWaste/issues/592)

## Code reviewers

- [ ] @loqimean

### Second Level Review

- [ ] @github_username

## Summary of issue

A spinner is used to select the priority level in the 'Пріоритет' input field.

According to [User story #427](https://github.com/ita-social-projects/ZeroWaste/issues/427)/ Criteria 3:
the priority range selection should provide clear options, such as a dropdown or radio buttons, to choose the desired range.

## Summary of change

1. Changed the input with type "number" to dropdown with a range between 0 and 10 inclusive.
2. Deleted Bootstrap class "form-select" so that Tailwind styles got applied to the select.

![Screenshot 2023-12-12 002652](https://github.com/ita-social-projects/ZeroWaste/assets/25872733/71d6d910-3d34-4db8-8368-5aceab9d4173)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-12-12 12:24 UTC, obniavko approved these changes

2023-12-19 18:25 UTC, loqimean requested changes

2023-12-19 18:25 UTC, loqimean commented on app/models/category.rb
> +  PRIORITY_RANGE = 0..10
константи в самому верху пишемо

2023-12-19 18:25 UTC, loqimean commented on app/views/account/categories/edit.html.slim
> +        = f.input :priority, collection: Category::PRIORITY_RANGE, selected: @category.priority, wrapper: :custom_vertical_select
не треба селектед

2023-12-19 18:25 UTC, loqimean commented on app/views/account/categories/new.html.slim
> +        = f.input :priority, collection: Category::PRIORITY_RANGE, selected: @category.priority, wrapper: :custom_vertical_select
те ж саме

2023-12-26 06:47 UTC, loqimean approved these changes

2024-01-16 13:31 UTC, merged