Fix-uk-locale-pluralize-in-old-calculator
ita-social-projects/ZeroWaste pull request #672
Opened 2023-12-12 16:57 UTC by fh0enix

dev ticket
https://github.com/ita-social-projects/ZeroWaste/issues/418

## Code reviewers

- [x] @loqimean

### Second Level Review

- [x] @

## Summary of issue

Title: Fix Pluralization in Diaper Calculator Results

Description:
This pull request addresses an issue related to pluralization in the Diaper Calculator results. Previously, the pluralized strings for the number of used and to-be-used diapers were not correctly formatted, leading to inaccuracies in the displayed values. The problem has been resolved by fixing the pluralization logic and updating the corresponding tests to ensure accurate localization.

Changes:

Corrected pluralization logic for the count of used and to-be-used diapers.
Updated tests to validate the accuracy of pluralized strings in the Diaper Calculator results.
Testing:

Added new tests to verify the correct pluralization of diaper counts.
Ran existing test suite to ensure overall functionality.

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-12-12 17:51 UTC, obniavko approved these changes

2023-12-13 07:38 UTC, obniavko approved these changes

2023-12-19 18:27 UTC, loqimean requested changes

2023-12-19 18:27 UTC, loqimean commented on app/javascript/controllers/results_controller.js
> +    this.moneySpentTarget.innerHTML = Math.ceil(result.money_spent);;
```suggestion
    this.moneySpentTarget.innerHTML = Math.ceil(result.money_spent);
```

2023-12-19 18:27 UTC, loqimean commented on app/views/calculators/old_calculator.html.slim
> +.container.calculation-results.result[data-controller='results']
а пробіл точно не треба?

2023-12-19 18:27 UTC, loqimean commented on spec/requests/diaper_calculators_spec.rb
> +        expected_to_be_used_diapers = I18n.t("calculators.old_calculator.will_buy_diapers", count: values[:to_be_used_diapers_amount])
сподіваюся я такого більше не побачу, для того є така штука, як `let`

2023-12-20 17:16 UTC, fh0enix commented on spec/requests/diaper_calculators_spec.rb
> +        expected_to_be_used_diapers = I18n.t("calculators.old_calculator.will_buy_diapers", count: values[:to_be_used_diapers_amount])
solved

2023-12-20 17:25 UTC, fh0enix commented on app/views/calculators/old_calculator.html.slim
> +.container.calculation-results.result[data-controller='results']
ou sorry. solved

2023-12-20 17:26 UTC, fh0enix commented on app/javascript/controllers/results_controller.js
> +    this.moneySpentTarget.innerHTML = Math.ceil(result.money_spent);;
oops... solved

2023-12-26 06:49 UTC, loqimean requested changes

2023-12-26 06:49 UTC, loqimean commented on spec/requests/diaper_calculators_spec.rb
> +        post api_v1_diaper_calculators_path, params: { childs_years: 1, childs_months: 0 }
це в before

2023-12-26 06:49 UTC, loqimean commented on spec/requests/diaper_calculators_spec.rb
> +        response_body = JSON.parse(response.body)["result"]
а це в let

2023-12-26 13:20 UTC, fh0enix commented on spec/requests/diaper_calculators_spec.rb
> +        response_body = JSON.parse(response.body)["result"]
solved

2023-12-26 13:20 UTC, fh0enix commented on spec/requests/diaper_calculators_spec.rb
> +        post api_v1_diaper_calculators_path, params: { childs_years: 1, childs_months: 0 }
solved

2024-01-16 19:31 UTC, merged