660 error messages when singup with empty fields
ita-social-projects/ZeroWaste pull request #689
Opened 2023-12-16 08:18 UTC by dafeys

dev
## ZeroWaste project
 [Sign Up Page] Incorrect error message when creating new user with empty fields #660

## Code reviewers

- [ ] @loqimean

### Second Level Review

- [ ] @DmytroStoliaruk 

## Summary of issue

Incorrect number of errors was displayed in sign up form when the field was empty

## Summary of change
- Displaying only one error if the form field is empty
- fixed translation of error messages in Ukrainian

![blank-en](https://github.com/ita-social-projects/ZeroWaste/assets/36037839/be9e53c4-4499-4361-bb05-0e08698ae5e7)

![blank-ua](https://github.com/ita-social-projects/ZeroWaste/assets/36037839/0bad37cb-3c5a-49a3-a9c7-60b9476979a7)

2023-12-16 08:29 UTC, DmytroStoliaruk approved these changes

2023-12-19 19:00 UTC, loqimean commented on app/controllers/users/registrations_controller.rb
> +  end
а навіщо це все?

2023-12-20 23:33 UTC, dafeys commented on app/models/user.rb
> +            on: [:create, :update],
Не можу зрозуміти, чи дійсно тут потрібні   on: [:create, :update] ?

2023-12-22 08:48 UTC, loqimean requested changes

2023-12-22 08:48 UTC, loqimean commented on app/models/user.rb
> +            on: [:create, :update],
а що це за валідація, яка нічого не валідує?)

2023-12-22 08:48 UTC, loqimean commented on app/models/user.rb
> +            on: [:create, :update],
а, бачу, ну та додай цей алов_бленк в кінці валідацій

2023-12-22 08:48 UTC, loqimean commented on app/models/user.rb
> +            on: [:create, :update],
не треба on

2023-12-24 09:11 UTC, dafeys commented on app/models/user.rb
> +            on: [:create, :update],
Забрав on, перемістив всі allow_blank: true в кінець

2023-12-24 11:41 UTC, mdotvasylenchuk commented on app/models/user.rb
> +  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_blank: true
а чому тут розбив валідацію?

2023-12-24 11:41 UTC, mdotvasylenchuk commented on app/models/user.rb
> +            confirmation: true,
а тут наприклад ні?

2023-12-24 12:18 UTC, dafeys commented on app/models/user.rb
> +  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_blank: true
Щоб юзеру не показувалися одночасно всі помилки, коли поле пусте

2023-12-24 12:20 UTC, dafeys commented on app/models/user.rb
> +            confirmation: true,
Бо confirmation: true потрібен =) а решта логіки по пасворду така сама як і для email

2023-12-26 06:50 UTC, loqimean approved these changes

2023-12-26 07:13 UTC, merged