686 admin burger menu
ita-social-projects/ZeroWaste pull request #691
Opened 2023-12-17 12:08 UTC by DmytroStoliaruk

dev
## Zerowaste

* [#686 ]

## Code reviewers

- [ ] @loqimean 

### Second Level Review

- [ ] @iryna-borniak 

## Summary of issue

Refactor admin menu from Bootstrap to Tailwind styles
Fix the unworking burger menu

## Summary of change

1. Refactored admin menu
2. Add burger menu, add Stimulus controller for it

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

Uploading Screen Recording 2023-12-17 at 14.05.51.mov…

2023-12-17 17:10 UTC, iryna-borniak approved these changes

2023-12-20 15:50 UTC, DmytroStoliaruk commented on app/views/layouts/_account_navbar.html.erb
> +          </svg>
зробив

2023-12-20 15:50 UTC, DmytroStoliaruk commented on app/javascript/controllers/burger_controller.js
> +  crossPath = "M3 3L21 21M3 21L21 3";
ок

2023-12-20 15:56 UTC, loqimean requested changes

2023-12-20 15:56 UTC, loqimean commented on app/javascript/controllers/burger_controller.js
> +    document.getElementById('navbarNav').classList.toggle('hidden');
таргети)

2023-12-20 17:58 UTC, DmytroStoliaruk commented on app/javascript/controllers/burger_controller.js
> +    document.getElementById('navbarNav').classList.toggle('hidden');
виправив

2023-12-21 10:44 UTC, loqimean approved these changes

2023-12-21 11:07 UTC, merged