Change-Flash-messages-and-Toastr-messages-to-Toastify-JS-notifications
ita-social-projects/ZeroWaste pull request #692
Opened 2023-12-18 19:10 UTC by fh0enix

dev ticket
https://github.com/ita-social-projects/ZeroWaste/issues/562

## Code reviewers

- [x] @loqimean

### Second Level Review

- [x] @kisiohlova

Issue:
Flashes persist after clicking [x]

Steps to Reproduce:
Perform any actions that lead to flash messages, e.g., log in.

Actual Result:
Flashes do not disappear after clicking [x].

Expected Result:
Notifications should disappear after clicking [x].

Clarification from @loqimean:
[x] should be at the end of the block with the message.

Solution:
After consulting with the expert @loqimean, it was decided to transition from flash messages to Toastify JS notifications for a more user-friendly experience. The updated solution involves integrating Toastify JS and replacing the existing logic for displaying flash messages with the new toast notifications. This change enhances the user interface by providing dynamic and visually appealing notifications that automatically disappear after a set duration.

This pull request addresses the reported issue and implements the recommended solution, creating a more efficient and modern notification system.

Changes Made:

Integrated Toastify JS library for toast notifications.
Replaced the existing logic for displaying flash messages with Toastify JS notifications.
Updated Stimulus controller to handle Turbo Streams and utilize Toastify for error notifications.
Additional Notes:

Toastify settings, such as duration and styling, have been configured to enhance the user experience.
The solution aligns with best practices and offers a more intuitive notification mechanism.

This pull request is in accordance with the discussion in previous correspondence. Please review and provide feedback.

## Testing approach

No new tests were added in this pull request as the logic for notifications remains unchanged, and the existing test suite adequately covers the functionality. The transition from flash messages to Toastify JS notifications focused on the user interface layer, and the underlying application logic, including error handling, remains consistent.

The Toastify JS implementation was seamlessly integrated without altering the existing application logic. Therefore, the previously written tests for flash messages remain relevant and effective. These tests include scenarios such as displaying messages on successful actions and handling error cases.

The decision not to introduce new tests aligns with the principle of maintaining a stable codebase while enhancing the user experience. The existing test coverage ensures that the application behaves as expected, and the pull request focuses on the visual representation of notifications.

Reviewers are encouraged to validate the existing test suite to confirm that the application's core functionality remains robust despite the cosmetic changes to the notification system.

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-12-19 19:11 UTC, loqimean requested changes

2023-12-19 19:11 UTC, loqimean commented on app/javascript/controllers/input_child_info_controller.js
> +      showToast(result.error)
а якого типу буде цей тостер?)

2023-12-19 19:11 UTC, loqimean commented on app/javascript/helpers/toast-helper.js
> +      background: background == "notice" ? "#8FBA3B" : "#DC3545",
case switch на різні типи, як от ерора, нотіс та ворнінг

2023-12-19 19:11 UTC, loqimean commented on app/javascript/turbo_streams/toast.js
> +import { showToast } from "../helpers/toast-helper";
не гуд взагалі, helpers папка має бути додана в імпортмапи

2023-12-19 19:11 UTC, loqimean commented on app/javascript/controllers/application.js
> +import "../turbo_streams/toast"
не гуд теж, тре задати це в імпортмапи

2023-12-19 19:11 UTC, loqimean commented on app/helpers/turbo_stream_actions_helper.rb
> +Turbo::Streams::TagBuilder.prepend(TurboStreamActionsHelper)
а чому це в хелпері? і для чого це?

2023-12-19 20:07 UTC, fh0enix commented on app/javascript/controllers/application.js
> +import "../turbo_streams/toast"
solved

2023-12-19 20:09 UTC, fh0enix commented on app/javascript/controllers/input_child_info_controller.js
> +      showToast(result.error)
solved

2023-12-19 20:28 UTC, fh0enix commented on app/javascript/helpers/toast-helper.js
> +      background: background == "notice" ? "#8FBA3B" : "#DC3545",
solved

2023-12-20 08:09 UTC, fh0enix commented on app/helpers/turbo_stream_actions_helper.rb
> +Turbo::Streams::TagBuilder.prepend(TurboStreamActionsHelper)
Turbo::Streams::TagBuilder.prepend(TurboStreamActionsHelper): я викликаю prepend на Turbo::Streams::TagBuilder, додаючи методи з TurboStreamActionsHelper до цього класу або модулю. Таким чином, всі інстанції Turbo::Streams::TagBuilder тепер будуть мати доступ до методів, визначених у TurboStreamActionsHelper.

Це дозволить використовувати метод toast в контексті Turbo Streams

2023-12-21 15:16 UTC, mdotvasylenchuk commented on app/views/layouts/application.html.erb
> +    <%= favicon_link_tag(url_for(SiteSetting.current.favicon)) %>
тут n+1, зроби щоб сайт сетінг карент раз витягався і всюди юзався лише один об'єкт

2023-12-22 10:13 UTC, mdotvasylenchuk approved these changes

2023-12-22 10:23 UTC, kisiohlova approved these changes

2023-12-26 06:56 UTC, loqimean requested changes

2023-12-26 06:56 UTC, loqimean commented on app/javascript/helpers/toast-helper.js
переназви файл через underscore, так зручніше потім назви файлів писати

2023-12-26 06:56 UTC, loqimean commented on app/javascript/turbo_streams/toast.js
> +window.Turbo.StreamActions.toast = function() {
стрілочну ф-цію юзани

2023-12-26 06:56 UTC, loqimean commented on app/views/layouts/account.html.erb
> +  <%= stylesheet_link_tag "application", "https://ga.jspm.io/npm:toastify-js@1.12.0/src/toastify.css", "data-turbo-track": "reload" %>
ну бляха, а імпортмапи для чого?? також чому в `account` лейауті лежить `application` стайлшит??

2023-12-26 06:56 UTC, loqimean commented on app/views/layouts/account.html.erb
> +  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
і тут знову лежить, вже дублювання

2023-12-26 06:56 UTC, loqimean commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "application", "https://ga.jspm.io/npm:toastify-js@1.12.0/src/toastify.css", "data-turbo-track": "reload" %>
знову імпортмапи

2023-12-26 06:56 UTC, loqimean commented on config/importmap.rb
> +pin "toastify-js", to: "https://ga.jspm.io/npm:toastify-js@1.12.0/src/toastify.js", preload: true
ну от тут додав, а навіщо ще в лейауті писати??

2023-12-26 09:35 UTC, fh0enix commented on app/javascript/helpers/toast-helper.js
solved

2023-12-26 09:45 UTC, fh0enix commented on app/javascript/turbo_streams/toast.js
> +window.Turbo.StreamActions.toast = function() {
![image](https://github.com/ita-social-projects/ZeroWaste/assets/13628239/79b389cb-93c0-4ea8-b34e-b92aa6a183cc)
https://www.ducktypelabs.com/the-anatomy-of-a-turbo-stream/

Це не працює для кастомних екшенів

2023-12-26 11:40 UTC, fh0enix commented on config/importmap.rb
> +pin "toastify-js", to: "https://ga.jspm.io/npm:toastify-js@1.12.0/src/toastify.js", preload: true
solved

2023-12-26 11:41 UTC, fh0enix commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag "application", "https://ga.jspm.io/npm:toastify-js@1.12.0/src/toastify.css", "data-turbo-track": "reload" %>
solved

2023-12-26 11:41 UTC, fh0enix commented on app/views/layouts/account.html.erb
> +  <%= stylesheet_link_tag "application", "https://ga.jspm.io/npm:toastify-js@1.12.0/src/toastify.css", "data-turbo-track": "reload" %>
solved

2023-12-26 11:42 UTC, fh0enix commented on app/views/layouts/account.html.erb
> +  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
solved

2023-12-26 11:53 UTC, fh0enix commented on app/views/layouts/account.html.erb
> +  <%= stylesheet_link_tag "application", "https://ga.jspm.io/npm:toastify-js@1.12.0/src/toastify.css", "data-turbo-track": "reload" %>
![image](https://github.com/ita-social-projects/ZeroWaste/assets/13628239/77cb9dda-cf3d-429f-a059-0c2a90fbf982)
в account лейауті лежить application стайлшит , без нього все ламається.

2024-01-12 17:18 UTC, loqimean requested changes

2024-01-12 17:18 UTC, loqimean commented on app/assets/stylesheets/components/toastify.scss
> +  z-index: 2147483647;
не гуд, там є максимальне значення, врахуй це та виправ

2024-01-12 17:18 UTC, loqimean commented on app/javascript/helpers/toast_helper.js
> +}
пропиши зверху функції та екпортуй по назві тут, бо кожен раз писати експорт така собі забавка, що, якщо мені тре буде 20 методів, або функцій тут прописати?

2024-01-12 17:18 UTC, loqimean commented on app/javascript/turbo_streams/toast.js
> +window.Turbo.StreamActions.toast = function() {
без питань)

2024-01-12 17:18 UTC, loqimean commented on app/javascript/turbo_streams/toast.js
> +  const messageType = this.getAttribute("background")
я щось не розумію, ти просиш бекграунд, а пишеш його в месидж тайп? щось не гуд

2024-01-12 17:37 UTC, fh0enix commented on app/assets/stylesheets/components/toastify.scss
> +  z-index: 2147483647;
це і є максимальне значення. тобто ми показуємо це поверх всіх існуючих елементів. на що виправити?

Conclusion Maximum z-index value is 2,147,483,647 and more than this convert to 2,147,483,647

2024-01-12 18:22 UTC, fh0enix commented on app/javascript/turbo_streams/toast.js
> +  const messageType = this.getAttribute("background")
solved

2024-01-12 18:40 UTC, fh0enix commented on app/javascript/helpers/toast_helper.js
> +}
solved

2024-01-16 19:32 UTC, merged