fix delete button on users page
ita-social-projects/ZeroWaste pull request #693
Opened 2023-12-20 14:59 UTC by iryna-borniak

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-12-22 10:13 UTC, obniavko approved these changes

2023-12-24 11:44 UTC, mdotvasylenchuk commented on config/environments/test.rb
> +  config.action_dispatch.show_exceptions = :none
чому тут none?

2023-12-24 11:45 UTC, mdotvasylenchuk commented on app/views/account/users/index.html.erb
> +<div class="container home">
додай тут - title

2023-12-24 11:45 UTC, mdotvasylenchuk commented on app/views/account/users/index.html.erb
> +                            onclick: "alert('Are you sure?')", method: :patch) %>
розпиши трохи детальніше повідомлення

2023-12-24 11:47 UTC, mdotvasylenchuk commented on app/views/account/users/index.html.erb
> +                  <i class="fa fa-trash mx-2"></i>
тим більше тут юзається і18н а вище ні, так розумію адмінка теж мультимовна, тому виправ кнопку вище

2023-12-24 15:58 UTC, iryna-borniak commented on app/views/account/users/index.html.erb
> +                            onclick: "alert('Are you sure?')", method: :patch) %>
Ця логіка повністю перероблена і закривається ПР * [#702](https://github.com/ita-social-projects/ZeroWaste/pull/702/files)

2023-12-24 16:30 UTC, iryna-borniak commented on app/views/account/users/index.html.erb
> +<div class="container home">
В ПР * [#702](https://github.com/ita-social-projects/ZeroWaste/pull/702/files) застосовується caption (стилізований, як заголовок)

2023-12-24 16:46 UTC, iryna-borniak commented on config/environments/test.rb
> +  config.action_dispatch.show_exceptions = :none
![Screenshot 2023-12-24 183950](https://github.com/ita-social-projects/ZeroWaste/assets/25872733/7fe638d0-af04-41c0-8249-826cdc80e149)

2023-12-26 06:59 UTC, loqimean requested changes

2023-12-26 06:59 UTC, loqimean commented on app/views/account/users/index.html.erb
> +                            onclick: "alert('Are you sure?')", method: :patch) %>
більше того, логіка заблокування в хелпері має бути, а онклік замінити ПОТРІБНО  на турбо конфірм

2023-12-26 06:59 UTC, loqimean commented on app/views/account/users/index.html.erb
> +                            onclick: "alert('Are you sure?')", method: :patch) %>
локалізація теж тре

2023-12-26 21:47 UTC, iryna-borniak commented on app/views/account/users/index.html.erb
> +                            onclick: "alert('Are you sure?')", method: :patch) %>
Done

2023-12-26 23:57 UTC, iryna-borniak commented on app/views/account/users/index.html.erb
> +                  <i class="fa fa-trash mx-2"></i>
Done

2024-01-16 18:57 UTC, loqimean requested changes

2024-01-21 22:30 UTC, iryna-borniak commented on app/helpers/account/users_helper.rb
done

2024-01-21 22:38 UTC, iryna-borniak commented on app/views/account/users/index.html.erb
> +<div class="container home">
done

2024-02-19 22:47 UTC, merged