Feature/block user
ita-social-projects/ZeroWaste pull request #702
Opened 2023-12-22 00:55 UTC by Natali-Kotelnitska

dev
Ticket #653 

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue
 It is not possible to block the user when clicking on the "Ban" button in admine dashboard.

## Summary of change

1. Refactor functionality of the 'ban' button.
2. Convert account/users/index view from slim into erb format.
3. Add styles using Tailwind.
4. Add translations for locales.

![Знімок екрана (391)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/95866e7f-4ebb-4571-b488-ad060c132e1e)
![Знімок екрана (393)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/6b40e9e6-90c0-4cc0-9eff-0d13f473d01e)
![Знімок екрана (394)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/880c125d-2354-40af-b558-0cd10f04aa7c)
![Знімок екрана (395)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/33488cd1-4d73-4cff-bfaf-b58442777ed6)

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-12-24 11:49 UTC, dafeys approved these changes

2023-12-24 12:02 UTC, mdotvasylenchuk commented on app/views/account/users/index.html.erb
> +                <%= button_to update_block_status_account_user_path(id: user.id), method: :put do %>
а чому просто не передаси update_block_status_account_user_path(user)?

2023-12-24 12:02 UTC, mdotvasylenchuk commented on app/views/account/users/index.html.erb
> +                <%= button_to update_block_status_account_user_path(id: user.id), method: :put do %>
юрл хелпери дістають id з юзера

2023-12-24 12:02 UTC, mdotvasylenchuk commented on app/views/account/users/index.html.erb
> +            <th><%= t '.table.delete' %></th>
краще душки юзай

2023-12-24 12:03 UTC, mdotvasylenchuk commented on config/routes.rb
> +          put "update_block_status", to: "users#update_block_status", as: :update_block_status
почитай різницю між put і patch, і визначи який метод тут має бути залежно від твого функціоналу

2023-12-24 13:08 UTC, Natali-Kotelnitska commented on app/views/account/users/index.html.erb
> +                <%= button_to update_block_status_account_user_path(id: user.id), method: :put do %>
Виправила на user.

2023-12-24 13:09 UTC, Natali-Kotelnitska commented on app/views/account/users/index.html.erb
> +            <th><%= t '.table.delete' %></th>
Done.

2023-12-24 13:09 UTC, Natali-Kotelnitska commented on config/routes.rb
> +          put "update_block_status", to: "users#update_block_status", as: :update_block_status
Так, переплутала. Виправила. Дякую :)

2023-12-26 07:08 UTC, loqimean requested changes

2023-12-26 07:08 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      redirect_to account_users_path
щось тут не гуд)

2023-12-26 07:08 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      redirect_to account_users_path
і у тебе утт багато повторюється, флеш і редірект можна обʼєднати і винести з кондішенів

2023-12-26 07:08 UTC, loqimean commented on app/views/account/users/index.html.erb
> +    <h1 class="text-body inline-block"><%= t '.main_header' %></h1>
```suggestion
    <h1 class="text-body inline-block"><%= t('.main_header') %></h1>
```

2023-12-26 07:08 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +        sign_in admin_user
для того є контексти

2023-12-26 07:08 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +        expect(admin_user.reload.blocked).to be_falsey
тут блок з релоадом всередині напиши

2023-12-26 07:08 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +        user.update(blocked: true)
трейт

2023-12-26 07:08 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +        expect(user.blocked).to be_falsey
блок

2023-12-26 07:08 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +        expect(flash[:alert]).to eq(I18n.t("notifications.status_update_alert"))
і тут все те ж

2023-12-26 07:08 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +        allow_any_instance_of(User).to receive(:update).and_return(false)
тут біфор

2024-03-05 09:30 UTC, closed without merging