Fix error when clicking on table header
ita-social-projects/ZeroWaste pull request #706
Opened 2023-12-28 10:38 UTC by obniavko

dev
## ZeroWaste project

* [Project ticket #705](https://github.com/ita-social-projects/ZeroWaste/issues/705)

## Code reviewers

- [ ] @kisiohlova 
- [ ] @loqimean 

## Summary of issue

An error occurs when clicking on table header on [Users](https://zero-waste-staging.onrender.com/en/account/users)/[Products](https://zero-waste-staging.onrender.com/en/account/products)/[Categories](https://zero-waste-staging.onrender.com/en/account/categories) pages.

## Summary of change

1. Fixed error.
![sorted](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/88148e95-6e96-47da-aa86-b216943ca91b)
3. Added ability to sort items for [Messages](https://zero-waste-staging.onrender.com/en/account/messages) page.
4. Added ability to sort items for [Calculators](https://zero-waste-staging.onrender.com/en/calculators) page.
![calculators](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/5d07a545-0792-47a1-9f47-1df739fcb2ed)

## CHECK LIST
- [x]  СI passed
- [x]  Сode coverage >=95%
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [x]  I've checked new feature as logged in and logged out user if needed
- [x]  PR meets all conventions

2024-01-16 19:00 UTC, loqimean requested changes

2024-01-16 19:00 UTC, loqimean commented on app/models/category.rb
> +  def self.ransackable_attributes(auth_object = nil)
бачу тут не каверид строчки)

2024-01-16 19:00 UTC, loqimean commented on app/models/message.rb
> +  def self.ransackable_attributes(auth_object = nil)
те ж саме

2024-01-16 19:00 UTC, loqimean commented on app/models/product.rb
> +  def self.ransackable_attributes(auth_object = nil)
каверидж просів

2024-01-16 19:00 UTC, loqimean commented on app/models/user.rb
> +  def self.ransackable_attributes(auth_object = nil)
теж просів

2024-01-16 19:00 UTC, loqimean commented on spec/requests/account/messages_spec.rb
> +      get account_message_path(message)
напиши пліз тести на всі сторінки, які мали ерори

2024-01-17 16:16 UTC, obniavko commented on app/models/category.rb
> +  def self.ransackable_attributes(auth_object = nil)
Fixed

2024-01-17 16:16 UTC, obniavko commented on app/models/message.rb
> +  def self.ransackable_attributes(auth_object = nil)
Fixed

2024-01-17 16:16 UTC, obniavko commented on app/models/product.rb
> +  def self.ransackable_attributes(auth_object = nil)
Fixed

2024-01-17 16:17 UTC, obniavko commented on app/models/user.rb
> +  def self.ransackable_attributes(auth_object = nil)
Fixed

2024-01-17 16:17 UTC, obniavko commented on spec/requests/account/messages_spec.rb
> +      get account_message_path(message)
Done

2024-01-18 13:11 UTC, loqimean requested changes

2024-01-18 13:11 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +      get account_users_path
```suggestion
      get account_users_path

```

2024-01-18 13:11 UTC, loqimean commented on spec/requests/account/users_spec.rb
> +      expect(User.ransackable_attributes).to eq(["created_at", "id", "blocked", "country", "email", "first_name", "last_name", "updated_at"])
що це за тест взагалі такий?)

2024-01-18 13:11 UTC, loqimean commented on spec/requests/categories_spec.rb
> +      expect(Category.ransackable_attributes).to eq(["created_at", "id", "name", "priority", "updated_at"])
давай міняй

2024-01-18 13:11 UTC, loqimean commented on spec/requests/categories_spec.rb
> +      expect(Category.ransackable_attributes).to eq(["created_at", "id", "name", "priority", "updated_at"])
я казав ітератором пройтися і зробити запити з цими параметрами)

2024-01-25 15:05 UTC, obniavko commented on spec/requests/categories_spec.rb
> +      expect(Category.ransackable_attributes).to eq(["created_at", "id", "name", "priority", "updated_at"])
Fixed

2024-02-13 21:27 UTC, loqimean approved these changes

2024-02-13 21:27 UTC, merged