Add test for reset password page
ita-social-projects/ZeroWaste pull request #74
Opened 2021-08-13 18:11 UTC by halyna-m

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-08-13 20:56 UTC, olenochka123 reviewed
everything's good)

2021-08-13 23:34 UTC, andriibureviy approved these changes
Everything is fine

2021-08-14 07:58 UTC, olenochka123 approved these changes

2021-08-14 16:18 UTC, maksymst requested changes
There is an issue with test describing. 
Rspec has several methods that can build a kind of documentation based on tests.

```ruby
describe '#some_method'
# OR
describe SomeClass
# OR
describe 'Some Page'
```
`context` and `it` together build the sentence
```ruby
context 'when user clicks button' do
  it 'redirects to home page' { ... }
end

# OR

context `when parameter is passed` do
  context 'when parameter is string' do
    It 'returns nil' { ... }
  end
end
```

Try to fix your tests according to these rules

2021-08-14 16:18 UTC, maksymst commented on spec/features/reset_password_spec.rb
> +end
Add new line at EOF

2021-08-14 16:18 UTC, maksymst commented on spec/features/reset_password_spec.rb
> +    end
1. the text in `it` is confusing
2. user visits password reset page, clicks link `Sign Up` and sees another `Sign Up` link. This test is not really verifying anything. Let's try to improve this scenario

2021-08-14 16:18 UTC, maksymst commented on spec/features/reset_password_spec.rb
> +      expect(page).to have_selector("a[href='/users/sign_in']")
See coment below

2021-08-14 16:18 UTC, maksymst commented on spec/features/reset_password_spec.rb
> +      expect(page).to have_selector("a[href='/users/sign_in']")
See comment below

2021-08-16 08:35 UTC, andriibureviy approved these changes

2021-08-16 09:00 UTC, olenochka123 approved these changes

2021-08-16 09:03 UTC, andriibureviy approved these changes

2021-08-16 10:06 UTC, andriibureviy approved these changes

2021-08-16 12:35 UTC, olenochka123 approved these changes

2021-08-16 14:14 UTC, maksymst requested changes

2021-08-16 14:14 UTC, maksymst commented on spec/features/reset_password_spec.rb
> +describe 'Log In', js: true do
Leave the test but remove `describe`

2021-08-16 14:14 UTC, maksymst commented on spec/features/reset_password_spec.rb
> +describe 'Sign Up', js: true do
Leave the test but remove `describe`

2021-08-16 14:14 UTC, maksymst commented on spec/features/reset_password_spec.rb
> +  context 'when user clicks button Sign up' do
```suggestion
  context 'when user clicks Sign up link' do
```

2021-08-16 14:14 UTC, maksymst commented on spec/features/reset_password_spec.rb
> +  context 'when user clicks button Log in' do
```suggestion
  context 'when user clicks Log in link' do
```

2021-08-17 07:29 UTC, andriibureviy approved these changes

2021-08-17 09:07 UTC, olenochka123 approved these changes

2021-08-17 09:09 UTC, maksymst approved these changes

2021-08-17 09:28 UTC, merged