New Diaper Calculator rebuild
ita-social-projects/ZeroWaste pull request #765
Opened 2024-02-09 08:35 UTC by dafeys

dev

## ZeroWaste project
- #556 
- #755 

## Code reviewers

- [@loqimean 

### Second Level Review

- @github_username

https://github.com/ita-social-projects/ZeroWaste/assets/36037839/4ae9cb59-a7e8-4446-b9d5-5a053a4f1073

## Summary of issue
The new calculator did not work properly and did not recalculate the price when changing the category

## Summary of change
- created a new model to store periods of a child's life, the diaper consumption per day, and the price per unit that will belong to one of the categories with validations
- rebuild calculations based on new possible categories
- number of categories and periods can be arbitrary
- after the category is filled with periods up to 30 months, it becomes available in the calculator
- сreate a new section in the site settings for adding and editing periods
- TurboStream is used to update settings, so settings change dynamically without refreshing the page
- fixes in styling
- cover the functionality with tests

2024-02-13 09:38 UTC, DmytroStoliaruk approved these changes

2024-02-13 22:00 UTC, loqimean commented on config/routes.rb
> +          get :available_categories
скоріше `new_period`, чи не так?

2024-02-13 22:01 UTC, loqimean commented on db/migrate/20240122225503_create_diapers_periods.rb
> +      t.decimal :price, precision: 8, scale: 2
а чому тут нема валідації на рівні БД?

2024-02-13 22:01 UTC, loqimean commented on db/migrate/20240206152415_remove_defaults_from_diapers_periods.rb
> +  end
наче ж чейндж нулл мав мати ролбек, тож мало би гуд працювати зі звичайним `def change`

2024-02-13 22:02 UTC, loqimean commented on db/migrate/20240207143101_add_preferable_to_categories.rb
> +    add_column :categories, :preferable, :boolean, default: false
а де `null: false`?)

2024-02-13 22:03 UTC, loqimean commented on spec/factories/categories.rb
> +    end
пропиши через асоціацію, не тре тут хук

2024-02-13 22:03 UTC, loqimean commented on spec/factories/diapers_periods.rb
> +    end
а це навіщо? думаю не тре

2024-02-13 22:04 UTC, loqimean commented on spec/requests/account/diapers_periods_spec.rb
> +      expect(response).to render_template(layout: false)
не тре цих перевірок двох

2024-02-13 22:05 UTC, loqimean commented on spec/requests/account/diapers_periods_spec.rb
> +      allow(Category).to receive(:find).and_return(category)
а так робити не гуд), давай забирай

2024-02-13 22:05 UTC, loqimean commented on app/views/account/diapers_periods/partials/index/_delete_button.erb
> +<% if diapers_period == @diapers_periods.last %>
по-перше в паршалах ми не юзаємо інстанс змінні, а по-друге навіщо утт перевірка на ласт? це щось явно не гуд

2024-02-13 22:05 UTC, loqimean commented on app/views/account/diapers_periods/partials/index/_delete_button.erb
> +  <% if @category.preferable? %>
те ж саме про інстанс змінну

2024-02-13 22:09 UTC, loqimean commented on app/views/account/diapers_periods/partials/new/_form.html.erb
> +              readonly: true %>
щось мені це не подобається

2024-02-13 22:10 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +  <a href="<%= root_path %>" class="px-2 mt-3 rounded back-link" >
хелпер

2024-02-13 22:10 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +      <%= t "calculators.buttons.to_main" %>
дужки

2024-02-13 22:11 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +          { image: "money_to_spent_2.png", data_target: "moneyWillBeSpent", unit: t(".unit"), text: t(".money_will_be_spent") }].each_with_index do |item, index| %>
це тре в який хелпер винести

2024-02-13 22:11 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +            <%= image_tag "icons/vector_2.png", class: "vector-mobile" %>
тут тре задати альти

2024-02-13 22:11 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +            <%= image_tag item[:image], class: "img-margin" %>
тут теж

2024-02-13 22:12 UTC, loqimean commented on app/views/calculators/old_calculator.html.erb
> +  <a href="<%= root_path %>" class="px-2 mt-3 rounded back-link" >
знову хелпер

2024-02-13 22:12 UTC, loqimean commented on app/views/calculators/old_calculator.html.erb
> +      <%= t "calculators.buttons.to_main" %>
дужки

2024-02-13 22:12 UTC, loqimean commented on app/views/calculators/old_calculator.html.erb
> +        { image: "money_spent.png", data_target: "moneySpent", text: t(".money_spent") }].each do |item| %>
а це навіть взагалі дублюється

2024-02-13 22:12 UTC, loqimean commented on app/views/calculators/old_calculator.html.erb
> +          <%= image_tag item[:image], class: "rounded" %>
альт

2024-02-13 22:13 UTC, loqimean commented on app/services/categories/preferable_service.rb
> +    Category.where.not(id: @id).each do |cat|
ну тут тестів нема, а також не дуже розумію, що це за сервіс і навіщо він

2024-02-13 22:14 UTC, loqimean commented on app/decorators/calculator_decorator.rb
> +      to_be_used_diapers_amount: result.to_be_used_diapers_amount.to_s,
та навіщо дублювати, в кінці пропиши якийсь меп з цим методом

2024-02-13 22:15 UTC, loqimean commented on app/controllers/api/v1/diaper_calculators_controller.rb
> +      category_id          = params[:category_id].presence || Category.preferable.id
так а що це взагалі за преферейбл?

2024-02-13 22:15 UTC, loqimean commented on app/controllers/account/categories_controller.rb
> +    end
а це що таке?

2024-02-15 21:33 UTC, dafeys commented on app/services/categories/preferable_service.rb
> +    Category.where.not(id: @id).each do |cat|
Сервіс що знімає preferable з іншої категорії коли поставив чекбокс при редагуванні поточної, щоб preferable категорія була лише одна. Зробили по аналогії з існуючим preferable сервісом для калькулятора

2024-02-15 21:37 UTC, dafeys commented on app/controllers/api/v1/diaper_calculators_controller.rb
> +      category_id          = params[:category_id].presence || Category.preferable.id
preferable категорія це та що відображається по замовчуваню в новому калькуляторі, а також використовується старим калькулятором

2024-02-15 22:09 UTC, dafeys commented on app/decorators/calculator_decorator.rb
> +      to_be_used_diapers_amount: result.to_be_used_diapers_amount.to_s,
замінено на  .transform_values

2024-02-15 23:34 UTC, dafeys commented on app/views/account/diapers_periods/destroy.turbo_stream.erb
> +<%= turbo_stream.append(
Замінено на blank?. А така магія і задумувалася )) щоб юзер міг видаляти лише останній період і щоб не з'явилися пропуски в періодах. Нотифікацію про це додамо

2024-02-16 00:35 UTC, dafeys commented on app/views/account/categories/index.html.erb
> +                <%= button_to(account_category_path(id: category), method: :delete, data: { confirm: t('.confirm_delete') }) do %>
@obniavko  пофіксав в іншій гілці )

2024-02-19 18:44 UTC, kisiohlova commented on app/controllers/account/categories_controller.rb
> +    end
Метод в контролері для оновлення категорії на основну.

2024-02-19 18:58 UTC, kisiohlova commented on spec/factories/categories.rb
> +    end
Оскільки тут has_many асоціація, в [офіційній документації](https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#has_many-associations) є варіанти або обʼєднати в одну фабрику, або використовувати after(:create) callback. А так як наші категорії не лише для підгузків, додавати їх в фабрику підгузків було б не дуже гарно.

2024-02-21 12:02 UTC, kisiohlova commented on app/models/diapers_period.rb
> +            numericality: { only_integer: true, greater_than_or_equal_to: 1 }
Якщо забрати ``only_integer``, то немає нотіса про помилку від форми для користувача, якщо ввести не ціле число, а в period_start і period_end просто відкидається дробова частина. Тому, вирішили залишити, щоб було більш юзер френдлі)))

2024-02-26 10:30 UTC, loqimean commented on spec/factories/categories.rb
> +    end
ну то якщо ти за абстракцію, то навіщо мені на одному типі преферейбл діперс періоди? винеси в трейт, або створюй тоді, коли тобі тре в тестах

2024-02-26 20:27 UTC, dafeys commented on app/controllers/account/categories_controller.rb
> +    if @category.update(category_params.merge(preferable: category_params[:preferable].to_i))
Змінили enum на string

2024-03-01 07:27 UTC, loqimean commented on app/controllers/api/v1/diaper_calculators_controller.rb
> +      category_id          = params[:category_id].presence || Category.find_by(preferable: :preferable)
а це в якийсь хелпер метод тут винесіть

2024-03-01 07:27 UTC, loqimean commented on app/controllers/api/v1/diaper_calculators_controller.rb
> +      category_id          = params[:category_id].presence || Category.find_by(preferable: :preferable)
ну в приватний метод

2024-03-01 07:27 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +      concat image_tag("icons/vector_2.png", class: "vector-mobile", alt: "vertical arrow")
без конкату хіба не піде?

2024-03-01 07:27 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +  end
щось мені такі штуки не подобаються, давайте назад їх у вʼю

2024-03-01 07:27 UTC, loqimean commented on app/helpers/calculators_helper.rb
> +      concat image_tag("icons/vector_2.png", class: "vector-mobile", alt: "vertical arrow")
це теж у вʼю

2024-03-01 07:27 UTC, loqimean commented on app/models/category.rb
> +  enum preferable: { not_preferable: "0", preferable: "1" }
))))), коли я казав стрінг, то я мав на увазі, що коли ВИ зайдете в БД, то побачите на полі преферейбл 0, або 1, а це не дуж зрозуміло, тож якщо у вас тільки два значення, то варто задуматися, чи потрібен вам взагалі єнам, бо можливо вам потрібне..., булеве поле)))

2024-03-01 07:27 UTC, loqimean commented on app/models/diapers_period.rb
> +  end
от ви мені скажі, чому коли я звертаюся до ресурсу DiapersPeriod, я маю отримувати НЕ DiapersPeriod? якщо ви повертаєте скоуп категорій, то можливо варто і зробити скоуп у класа категорії?))) особливо коли вам з ІНШОГО класу нічого не потрібно, та і навіть в таких випадках можна прокинути proc на скоуп)

2024-03-01 07:27 UTC, loqimean commented on app/models/diapers_period.rb
> +  end
а, ще ж тут те саме))

2024-03-01 07:27 UTC, loqimean commented on app/services/calculators/diaper_usage_service.rb
> +    self
а навіщо тут селф?

2024-03-01 07:27 UTC, loqimean commented on app/views/account/categories/index.html.erb
> +        <tr class="<%= category.preferable? ? "table-success" : "table-light" %>">
хелпер

2024-03-01 07:27 UTC, loqimean commented on app/views/account/categories/index.html.erb
> +                <%= button_to(account_category_path(id: category), method: :delete, data: { confirm: t(".confirm_delete") }) do %>
а цей конфірм працює?)

2024-03-01 07:27 UTC, loqimean commented on app/views/account/diapers_periods/destroy.turbo_stream.erb
> +    ) unless @diapers_periods.blank? %>
```suggestion
    ) if @diapers_periods.present? %>
```

2024-03-01 07:27 UTC, loqimean commented on app/views/account/diapers_periods/destroy.turbo_stream.erb
> +    ) unless @diapers_periods.blank? %>
та і краще винесіть це на загальний if

2024-03-01 07:27 UTC, loqimean commented on app/views/account/diapers_periods/partials/categories/_content.html.erb
> +          <tr id="<%= dom_id(category) %>" class="<%= category.preferable? ? "table-success" : "text-inherit" %>">
знову хелпер)

2024-03-01 07:27 UTC, loqimean commented on app/views/account/diapers_periods/partials/categories/_content.html.erb
> +              <%= category.name %>
а це не тре ніяким тегом огорнути?))

2024-03-01 07:27 UTC, loqimean commented on app/views/account/diapers_periods/partials/edit/_form.html.erb
> +              readonly: true %>
а чому тут рідонлі?)

2024-03-01 07:27 UTC, loqimean commented on app/views/account/diapers_periods/partials/index/_delete_button.erb
> +  <% if category.preferable? %>
вкладені іфи не гуд

2024-03-01 07:27 UTC, loqimean commented on app/views/account/diapers_periods/partials/index/_delete_button.erb
> +<% if diapers_period == diapers_periods.last %>
щось не дуже розумію, що тут відбувається

2024-03-01 07:27 UTC, loqimean commented on app/views/account/diapers_periods/partials/index/_delete_button.erb
> +      <span title="<%= t(".cannot_delete_category") %>"><i class="mx-2 fa fa-trash"></i></span>
так а причому категорія до періода?

2024-03-01 07:27 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +      <%= image_tag "icons/arrow-left.svg", class: "z-1", alt: "arrow left" %>
inline_svg

2024-03-01 07:27 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +      <%= image_tag "icons/arrow-left.svg", class: "z-1", alt: "arrow left" %>
а також у svg іконок нема атрибуту alt

2024-03-01 07:27 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +    <%= image_tag "scales.png", class: "scales_img" %>
alt

2024-03-01 07:27 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +    <div class="result-container">
а тут дійсно потрібно 3 блоки?

2024-03-01 07:27 UTC, loqimean commented on config/routes.rb
> +          delete :destroy_category
так виглядає, що замість трьох роутів простіше було би написати resources :categories ))))

2024-03-01 07:27 UTC, loqimean commented on db/migrate/20240207143101_add_preferable_to_categories.rb
> +    add_column :categories, :preferable, :string, default: "0", null: false
навіщо огортати 0 в стрінг)

2024-03-01 07:27 UTC, loqimean commented on spec/requests/account/diapers_periods_spec.rb
> +        expect(response).to render_template(:create)
ну а де перевірка, що айтем успішно заінсертився?

2024-03-01 07:27 UTC, loqimean commented on spec/requests/account/diapers_periods_spec.rb
> +        expect(response).to render_template(:update)
а де перевірка, що він апдейтнувся

2024-03-01 07:27 UTC, loqimean commented on spec/requests/account/diapers_periods_spec.rb
> +      expect(response).to have_rendered(:destroy)
де перевірка, що айтем видалений з вʼю?))

2024-03-01 07:27 UTC, loqimean commented on spec/requests/account/diapers_periods_spec.rb
> +      expect(response).to have_rendered(:destroy)
і так скрізь

2024-03-01 07:27 UTC, loqimean commented on spec/services/categories/preferable_service_spec.rb
> +        service = described_class.new(become_preferable_category)
у нас для цього є `let` 🙂

2024-03-01 07:27 UTC, loqimean commented on spec/services/categories/preferable_service_spec.rb
> +        service = described_class.new(become_preferable_category)
the same thing)

2024-03-01 10:09 UTC, dafeys commented on app/models/category.rb
> +  enum preferable: { not_preferable: "0", preferable: "1" }
Це ж було вже

2024-03-01 10:15 UTC, kisiohlova commented on app/models/category.rb
> +  enum preferable: { not_preferable: "0", preferable: "1" }
З самого почтаку було))
```
t.boolean "preferable", default: false
```
7c8e744fa8375b93735565f18c651f4bb4e660ac

2024-03-01 10:19 UTC, kisiohlova commented on app/models/diapers_period.rb
> +  end
Бо наче ж домовились що в нас модель категорій абстрактна, тому винесли те, що стосується дайперс періодів в модель дайперс періодів)
Ось тут твої коментарі:
https://github.com/ita-social-projects/ZeroWaste/pull/765/files/877ef243dcd7083c4a50ed07a19b420ab536f811#diff-deed30f0fddef89f28507686ea15945ba15838c6169535ab7b9c0605a4af64a6

2024-03-01 10:20 UTC, dafeys commented on app/views/account/diapers_periods/partials/edit/_form.html.erb
> +              readonly: true %>
Щоб адмін міг редагувати ціни і кількість, але не періоди, щоб він не лишив пропуск в періодах або оверлапу і не зламався процес калькуляції

2024-03-03 16:12 UTC, dafeys commented on app/services/calculators/diaper_usage_service.rb
> +    self
Щоб повертався екземпляр класу, який далі передається в декоратор на вью калькулятора (змінні скільки було використано, витрачено і т.д. )

2024-03-03 16:30 UTC, dafeys commented on app/views/account/categories/index.html.erb
> +                <%= button_to(account_category_path(id: category), method: :delete, data: { confirm: t(".confirm_delete") }) do %>
пофікшено в іншому ПР, стягнемо зміни

2024-03-03 16:36 UTC, dafeys commented on app/views/account/diapers_periods/destroy.turbo_stream.erb
> +    ) unless @diapers_periods.blank? %>
Замінили на if

2024-03-03 16:47 UTC, dafeys commented on app/views/account/diapers_periods/partials/index/_delete_button.erb
> +<% if diapers_period == diapers_periods.last %>
оптимізували логіку

2024-03-03 16:47 UTC, dafeys commented on app/views/account/diapers_periods/partials/index/_delete_button.erb
> +      <span title="<%= t(".cannot_delete_category") %>"><i class="mx-2 fa fa-trash"></i></span>
бо не можна видаляти періоди в основній категорії

2024-03-03 17:04 UTC, dafeys commented on app/views/calculators/new_calculator.html.erb
> +    <div class="result-container">
Треба, без них не правильно працює перенесення результатів на нові рядки для менших скрінів.

2024-03-03 17:09 UTC, dafeys commented on config/routes.rb
> +          delete :destroy_category
а навіщо нам всі рестфул роути, якщо нам потрібно лише ці 3 і 2 з них не стандартні

2024-03-06 08:07 UTC, loqimean requested changes

2024-03-06 08:07 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +    <div class="result-container">
як це не правильно, якщо ці три блоки те ж саме, що і один, тільки з цими трьома класами

2024-03-06 08:07 UTC, loqimean commented on app/views/calculators/new_calculator.html.erb
> +          { image: "money_to_spent_2.png", data_target: "moneyWillBeSpent", unit: t(".unit"), text: t(".money_will_be_spent") }].each_with_index do |item, index| %>
не виніс)

2024-03-06 08:07 UTC, loqimean commented on app/views/calculators/old_calculator.html.erb
> +        { image: "money_spent.png", data_target: "moneySpent", text: t(".money_spent") }].each do |item| %>
те ж саме

2024-03-06 08:07 UTC, loqimean commented on config/routes.rb
> +          delete :destroy_category
теж не готово)

2024-03-06 08:07 UTC, loqimean commented on spec/services/categories/preferable_service_spec.rb
> +        if category != become_preferable_category
а це навіщо тут?

2024-03-06 08:07 UTC, loqimean commented on spec/services/categories/preferable_service_spec.rb
> +        if category != become_preferable_category
точно не потрібен

2024-03-06 12:25 UTC, kisiohlova commented on app/controllers/account/diapers_periods_controller.rb
> +      redirect_to account_site_setting_path, alert: t("notifications.category_diapers_period_not_deleted")
Please, see last changes: https://github.com/ita-social-projects/ZeroWaste/pull/765/files#diff-35c7f067682429ddcd7ad64f35918c25f1190ecb9a23d22e4370fc5773f6e0a5

2024-03-06 15:54 UTC, dafeys commented on app/services/calculators/diaper_usage_service.rb
> +    self
Переробили, повертається хеш в def result

2024-03-13 10:52 UTC, loqimean commented on app/controllers/account/diapers_periods/categories_controller.rb
> +    @category = Category.find(params[:id])
ресурс

2024-03-13 10:52 UTC, loqimean commented on app/controllers/account/diapers_periods_controller.rb
> +    @category            = Category.find(params[:category_id])
ресурс

2024-03-13 17:19 UTC, dafeys commented on app/controllers/account/diapers_periods/categories_controller.rb
> +    @categories = Category.without_diapers_periods
це інший скоуп, чи може бути 2 collection?

2024-03-13 17:31 UTC, dafeys commented on app/controllers/account/diapers_periods_controller.rb
> +    @category            = Category.find(params[:category_id])
А чи правильно робити ресурс на категорію в контроллері diapers_periods?

2024-03-13 17:43 UTC, dafeys commented on app/controllers/account/diapers_periods_controller.rb
> +    @diapers_periods     = @category.diapers_periods.order(:id)
Прибрали взагалі, працює без цього добре ))

2024-03-15 12:47 UTC, loqimean commented on app/controllers/account/diapers_periods/categories_controller.rb
> +    @categories = Category.without_diapers_periods
ну диви, мало би бути так:
```ruby
def collection
  Category.ordered
end

collection.with_something
...
collection.without_something
```

2024-03-17 11:06 UTC, loqimean approved these changes

2024-03-17 20:02 UTC, merged