[Products] [Add product]  Resolve Validation Error for Sum Range.
ita-social-projects/ZeroWaste pull request #769
Opened 2024-02-11 15:47 UTC by Natali-Kotelnitska

dev

* resolves  #724 

## Code reviewers

- [ ] @obniavko 
- [ ] @loqimean 

## Summary of issue
When entering an excessively long value in the category field (e.g., 999999999999999999999999999999999999999999999999), an error occurs with the message 'We're sorry, but something went wrong. If you are the application owner, check the logs for more information.'

## Summary of change
The validation and error handling have been updated to show a specific error message ("Sum is too long (must be between 0 and 999999.99)") beneath the category field as intended.

![Знімок екрана (531)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/5ffcabf0-0008-4bb2-8bc5-dd69abf66f78)
Additionally, translations have been added for the Ukrainian locale ("Сума занадто велика (повинна бути від 0 до 999999.99)".

![Знімок екрана (532)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/6dba24a9-dcaa-4f0e-b7ef-0e67461b033a)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-02-11 20:46 UTC, obniavko approved these changes

2024-02-13 21:44 UTC, loqimean requested changes

2024-02-13 21:44 UTC, loqimean commented on config/locales/uk/uk.yml
> +              less_than: "занадто велика (повинна бути від 0 до 999999.99)"
не гуд хардкодити, тут точно мали б передаватися автоматично параметри. Якщо я поміняю макс на 500, то і тут тре міняти? не гуд

2024-02-14 05:52 UTC, Natali-Kotelnitska commented on config/locales/uk/uk.yml
> +              less_than: "занадто велика (повинна бути від 0 до 999999.99)"
Виправила.

2024-02-14 10:23 UTC, loqimean approved these changes

2024-02-14 10:59 UTC, merged