720 fix revert btn
ita-social-projects/ZeroWaste pull request #775
Opened 2024-02-20 01:16 UTC by iryna-borniak

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-02-27 07:32 UTC, obniavko approved these changes

2024-03-01 07:30 UTC, loqimean requested changes

2024-03-01 07:30 UTC, loqimean commented on app/controllers/account/site_settings_controller.rb
> +    if @site_setting.update(title: "ZeroWaste", favicon: {
винеси параметтри в якусь змінну

2024-03-01 07:30 UTC, loqimean commented on app/controllers/account/site_settings_controller.rb
> +    if @site_setting.update(title: "ZeroWaste", favicon: {
я б навіть сказав клас метод сайт сетінгів, це має там сторитися і має тобі бути клас-метод як от revert!

2024-03-01 07:30 UTC, loqimean commented on app/controllers/account/site_settings_controller.rb
> +    if @site_setting.update(title: "ZeroWaste", favicon: {
чи restore_defaults!

2024-03-01 07:30 UTC, loqimean commented on app/views/account/site_settings/edit.html.erb
> +                  method: :patch,
а чому патч?

2024-03-01 07:30 UTC, loqimean commented on app/views/account/site_settings/edit.html.erb
> +                  method: :patch,
я бсказав навіть, що це put)

2024-03-09 19:56 UTC, iryna-borniak commented on app/views/account/site_settings/edit.html.erb
> +                  method: :patch,
Indeed, appreciated

2024-03-09 19:56 UTC, iryna-borniak commented on app/controllers/account/site_settings_controller.rb
> +    if @site_setting.update(title: "ZeroWaste", favicon: {
Done

2024-03-11 17:52 UTC, merged