Feature/Add Footer to the Admin page
ita-social-projects/ZeroWaste pull request #797
Opened 2024-02-28 16:38 UTC by Natali-Kotelnitska

dev
* resolves  #796 

## Code reviewers

- [ ] @loqimean 

## Summary of issue

Implement a footer on the Admin page to enhance user experience and provide essential information.

## Summary of change

- Added HTML structure for the footer section.
- Styled the footer to match the overall website design.
- Included a functional link to SoftServe Academy within the footer, directing users to the correct page.
- Implemented a responsive design, ensuring the footer adapts seamlessly to different screen sizes.

![Знімок екрана (542)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/d5221b30-6e01-4046-874f-291f4c0ad77f)

- Made the footer content dynamic, accommodating translations for both English and Ukrainian users.

![Знімок екрана (546)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/73566175-d422-4f6d-a8d8-5cf4825bfb93)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-02-28 17:21 UTC, kisiohlova requested changes

2024-02-28 17:21 UTC, kisiohlova commented on app/views/layouts/_account_footer.html.erb
> +      <p>&copy; <%= Time.now.year %> <span class="text-success font-bold">Zero Waste Lviv</span></p>
```suggestion
      <p>&copy; <%= Date.current.year %> <span class="text-success font-bold">Zero Waste Lviv</span></p>
```

2024-02-28 17:29 UTC, kisiohlova approved these changes

2024-03-01 07:36 UTC, loqimean approved these changes

2024-03-01 07:37 UTC, merged