695 main page burger menu
ita-social-projects/ZeroWaste pull request #800
Opened 2024-02-29 19:51 UTC by DmytroStoliaruk

dev
## ZeroWaste project

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @loqimean

### Second Level Review

- [ ] @github_username

## Summary of issue

Create a burger menu for the main page

## Summary of change

1. Add a Stimulus controller for a burger
2. Add styles for menu elements 

Uploading Main burger menu.mov…

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-03-03 13:21 UTC, dafeys approved these changes

2024-03-04 12:51 UTC, loqimean requested changes

2024-03-04 12:51 UTC, loqimean commented on app/views/account/shared/_navigation.html.erb
> +            <% if current_user.admin? %>
вкладені іфи не гуд, це завжди призводить до проблем, міняй

2024-03-04 12:51 UTC, loqimean commented on app/views/account/shared/_navigation.html.erb
> +</body>
де нова строка?) і чому тут боді лежить?))

2024-03-04 12:51 UTC, loqimean commented on db/schema.rb
> +  end
чому це тут?)

2024-03-04 12:51 UTC, loqimean commented on spec/features/navigator_spec.rb
> +    expect(page).to have_link("Contact us", href: "/en/messages/new", visible: :all)
а роут хелпери для чого?))

2024-03-04 12:51 UTC, loqimean commented on spec/features/navigator_spec.rb
> +      expect(page).to have_link("Admin", href: "/en/account/calculators", visible: :all)
те ж питання

2024-03-04 12:51 UTC, loqimean commented on spec/features/navigator_spec.rb
> +      expect(page).to have_no_link("Admin", href: "/en/accounts/calculators", visible: :all)
і тут

2024-03-04 12:51 UTC, loqimean commented on spec/features/visit_login_spec.rb
> +    expect(page).to have_link("Log Out", href: "/en/users/sign_out", visible: :all)
теж

2024-03-04 12:58 UTC, DmytroStoliaruk commented on db/schema.rb
> +  end
просило міграцію при оновленні... Прибрав.

2024-03-04 13:07 UTC, DmytroStoliaruk commented on spec/features/navigator_spec.rb
> +    expect(page).to have_link("Contact us", href: "/en/messages/new", visible: :all)
дійсно.) поправив

2024-03-04 13:07 UTC, DmytroStoliaruk commented on spec/features/navigator_spec.rb
> +      expect(page).to have_link("Admin", href: "/en/account/calculators", visible: :all)
поправив

2024-03-04 13:07 UTC, DmytroStoliaruk commented on spec/features/navigator_spec.rb
> +      expect(page).to have_no_link("Admin", href: "/en/accounts/calculators", visible: :all)
поправив

2024-03-04 13:09 UTC, DmytroStoliaruk commented on spec/features/visit_login_spec.rb
> +    expect(page).to have_link("Log Out", href: "/en/users/sign_out", visible: :all)
поправив

2024-03-06 07:44 UTC, loqimean commented on spec/features/navigator_spec.rb
> +      expect(page).to have_link("Log Out", href: destroy_user_session_path(locale: "en"), visible: :all)
а навіщо ти скрізь передаєш локаль? вона ж по-замовчуванню має бути якась дефолтна

2024-03-06 07:53 UTC, DmytroStoliaruk commented on spec/features/navigator_spec.rb
> +      expect(page).to have_link("Log Out", href: destroy_user_session_path(locale: "en"), visible: :all)
щоб бути впевненим, бо перевіряю саме англійську версію.) Прибрав, працює і без цього.

2024-03-06 08:08 UTC, loqimean approved these changes

2024-03-06 08:31 UTC, merged