Add 404 page
ita-social-projects/ZeroWaste pull request #820
Opened 2024-03-11 17:12 UTC by obniavko

dev
## ZeroWaste project

* [Project ticket #799](https://github.com/ita-social-projects/ZeroWaste/issues/799)

## Code reviewers

- [ ] @DmytroStoliaruk 
- [ ] @loqimean 

## Summary of issue

The site does not have a 404 page.

## Summary of change

1. Added 404 page for public side of website.

![404-public](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/dc547756-6bf2-4cf0-aa21-c20d195646ae)

2. Added 404 page for admin panel.

![404-admin](https://github.com/ita-social-projects/ZeroWaste/assets/108181313/00b5dd11-0e6d-4d26-b29e-5a2771362402)

## CHECK LIST
- [x]  СI passed
- [x]  Сode coverage >=95%
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [x]  I've checked new feature as logged in and logged out user if needed
- [x]  PR meets all conventions

2024-03-11 17:18 UTC, DmytroStoliaruk approved these changes

2024-03-20 05:42 UTC, loqimean requested changes

2024-03-20 05:42 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :render_404
а що це? а навіщо це? давай видаляй

2024-05-11 16:57 UTC, obniavko commented on app/controllers/account/calculators_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :render_404
Fixed

2024-06-16 07:31 UTC, closed without merging