[Products]: Refactor Forms to Turbo Streams: Fix Translation.
ita-social-projects/ZeroWaste pull request #832
Opened 2024-03-19 08:25 UTC by Natali-Kotelnitska

dev

## Code reviewers

- [ ] @loqimean 

## Summary of issue

After switching the language, the Admin is returned back to the page with the list of products instead of observing the translation as expected.

## Summary of change
- Created form partials for updating and creating the product.
- Rewrote the formsinto Turbo Stream format.
- Refactored locale values for correct translation.

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-03-20 05:44 UTC, loqimean requested changes

2024-03-20 05:44 UTC, loqimean commented on app/views/account/products/edit.turbo_stream.erb
> +<%= turbo_stream.replace(dom_id(@product, :form), partial: "account/products/partials/edit/form", locals: {product: @product}) %>
додай пробіли в хеші

2024-03-20 05:44 UTC, loqimean commented on app/views/account/products/new.turbo_stream.erb
> +<%= turbo_stream.replace(dom_id(@product, :form), partial: "account/products/partials/new/form", locals: {product: @product}) %>
теж пробіли

2024-03-20 05:44 UTC, loqimean commented on app/views/account/products/partials/edit/_form.html.erb
> + <%= simple_form_for @product, method: :patch, url: account_product_path, html: {id: dom_id(product, :form)}, data: { controller: "price-form" } do |f| %>
і тут пробіли

2024-03-20 05:44 UTC, loqimean commented on app/views/account/products/partials/new/_form.html.erb
> +      <% Category.ordered_by_name.each do |category| %>
а це має бути в змінній і прийти з контроллера

2024-03-20 05:44 UTC, loqimean commented on app/views/account/products/partials/edit/_form.html.erb
> +        <% if Category.ordered_by_name.exists? %>
це теж

2024-03-20 07:28 UTC, Natali-Kotelnitska commented on app/views/account/products/edit.turbo_stream.erb
> +<%= turbo_stream.replace(dom_id(@product, :form), partial: "account/products/partials/edit/form", locals: {product: @product}) %>
Done.

2024-03-20 07:28 UTC, Natali-Kotelnitska commented on app/views/account/products/new.turbo_stream.erb
> +<%= turbo_stream.replace(dom_id(@product, :form), partial: "account/products/partials/new/form", locals: {product: @product}) %>
Done.

2024-03-25 13:28 UTC, obniavko approved these changes

2024-03-25 15:35 UTC, dafeys approved these changes

2024-04-02 08:00 UTC, loqimean approved these changes

2024-04-02 08:10 UTC, merged