Fix Session Timeout Message Duplication
ita-social-projects/ZeroWaste pull request #844
Opened 2024-03-25 11:07 UTC by Natali-Kotelnitska

dev

* resolves #789 

## Code reviewers

- [ ] @loqimean 

- [ ] @obniavko 

## Summary of issue

There is currently an issue where two different warning messages, 'true' and "Your session expired. Please sign in again to continue", are appearing after non-working time when logged in. This inconsistency in warning messages needs to be resolved.

## Summary of change

The issue was fixed by modifying the flash message iteration in the view. The 'timedout' message type is now skipped, preventing the 'true' message from being displayed.

![Знімок екрана (608)](https://github.com/ita-social-projects/ZeroWaste/assets/83007830/a7830488-9936-4053-8480-0348f95133b9)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-03-25 11:17 UTC, obniavko approved these changes

2024-04-02 08:05 UTC, loqimean requested changes

2024-04-02 08:05 UTC, loqimean commented on app/views/layouts/_flash_messages.html.erb
> +  <% next if message_type == 'timedout' %>
а якщо будуть інші дублікати? не окей, бо тоді ти будеш додавати так до безкінечності, ти маєш задати універсальне рішення

2024-04-02 19:42 UTC, Natali-Kotelnitska commented on app/views/layouts/_flash_messages.html.erb
> +  <% next if message_type == 'timedout' %>
Переробила.

2024-04-22 08:30 UTC, loqimean requested changes

2024-04-22 08:30 UTC, loqimean commented on app/views/layouts/_flash_messages.html.erb
> +  <% next unless message.is_a? String %>
а не простіше не ітеруватися по кейсам, коли нема месиджів?)

2024-05-02 11:37 UTC, loqimean commented on app/views/layouts/_flash_messages.html.erb
> +  <%= turbo_stream.toast(message, background: message_type) if message.is_a? String %>
так а чому так? які ще кейси бувають? масив?)

2024-05-18 15:06 UTC, loqimean approved these changes

2024-05-18 15:06 UTC, loqimean commented on app/views/layouts/_flash_messages.html.erb
> +<% flash.to_h.excluding("timedout").each do |message_type, message| %>
```suggestion
<% flash.to_h.except("timedout").each do |message_type, message| %>
```

2024-05-18 15:06 UTC, loqimean commented on app/views/layouts/_flash_messages.html.erb
> +<% flash.to_h.excluding("timedout").each do |message_type, message| %>
краще це заюзай і можеш мерджати

2024-05-18 16:08 UTC, merged