Add title "Diaper calculator"
ita-social-projects/ZeroWaste pull request #867
Opened 2024-04-14 21:40 UTC by iambrozjak

dev
* [Project ticket #863](https://github.com/ita-social-projects/ZeroWaste/issues/863)

## Code reviewers

- [ ] @loqimean 
- [ ] @dafeys 

## Summary of issue

Calculator title is absent on page.

## Summary of change
'Diaper сalculator/Калькулятор підгузків' Calculator title added in the first section. Ukrainian localization fixed.
![image](https://github.com/ita-social-projects/ZeroWaste/assets/129009813/a437a710-3f1e-44b1-af04-70d9ff6a9072)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/129009813/3c9e3eca-0fed-4266-92a9-54d0633f7326)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-04-15 21:25 UTC, dafeys approved these changes

2024-04-22 08:25 UTC, loqimean requested changes
Чому чекбокси не відмічені?)

2024-04-22 08:25 UTC, loqimean commented on config/locales/uk/uk.yml
> +      diaper_сalculator: "Калькулятор підгузків"
а англійською?

2024-04-22 13:34 UTC, loqimean approved these changes

2024-04-22 13:34 UTC, merged