Category name translation based on site locale
ita-social-projects/ZeroWaste pull request #881
Opened 2024-05-17 15:42 UTC by dafeys

dev

- #879 

## Code reviewers

- [ ] @loqimean 
- [ ]  

## Summary of issue
Categories contain only one name, regardless of the language of the site

## Summary of change
- Added concern for dynamically determining the category name
- Database and model changes: replaced name with en_name and uk_name
- Views refactored to accommodate the new names
- Refactored tests to reflect the new category names and added tests for the concern

2024-05-17 18:14 UTC, DmytroStoliaruk approved these changes

2024-05-18 15:16 UTC, loqimean requested changes

2024-05-18 15:16 UTC, loqimean commented on db/migrate/20240515234207_add_en_name_to_categories.rb
> +    add_index :categories, "lower((en_name)::text)", name: "index_categories_on_en_name", unique: true
та думаю зроби цей чейндж одною міграцією

2024-05-18 15:16 UTC, loqimean commented on app/models/concerns/translatable.rb
> +    rescue NoMethodError
цей кейс бачу не покритий тестами

2024-05-18 15:16 UTC, loqimean commented on app/models/concerns/translatable.rb
> +      public_send(:"#{I18n.locale}_name")
замість рескʼю я думаю краще заюзай respond_to?

2024-05-18 15:16 UTC, loqimean commented on app/models/concerns/translatable.rb
> +    end
а це не окей, бо твій концерн змушує мене називати щось так, як ти колись прописав. Дай можливість прописувати для чого саме ти додаєш цю перекладуваність

2024-05-18 15:16 UTC, loqimean commented on app/models/concerns/translatable.rb
> +    end
типу на яке поле-поля

2024-05-24 10:06 UTC, loqimean requested changes

2024-05-24 10:06 UTC, loqimean commented on app/models/concerns/.keep
най буде цей файл, не видаляй

2024-05-24 10:06 UTC, loqimean commented on spec/models/conserns/translatable_spec.rb
> +      let(:category) { create(:category, en_name: "Books", uk_name: "Книги") }
твій концерн є чимось абстрактним і не повинен залежати від чогось ззовні. От тобі приклад - ти поміняєш назву поля в категорії, чи її видалиш і вже будеш змушений міняти тести, які зовсім того не стосуються. Тож створи в сапорті dummy клас-модельку, яку і будеш тестувати, юзай наприклад `SomeClass.extend`

2024-05-31 09:33 UTC, loqimean approved these changes

2024-05-31 09:33 UTC, merged