Prohibition on entering "+" and "-" characters in the 'Sum' field
ita-social-projects/ZeroWaste pull request #882
Opened 2024-05-20 17:56 UTC by iambrozjak

* [Project ticket #746](https://github.com/ita-social-projects/ZeroWaste/issues/746)

## Code reviewers

- [ ] @loqimean 
- [x] @obniavko 

## Summary of issue
There shouldn't be an opportunity to enter any of those signs '-' and '+' in 'Sum' fields

## Summary of change
Added a ban on entering "+" and "-" characters in the 'Sum'  field when creating and editing a product
![image](https://github.com/ita-social-projects/ZeroWaste/assets/129009813/af338875-ac1b-4b19-b3c9-fd8d039cfa11)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/129009813/53188559-f611-45cf-a516-5b4e4203446e)
![image](https://github.com/ita-social-projects/ZeroWaste/assets/129009813/48d3dbd3-afd7-46b3-bbbc-75e70b3b44ad)

## CHECK LIST
- [x]  СI passed
- [x]  Сode coverage >=95%
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [x]  I've checked new feature as logged in and logged out user if needed
- [x]  PR meets all conventions

2024-05-20 18:04 UTC, obniavko approved these changes

2024-05-24 10:01 UTC, loqimean requested changes

2024-05-24 10:01 UTC, loqimean commented on app/views/account/products/partials/new/_form.html.erb
> +              <div class="error-message" style="display: none; color: #9e1503;" data-price-form-target="errorMessage"><%= t(".form.error_sum") %></div>
інлайнові стилі, це зло

2024-05-24 10:01 UTC, loqimean commented on app/views/account/products/partials/edit/_form.html.erb
> +                <div class="error-message" style="display: none; color: #9e1503;" data-price-form-target="errorMessage"><%= t(".form.error_sum") %></div>
аналогічно

2024-05-24 10:01 UTC, loqimean commented on app/javascript/controllers/price_form_controller.js
> +    const regex = /^[^\+\-]+$/;
а чому не валідувати на тільки цифри? не розумію навіщо так ускладнювати

2024-05-31 07:23 UTC, iambrozjak commented on app/views/account/products/partials/new/_form.html.erb
> +              <div class="error-message" style="display: none; color: #9e1503;" data-price-form-target="errorMessage"><%= t(".form.error_sum") %></div>
виправила)

2024-05-31 07:24 UTC, iambrozjak commented on app/javascript/controllers/price_form_controller.js
> +    const regex = /^[^\+\-]+$/;
змінила регулярний вираз)

2024-05-31 09:34 UTC, loqimean approved these changes

2024-06-03 15:53 UTC, loqimean approved these changes

2024-06-03 17:39 UTC, merged