ZER-79 - Added Create Calculator page on admin side
ita-social-projects/ZeroWaste pull request #89
Opened 2021-09-15 06:29 UTC by halyna-m

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-09-15 06:31 UTC, andriibureviy approved these changes

2021-09-15 06:31 UTC, Nazarii-Makohin approved these changes

2021-09-15 20:14 UTC, maksymst requested changes
You've added a new validation in the Calculator model. It requires a unit test. Also, please add capybara test

2021-09-15 20:14 UTC, maksymst commented on app/controllers/admins/calculators_controller.rb
> +                    notice: 'Successfully Updated'
```suggestion
                    notice: 'Calculator has been successfully updated'
```

2021-09-15 20:14 UTC, maksymst commented on app/controllers/admins/calculators_controller.rb
> +                    notice: 'Calculator was successfully created.'
```suggestion
                    notice: 'Calculator has been successfully created.'
```

2021-09-15 20:14 UTC, maksymst commented on app/controllers/admins/calculators_controller.rb
> +        flash[:error] = 'Invalid'
you display errors by using `@calculator.errors`. why do you need this?

2021-09-15 20:14 UTC, maksymst commented on app/controllers/admins/calculators_controller.rb
> +    before_action :find_calculator, except: %i[new create calculator_params]
`except` and `include` options contain only `controller actions`

2021-09-16 09:52 UTC, andriibureviy approved these changes

2021-09-16 10:07 UTC, Nazarii-Makohin submitted a review, later dismissed

2021-09-16 10:49 UTC, maksymst requested changes

2021-09-16 10:49 UTC, maksymst commented on spec/features/admin/create_calculator_spec.rb
> +      expect(page).to have_current_path("/admins/calculators/1/edit")
calculator identifier in the url can not be static

2021-09-16 17:38 UTC, andriibureviy approved these changes

2021-09-16 17:53 UTC, Nazarii-Makohin approved these changes

2021-09-16 18:43 UTC, maksymst approved these changes

2021-09-16 18:53 UTC, merged