890 update ruby to latest 1
ita-social-projects/ZeroWaste pull request #899
Opened 2024-08-03 18:48 UTC by DmytroStoliaruk

dev
## JIRA

* [#890 ]

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @loqimean 
## Summary of issue

Update to Ruby version to 3.3.3

## Summary of change

1. Changed the Ruby version 
2. update the code style for the new Rubocop requirements

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-10-31 01:30 UTC, DanielVajnagi commented
Updated to ruby 3.3.5

2024-10-31 12:09 UTC, DanielVajnagi commented
> dev
> 
> ## Zerowaste
> * [[Update ruby to latest #890](https://github.com/ita-social-projects/ZeroWaste/issues/890) ]
> 
> ## Code reviewers
> * [ ]  @igorSimash
> 
> ### Second Level Review
> * [ ]  @loqimean
> 
> ## Summary of issue
> Update to Ruby version to 3.3.3
> 
> ## Summary of change
> 1. Changed the Ruby version
> 2. update the code style for the new Rubocop requirements
> 
> ToDo
> 
> ## CHECK LIST
> * [x]   СI passed
> * [ ]   Сode coverage >=95%
> * [ ]   PR is reviewed manually again (to make sure you have 100% ready code)
> * [ ]   All reviewers agreed to merge the PR
> * [x]   I've checked new feature as logged in and logged out user if needed
> * [ ]   PR meets all conventions

2024-10-31 21:00 UTC, igorSimash approved these changes

2024-11-05 07:19 UTC, loqimean requested changes

2024-11-05 07:40 UTC, loqimean requested changes
круть), а тепер фіксай конфлікти)))

2024-11-05 15:48 UTC, loqimean approved these changes

2024-11-05 16:11 UTC, merged