Feat: Add 'Under Construction' page
ita-social-projects/ZeroWaste pull request #904
Opened 2024-08-12 18:31 UTC by Natali-Kotelnitska

dev
* resolves #896 

## Code reviewers

- [ ] @loqimean 

- [ ] @github_username

## Summary of issue

This task addresses the need to create an "Under Construction" page to inform users that certain features, specifically the Calculators page, are currently unavailable. 
The goal is to ensure that users are informed about ongoing updates and improvements

## Summary of change

- Developed a new view (`shared/under_construction.html.erb`) with elegant design and styling that matches the site's overall theme.
- Included an appropriate image and responsive styles to ensure the page is visually appealing across all devices.
- Modified the `index` action in the `CalculatorsController` to render the "Under Construction" page when the application is running in the production environment.
- Updated localization files with translations for both English and Ukrainian.

### After Changes 
![Знімок екрана (782)](https://github.com/user-attachments/assets/84cccf71-3403-437c-9087-671b5322a20b)
![Знімок екрана (785)](https://github.com/user-attachments/assets/b44ac48f-dde3-4df7-bc61-7d5b9ab8d624)

### Mobile Version (320px)
![Знімок екрана (783)](https://github.com/user-attachments/assets/5296b4ec-ebbd-4bd7-9909-ff77be313985)

## CHECK LIST

- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-08-16 09:28 UTC, loqimean requested changes

2024-08-16 09:28 UTC, loqimean commented on .rubocop.yml
> +  Enabled: false
так а це чому вирублено?))

2024-08-16 09:28 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +    render "shared/under_construction" unless Rails.env.local?
а таке питання, код знизу виконуєтсья після рендера, чи ні?)

2024-08-16 09:28 UTC, loqimean commented on app/views/shared/under_construction.html.erb
> +<section class="under-constr_section">
називай більш зрозуміло, повною назвою, також якщо юзаєш БЕМ, то юзай його правильно)

2024-08-16 09:28 UTC, loqimean commented on app/views/shared/under_construction.html.erb
> +<section class="under-constr_section">
https://en.bem.info/methodology/
https://en.bem.info/methodology/css/

2024-08-16 09:28 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +    render "shared/under_construction" unless Rails.env.local?
а де тест на цей кейс?))

2024-08-16 09:28 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +    render "shared/under_construction" unless Rails.env.local?
ВСІ кейси мають бути покриті тестами

2024-08-18 14:56 UTC, Natali-Kotelnitska commented on .rubocop.yml
> +  Enabled: false
> так а це чому вирублено?))

Rubocop свариться 'Unknown environment local'.

2024-08-19 08:52 UTC, Natali-Kotelnitska commented on app/controllers/account/calculators_controller.rb
> +    render "shared/under_construction" unless Rails.env.local?
> а таке питання, код знизу виконуєтсья після рендера, чи ні?)

рендериться. Додала в ПР Video Demonstration: Development vs. Production.

2024-08-19 08:53 UTC, Natali-Kotelnitska commented on app/controllers/account/calculators_controller.rb
> +    render "shared/under_construction" unless Rails.env.local?
> а таке питання, код знизу виконуєтсья після рендера, чи ні?)
Рендериться. Додала в ПР Video Demonstration: Development vs. Production.

2024-08-19 08:53 UTC, Natali-Kotelnitska commented on app/controllers/account/calculators_controller.rb
> +    render "shared/under_construction" unless Rails.env.local?
> а де тест на цей кейс?))

Додала тести.

2024-08-19 08:55 UTC, Natali-Kotelnitska commented on app/views/shared/under_construction.html.erb
> +<section class="under-constr_section">
> називай більш зрозуміло, повною назвою, також якщо юзаєш БЕМ, то юзай його правильно)

Виправила.

2024-08-19 17:07 UTC, Kotelnytska commented on .rubocop.yml
> +  Enabled: false
> де саме?

В контроллері. Свариться на «local” в render "shared/under_construction" unless Rails.env.local?.

2024-08-21 08:31 UTC, loqimean approved these changes

2024-08-21 08:31 UTC, merged