920 Added seeds for categories
ita-social-projects/ZeroWaste pull request #923
Opened 2024-10-25 11:21 UTC by alexy78

### Description
Added seeds for categories.

2024-11-01 08:04 UTC, DanielVajnagi approved these changes

2024-11-04 09:51 UTC, loqimean requested changes

2024-11-04 09:51 UTC, loqimean commented on db/seeds.rb
> +])
винеси ці дані в якийсь yml файл і вже звідти будеш то тягнути

2024-11-04 09:51 UTC, loqimean commented on db/seeds.rb
> +end
а цей метод тоді буде не потрібен

2024-11-09 09:47 UTC, loqimean requested changes

2024-11-09 09:47 UTC, loqimean commented on db/data/categories.yml
> +      - {period_start: 1,  period_end: 3,  usage_amount: 10, price: 11.41}
що це таке?) давай гарно ямлом опиши

2024-11-09 09:47 UTC, loqimean commented on db/data/categories.yml
> +      - {period_start: 13, period_end: 18, usage_amount: 4,  price: 6.45}
і так скрізь

2024-11-09 09:47 UTC, loqimean commented on db/seeds.rb
> +categories_data = YAML.load_file(Rails.root.join("db", "data", "categories.yml"))
```suggestion
categories_data = YAML.load_file(Rails.root.join("db", "data", "categories.yml"))

```

2024-11-09 09:47 UTC, loqimean commented on db/seeds.rb
> +  en_name, uk_name, priority, periods = args
не бачу сенсу в цьому

2024-11-09 09:47 UTC, loqimean commented on db/seeds.rb
> +  return if Category.exists?(en_name: en_name)
```suggestion
  return if Category.exists?(en_name: args[:en_name])
```

2024-11-09 09:47 UTC, loqimean commented on db/seeds.rb
> +  periods.each { |period| DiapersPeriod.create!(period.merge(category: category)) }
зроби так, щоб це була одна строка, там є щось типу insert, чи типу того. Потрібно не додатково ітеруватися, а правильно зложити YML хеш, який конвертнеться в хеш, котрий буде інсертнутий в БД

2024-11-09 09:47 UTC, loqimean commented on db/seeds.rb
> +end
думаю можна обійтися без метода, бо цей код не є реюзабельний

2024-11-26 17:11 UTC, loqimean approved these changes

2024-11-26 17:33 UTC, merged