910 Created menstrual hygiene calculato
ita-social-projects/ZeroWaste pull request #924
Opened 2024-10-27 11:32 UTC by SleekMutt

resolves #910 

## Code reviewers

- [ ] @loqimean 

## Summary of issue

Create menstrual hygiene calculator to display 4 calculations: 
1. how many disposable menstrual products have been used since the onset of menstruation until the current age
2. how much money has already been spent on disposable menstrual products from the time of menstruation to the current age
3. how much more menstrual products can be used from the current age to the expected age of menopause
4. how much money can still be spent on menstrual products from the current age to the expected age of menopause

## Summary of change

-Created api controller and action to the existing controller
-Created service to calculate mentioned indicators 
-Created validations to filter invalid values
-Created stimulus controller to the calculator view
-Created view with the calculator 
-Created tests to test calculations

https://github.com/user-attachments/assets/ab50c980-2d3e-405e-b38a-09a96d38f7ca

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-05 07:52 UTC, loqimean requested changes

2024-11-05 07:52 UTC, loqimean commented on app/controllers/calculators_controller.rb
> +    render "calculators/mhc_calculator"
а це навіщо? рельса і так знає, що тре зарендерити)

2024-11-05 07:52 UTC, loqimean commented on app/views/layouts/_mhc_description_block.html.slim
> +            information_link: It.link("https://docs.google.com/document/d/1xu6cch-Ner9OEpU4_TV5suIUsuVcWpgiUuX6QrOgaL4/edit",
а що це за документ?

2024-11-05 07:52 UTC, loqimean commented on app/views/layouts/_mhc_description_button.html.slim
> +  = it "layouts.description_button.use_less",
що це за `it`?)

2024-11-05 14:58 UTC, SleekMutt commented on app/views/layouts/_mhc_description_block.html.slim
> +            information_link: It.link("https://docs.google.com/document/d/1xu6cch-Ner9OEpU4_TV5suIUsuVcWpgiUuX6QrOgaL4/edit",
https://docs.google.com/document/d/1q37RP0wfgcHJJxWo49dYbMhc1sPvUVqe/edit

В кінці написано, що треба додати до тексту посилання на цей документ

2024-11-05 15:01 UTC, SleekMutt commented on app/views/layouts/_mhc_description_button.html.slim
> +  = it "layouts.description_button.use_less",
локалізація

2024-11-14 18:08 UTC, loqimean approved these changes

2024-11-15 08:17 UTC, loqimean approved these changes

2024-11-15 09:37 UTC, loqimean requested changes

2024-11-15 09:37 UTC, loqimean commented on app/validators/mhc_calculator_validator.rb
стоп, а де тести на валіадтор?

2024-11-15 09:37 UTC, loqimean commented on app/validators/mhc_calculator_validator.rb
весь рубішний код має бути покритий тестами

2024-11-15 10:29 UTC, loqimean requested changes

2024-11-15 10:29 UTC, loqimean commented on spec/validators/mhc_calculator_validator_spec.rb
> +        invalid_params = valid_params.except(:user_age)
НІКОЛИ так не пиши, у нас для цього є `let`, я ж і не раз вже казав

2024-11-15 10:29 UTC, loqimean commented on spec/validators/mhc_calculator_validator_spec.rb
не всі методи покриті тестами

2024-11-15 12:10 UTC, loqimean requested changes

2024-11-15 12:10 UTC, loqimean commented on spec/validators/mhc_calculator_validator_spec.rb
> +    shared_examples "a presence validation" do |attribute|
шерид екземпли повинні бути в папці support

2024-11-15 12:10 UTC, loqimean commented on spec/validators/mhc_calculator_validator_spec.rb
> +        validator = described_class.new(invalid_params)
а це так і не пофіксав

2024-11-15 13:54 UTC, loqimean requested changes

2024-11-15 13:54 UTC, loqimean commented on spec/support/shared/presence_validation_example.rb
> +    validator.params[attribute] = nil
для цього використовуй before хук

2024-11-18 06:44 UTC, loqimean approved these changes

2024-11-18 15:01 UTC, merged