799 fix error pages
ita-social-projects/ZeroWaste pull request #926
Opened 2024-10-29 11:25 UTC by igorSimash

Resolves: https://github.com/ita-social-projects/ZeroWaste/issues/799

## Code reviewers

- [ ] @loqimean

## Summary of issue

- Product page is opened after linking with incorrect product ID in URL
- There is no custom 404, 422 & 500 error pages.

## Summary of change

- Added custom 404, 422 & 500 error pages.

![image](https://github.com/user-attachments/assets/7d408513-33b8-4b89-8703-73bd893e3aaf)

![image](https://github.com/user-attachments/assets/350169b7-f4c0-4d5a-b747-d0d2b5eaf4c4)

![image](https://github.com/user-attachments/assets/4fe1430d-6971-4b72-8fc1-51e6eb6914a8)

- Added 404 page display when there is no record with given ID (for whole app)

![image](https://github.com/user-attachments/assets/c2ae51f6-eb53-4e8c-a38e-caa156a7870a)

![image](https://github.com/user-attachments/assets/75457f2b-6ecf-4b38-bc6e-49d1f5b63151)

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-10-31 11:57 UTC, DanielVajnagi approved these changes

2024-11-05 07:27 UTC, loqimean commented
1. self review is not completed
2. show number of error for user, as large number
3. these long text should be in two lines
4. use white, or might be green color

2024-11-09 10:04 UTC, loqimean requested changes

2024-11-09 10:04 UTC, loqimean commented on app/views/errors/internal_server.html.erb
> +  <p class="px-8 text-lg"><%= t('500_page.description') %></p>
компоненти

2024-11-09 10:04 UTC, loqimean commented on app/views/errors/not_found.html.erb
> +<section class="mx-auto space-y-4 text-center rounded-lg py-36 bg-white/10 text-success backdrop-blur-md max-w-1230">
от класи повторюються

2024-11-27 11:12 UTC, loqimean approved these changes

2024-11-27 11:12 UTC, merged