fix  'Calculator' page reverting after changing locale
ita-social-projects/ZeroWaste pull request #928
Opened 2024-10-30 12:07 UTC by NVMakarenko

dev
## PROJECT

[Board ticket](https://github.com/orgs/ita-social-projects/projects/25/views/7?pane=issue&itemId=59388724&issue=ita-social-projects%7CZeroWaste%7C866)

## Code reviewers

- [ ] @loqimean 

## Summary of issue

New calculator is not creating because of validation failed. Error message is shown. If change locale on this stage, admin will be redirected to Calculator's page.
**Expected result**
'New calculator' page is reload and displayed.
'Name' field is blank.
Error message is absent.

## Summary of change

1. add hidden field into calculator form.
2. change link to locale by checking if we were on new page.

## CHECK LIST
- [x]  СI passed
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [x]  I've checked new feature as logged in user
- [ ]  PR meets all conventions

2024-11-05 07:44 UTC, loqimean requested changes

2024-11-05 07:44 UTC, loqimean commented on app/views/account/calculators/new.html.erb
> +    <%= hidden_field_tag :rendered_from, "new" %>
не гуд, таких форм у тебе рахуй 10 і на кожну потрібна перевірка?) не гуд, шукай інший солюшен, більш лайтовий

2024-11-07 18:06 UTC, KseniaGovorun approved these changes

2024-11-07 18:08 UTC, KseniaGovorun requested changes
Fix ci

2024-11-08 06:17 UTC, KseniaGovorun approved these changes

2024-11-08 17:51 UTC, loqimean requested changes

2024-11-08 17:51 UTC, loqimean commented on app/views/account/calculators/create.turbo_stream.erb
> +<div data-controller="redirect" data-url="<%= account_calculators_path %>"></div>
```ruby
turbo_stream.append :body_js do
  <script>
    window.location.replace("<%= account_calculators_path %>")
  </script>
end
```

2024-11-08 17:51 UTC, loqimean commented on app/views/account/calculators/new.turbo_stream.erb
> +<%= turbo_stream.replace(dom_id(@calculator, :form), partial: "account/calculators/partials/new/form", locals: {calculator: @calculator}) %>
```suggestion
<%= turbo_stream.replace(dom_id(@calculator, :form), partial: "account/calculators/partials/new/form", locals: { calculator: @calculator }) %>

```

2024-11-08 17:51 UTC, loqimean commented on app/javascript/controllers/redirect_controller.js
а це можна видаляти

2024-11-19 10:48 UTC, loqimean approved these changes

2024-12-09 09:08 UTC, merged