Update Ruby on Rails to 7.2.0
ita-social-projects/ZeroWaste pull request #929
Opened 2024-10-30 13:33 UTC by KseniaGovorun

2024-11-05 07:36 UTC, loqimean requested changes
зкооперуйся з Іванною Амброзяк, разом гляньте до цього ПРа, до її, аби все гарно зробити

2024-11-05 07:36 UTC, loqimean commented on config/environments/development.rb
> -  config.action_mailer.perform_deliveries = true
а чому цей конфіг видалений?

2024-11-05 07:36 UTC, loqimean commented on config/environments/production.rb
> -  }
чому цей конфіг видалений?

2024-11-05 07:36 UTC, loqimean commented on config/environments/production.rb
> +  config.force_ssl = true
а чому це додала?

2024-11-05 07:36 UTC, loqimean commented on config/initializers/new_framework_defaults_7_2.rb
тут же пише, що цей файл має бути видалений. Також я хотів би, аби максимальний розмір лог файла, з цього файла, був винесений в конфігурацію

2024-11-05 07:36 UTC, loqimean commented on public/icon.png
нам цього не потрібно

2024-11-05 07:36 UTC, loqimean commented on db/migrate/20241030095709_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb
а нам ця міграція потрібна?

2024-11-05 07:36 UTC, loqimean commented on db/migrate/20241030095707_add_service_name_to_active_storage_blobs.active_storage.rb
також всі ці інші міграції?

2024-11-09 09:55 UTC, loqimean requested changes

2024-11-09 09:55 UTC, loqimean commented on spec/lib/users_csv_generator_spec.rb
> +  let(:time_login) { Time.new(2020, 0o1, 0o1).in_time_zone("Europe/Kyiv") }
```suggestion
  let(:time_login) { Time.new(2020, 0o1, 0o1) }
```

2024-11-09 09:55 UTC, loqimean commented on config/application.rb
> +    # config.time_zone = "Central Time (US & Canada)"
де таймзона?)))

2024-11-09 09:55 UTC, loqimean commented on config/application.rb
> -    config.i18n.load_path += Dir[Rails.root.join("config", "locales", "**", "*.{rb,yml}")]
а це чому видалила?

2024-11-09 09:55 UTC, loqimean commented on config/environments/production.rb
> -  config.public_file_server.enabled = ENV["RAILS_SERVE_STATIC_FILES"].present?
а це чому видалила?

2024-11-09 09:55 UTC, loqimean commented on config/environments/production.rb
> -  config.active_support.deprecation = :notify
повертай

2024-11-09 09:55 UTC, loqimean commented on config/environments/production.rb
> -  config.active_support.disallowed_deprecation = :log
те ж саме

2024-11-09 09:55 UTC, loqimean commented on config/environments/production.rb
> -  config.log_formatter = ::Logger::Formatter.new
те ж саме

2024-11-09 09:55 UTC, loqimean commented on config/environments/test.rb
> +  config.enable_reloading = false
а це ще чому??

2024-11-09 09:55 UTC, loqimean commented on config/environments/test.rb
> -  config.active_job.queue_adapter = :test
а це чому видалила?

2024-11-09 09:55 UTC, loqimean commented on config/initializers/assets.rb
> -Rails.application.config.assets.precompile += ["turbo-streams.js", "bootstrap.min.js", "popper.js", "toastify-js"]
а нам цього точно не потрібно?

2024-11-09 09:55 UTC, loqimean commented on config/puma.rb
> -worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"
а де цей конфіг?

2024-11-09 09:55 UTC, loqimean commented on config/puma.rb
> -min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
чому нема мінімального каунту?

2024-11-26 10:17 UTC, loqimean requested changes

2024-11-26 10:17 UTC, loqimean commented on config/environments/production.rb
> +                                       .then { |logger| ActiveSupport::TaggedLogging.new(logger) }
це не гуд взагалі, глянь, як було, раніше була умова на цей конфіг

2024-11-26 15:12 UTC, loqimean approved these changes

2024-11-26 16:11 UTC, olexandervanzuriak approved these changes

2024-12-01 12:49 UTC, loqimean requested changes

2024-12-01 12:49 UTC, loqimean commented on Gemfile
> +  gem "rubocop-capybara"
require false

2024-12-01 12:49 UTC, loqimean commented on config/environments/test.rb
>    config.action_dispatch.show_exceptions = :none
через цю штуку тести падають

2024-12-02 13:30 UTC, loqimean approved these changes

2024-12-16 20:31 UTC, merged