931 fix selflock bug
ita-social-projects/ZeroWaste pull request #937
Opened 2024-11-03 01:46 UTC by DanielVajnagi

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

Admin can ban himself 

## Summary of change

Removed this function

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-04 12:01 UTC, alexy78 approved these changes

2024-11-05 07:39 UTC, loqimean requested changes

2024-11-05 07:39 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +    end
1. біфор екшин, ну я ж казав
2. навіщо перевіряти, чи користувач заблокований, чи ні? просто якщо юзер з парамсів - адмін, то редірект і заборона

2024-11-06 17:37 UTC, DanielVajnagi commented on app/controllers/account/users_controller.rb
> +    end
пофіксав

2024-11-07 08:59 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      redirect_to account_user_path(id: @user)
```suggestion
    @user = resource

    if params.dig(:user, :blocked) && @user.admin?
      flash[:alert] = t("errors.messages.blocked_user_cannot_be_admin")

      redirect_to account_user_path(@user)
```

2024-11-07 08:59 UTC, loqimean commented on app/controllers/account/users_controller.rb
> +      redirect_to account_user_path(id: @user)
guard style return

2024-11-09 10:03 UTC, loqimean approved these changes

2024-11-09 10:31 UTC, merged