Base setup
ita-social-projects/ZeroWaste pull request #943
Opened 2024-11-07 19:06 UTC by ktpe

dev
## GitHub Board

* [calculators constructor ticket](https://github.com/ita-social-projects/ZeroWaste/issues/359)

## Code reviewers

- [ ] @loqimean 

### Second Level Review

- [ ] @NVMakarenko @igorSimash @SleekMutt 

## Summary of issue

to create a foundation for the calculator builder.

## Summary of change

the addition of models, updating of the controller, updating of new.html, and creation of new _partials were implemented. Additionally, the cocoon gem was added to enable working with multiple calculator fields.

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-09 09:09 UTC, loqimean requested changes

2024-11-09 09:09 UTC, loqimean commented on app/models/calculator.rb
> +  has_many :formulas, dependent: :destroy
```suggestion
  has_many :formulas, dependent: :destroy

```

2024-11-09 09:09 UTC, loqimean commented on app/models/category.rb
> -  scope :unsigned_categories, ->(product) { where.not(id: product.categories_by_prices) }
а чому це видалили?)

2024-11-09 09:09 UTC, loqimean commented on app/models/field.rb
> +  accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true
```suggestion

  has_many :categories, dependent: :destroy

  accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true
```

2024-11-09 09:09 UTC, loqimean commented on app/models/field.rb
> -  validates :type, :kind, :label, presence: true
те ж саме

2024-11-09 09:09 UTC, loqimean commented on app/views/account/calculators/partials/_category_fields.html.erb
> +  <%= f.input :price, label: "Category Price:" %>
```suggestion
  <%= f.input :price, label: "Category Price:" %>

```

2024-11-09 09:09 UTC, loqimean commented on app/views/account/calculators/partials/_category_fields.html.erb
> +  <%= link_to_remove_association "-Remove Category", f, class: "text-red-500 underline" %>
```suggestion
  <%= link_to_remove_association "- Remove Category", f, class: "text-red-500 underline" %>
```

2024-11-09 09:09 UTC, loqimean commented on app/views/account/calculators/partials/_field_fields.html.erb
> +      collection: [["Number", "number"], ["Category", "category"]],
це в константу модельки філдів винеси

2024-11-09 09:09 UTC, loqimean commented on app/views/account/calculators/partials/_field_fields.html.erb
> +     class: "underline" %>
```suggestion
    <%= link_to_add_association "+Add Category", f, :categories, partial: "account/calculators/partials/category_fields",  class: "underline" %>
```

2024-11-09 09:09 UTC, loqimean commented on app/views/account/calculators/partials/_form.html.erb
> +         class: "underline" %>
те ж саме

2024-11-09 09:09 UTC, loqimean commented on app/views/account/calculators/partials/_form.html.erb
> +<% end %>
```suggestion
<% end %>

```

2024-11-09 09:09 UTC, loqimean commented on app/views/account/calculators/partials/_formula_fields.html.erb
> +</div>
```suggestion

  <%= link_to_remove_association "-Remove Formula", f, class: "text-red-500 underline" %>
</div>

```

2024-11-09 09:09 UTC, loqimean commented on config/database.yml.sample
а це ще що таке?? повертай

2024-11-09 09:09 UTC, loqimean commented on db/migrate/20210524103702_change_calculators.rb
повертай

2024-11-09 09:09 UTC, loqimean commented on db/migrate/20241107134610_create_formulas.rb
> +      t.string :en_label, null: false
бажано би без дефолт велʼю, але якщо тре, то чому не скрізь тре?)

2024-11-09 09:09 UTC, loqimean commented on db/migrate/20241107134610_create_formulas.rb
> +      t.string :en_unit
а ці поля звідки взялися і навіщо вони?)

2024-11-09 09:09 UTC, loqimean commented on db/migrate/20241107135318_change_fields.rb
> +    add_column :fields, :field_type, :string, null: false, default: ""
change_table bulk: true

2024-11-09 09:09 UTC, loqimean commented on db/migrate/20241107140542_change_categories.rb
> +    remove_columns :categories, :priority, :preferable
пріоріті тре, най буде

2024-11-10 09:15 UTC, ktpe commented on app/models/calculator.rb
> +  has_many :formulas, dependent: :destroy
fixed

2024-11-10 09:16 UTC, ktpe commented on app/models/category.rb
> -  scope :unsigned_categories, ->(product) { where.not(id: product.categories_by_prices) }
повернули
але видаляли бо не до кінця було зрозуміло чи потрібен був ций код для реалізації конструктора

2024-11-10 09:16 UTC, ktpe commented on app/models/field.rb
> +  accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true
fixed

2024-11-10 09:18 UTC, ktpe commented on app/models/field.rb
> -  validates :type, :kind, :label, presence: true
повернули

2024-11-10 09:18 UTC, ktpe commented on app/views/account/calculators/partials/_field_fields.html.erb
> +      collection: [["Number", "number"], ["Category", "category"]],
done

2024-11-10 09:19 UTC, ktpe commented on config/database.yml.sample
fixed

2024-11-10 09:19 UTC, ktpe commented on db/migrate/20210524103702_change_calculators.rb
fixed

2024-11-10 09:20 UTC, ktpe commented on db/migrate/20241107134610_create_formulas.rb
> +      t.string :en_label, null: false
ага, додали і для :en_label

2024-11-10 09:20 UTC, ktpe commented on db/migrate/20241107134610_create_formulas.rb
> +      t.string :en_unit
а це потрібно для дайперс калькулятора
ці поля будуть використані там у наступних гілках

2024-11-10 09:20 UTC, ktpe commented on db/migrate/20241107135318_change_fields.rb
> +    add_column :fields, :field_type, :string, null: false, default: ""
fixed

2024-11-10 09:21 UTC, ktpe commented on db/migrate/20241107140542_change_categories.rb
> +    remove_columns :categories, :priority, :preferable
прибрав

2024-11-10 10:06 UTC, loqimean requested changes

2024-11-10 10:06 UTC, loqimean commented on app/models/field.rb
> +  FIELD_TYPES = [
Роби хешом, а ще тре конвертнеш в масив

2024-11-10 10:06 UTC, loqimean commented on app/views/account/calculators/partials/_form.html.erb
> +    <div id="formulas" class="space-y-4">
Щось тут не гуд по ідентецшинам

2024-11-10 10:06 UTC, loqimean commented on config/database.yml.sample
> +#   password: <%= ENV['ZERO_WASTE_DATABASE_PASSWORD'] %>
Нова строка

2024-11-10 10:06 UTC, loqimean commented on db/migrate/20241107134610_create_formulas.rb
> +      t.string :en_unit
Не бачив їх, якщо ти про майбутнє, то давай в майбутньому і додамо

2024-11-10 10:06 UTC, loqimean commented on db/migrate/20241107140542_change_categories.rb
> +      t.float :price, null: false, default: 0.0
Завжди для ціни юзай BigDecimal, чи то Decimal. Загугли

2024-11-10 10:06 UTC, loqimean commented on spec/features/account/create_calculator_spec.rb
Видали, якщо не тре

2024-11-10 10:06 UTC, loqimean commented on spec/features/account/update_calculator_spec.rb
Теж

2024-11-10 10:33 UTC, ktpe commented on db/migrate/20241107140542_change_categories.rb
> +      t.float :price, null: false, default: 0.0
зробив через decimal
пишуть що BigDecimal вже буде юзатись у рубі коді, не в міграціях

2024-11-10 10:40 UTC, loqimean approved these changes

2024-11-10 10:40 UTC, loqimean commented on .vscode/settings.json
видаляй)

2024-11-10 10:40 UTC, loqimean commented on app/models/field.rb
> +  # enum :kind, { form: 0, parameter: 1, result: 2 }
kind,  FIELD_TYPES

2024-11-10 10:40 UTC, loqimean commented on app/views/account/calculators/partials/_form.html.erb
> +    <div id="formulas" class="space-y-4">
досі не гуд

2024-11-13 08:38 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +    @calculator = Calculator.new
тести)

2024-11-13 08:40 UTC, loqimean commented on app/models/category.rb
> +  validates :en_name,
а чому нема укр назви?) також транслейтабл?)

2024-11-13 08:40 UTC, loqimean commented on app/models/field.rb
> +  enum :kind, { number: 0, category: 1 }
юзайте текстові велєю + константи на ті велʼю

2024-11-13 08:40 UTC, loqimean commented on app/models/field.rb
> +  accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true
це має бути в самому низу

2024-11-13 08:42 UTC, loqimean commented on app/views/account/calculators/partials/_field_fields.html.erb
> +    input_html: { data: { field_type_target: "fieldTypeSelect" } } %>
```suggestion
  <%= f.input(
        :kind, 
        collection: Field.kinds.map { |k, _| [k.humanize, k] },
        prompt: "Select Field Type",
        label: "Field Type:",
        input_html: { data: { field_type_target: "fieldTypeSelect" }}
      ) %>
```

2024-12-08 10:33 UTC, closed without merging