Show calculator
ita-social-projects/ZeroWaste pull request #946
Opened 2024-11-08 16:34 UTC by NVMakarenko

dev
## Project

* [Project](https://github.com/ita-social-projects/ZeroWaste/issues/359)

## Code reviewers

- [ ] @loqimean 

## Summary of issue

If Admin created calculator via constructor, User chould see it.

## Summary of change

- [X] add show page for user
- [X] add routes

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-08 16:46 UTC, NVMakarenko commented on app/views/calculators/show.html.erb
![image](https://github.com/user-attachments/assets/9eb91561-f273-4977-ba59-906e5436d456)

2024-11-10 09:35 UTC, ktpe approved these changes

2024-11-10 10:37 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +    @calculator = Calculator.find(params[:slug])
тестів нема + юзай ресурс

2024-11-10 10:37 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +    @calculator = Calculator.find(params[:slug])
не дуже розумію, що це за результат з парамсів?

2024-11-10 10:37 UTC, loqimean commented on app/views/account/calculators/index.html.erb
> +          <td><%= calculator.en_name %></td>
```suggestion
          <td><%= calculator.name %></td>
```

2024-11-10 10:37 UTC, loqimean commented on app/views/calculators/show.html.erb
в опис ПРа потрібно додавати скріни

2024-11-10 10:37 UTC, loqimean commented on app/views/calculators/show.html.erb
> +  <%= form_with url: calculate_account_calculator_path(slug: @calculator.slug || @calculator.id) do |form| %>
```suggestion
  <%= form_with url: calculate_account_calculator_path(@calculator) do |form| %>

```

2024-11-10 11:13 UTC, NVMakarenko commented on app/controllers/account/calculators_controller.rb
> +    @calculator = Calculator.find(params[:slug])
SEO-friendly урла залишена з попердньої реалізації.

2024-11-10 16:43 UTC, loqimean requested changes

2024-11-10 16:43 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +    @calculator = Calculator.find(params[:slug])
що це ще таке?? ну Наталя, як ми юзаємо ресурс?

2024-11-10 16:43 UTC, loqimean commented on app/models/calculator.rb
> +  end
https://github.com/ita-social-projects/ZeroWaste/blob/master/app/models/concerns/translatable.rb

2024-11-10 16:43 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +    @calculator = Calculator.find(params[:slug])
я і не казав забирати слаг

2024-12-01 12:23 UTC, loqimean requested changes

2024-12-01 12:23 UTC, loqimean commented on app/controllers/calculators_controller.rb
> +    collection.find(params[:slug])
а чому шукає слаг, але скоуп френдлі видаляється?

2024-12-01 12:23 UTC, loqimean commented on app/controllers/account/calculators_controller.rb
> +  before_action :resource, only: [:edit, :update, :destroy]
видали цей біфор екшин

2024-12-01 12:23 UTC, loqimean commented on spec/features/show_calculator_spec.rb
> +      get :show, params: { slug: calculator.slug, locale: :en }
```suggestion
      get :show, params: { slug: calculator.slug, locale: :en }

```

2024-12-01 12:23 UTC, loqimean commented on spec/features/show_calculator_spec.rb
> +      get :show, params: { slug: calculator.slug, locale: :en }
і так скрізь. розділяй дії та експектейшини

2024-12-01 12:24 UTC, loqimean commented
порізолвай конфлікти

2024-12-09 09:24 UTC, NVMakarenko commented
This functionality is moved to [calculators-constructor branch](https://github.com/ita-social-projects/ZeroWaste/tree/calculators-constructor) and is developing there.

2024-12-09 09:24 UTC, closed without merging