Constructors validations
ita-social-projects/ZeroWaste pull request #948
Opened 2024-11-08 17:32 UTC by SleekMutt

part of: https://github.com/ita-social-projects/ZeroWaste/issues/359

## Code reviewers

- [ ] @loqimean 

### Second Level Review

- [ ] @NVMakarenko 
- [ ] @ktpe
- [ ] @igorSimash

## Summary of issue

There is no validations for constructors models

## Summary of change

Created new validations for formula and field models

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-09 09:21 UTC, loqimean requested changes

2024-11-09 09:21 UTC, loqimean commented on app/validators/field_validator.rb
> +    record.errors.add(:var_name, "field isn't used in any formula")
юзай локалізацію, думаю передай тут символ та додай переклад ключа в локалях

2024-11-09 09:21 UTC, loqimean commented on app/validators/field_validator.rb
> +      formula.expression.scan(/\b[a-zA-Z_]\w*\b/).uniq.include?(record.var_name)
винеси регексп в константу

2024-11-09 09:21 UTC, loqimean commented on app/validators/formula_validator.rb
> +    formula_variables = record.expression.scan(/\b[a-zA-Z_]\w*\b/).uniq
теж в константу

2024-11-09 09:21 UTC, loqimean commented on app/validators/formula_validator.rb
> +    record.errors.add(:expression, "requires fields #{unused_fields.join(', ')} to be initialized")
теж локалізація

2024-11-09 09:21 UTC, loqimean commented on app/validators/formula_validator.rb
> +    field_names = record.calculator.fields.map(&:var_name)
`.pluck`

2024-11-09 09:21 UTC, loqimean commented on app/validators/field_validator.rb
де тести, Лебовськи?)

2024-11-09 17:33 UTC, SleekMutt commented on app/validators/formula_validator.rb
> +    field_names = record.calculator.fields.map(&:var_name)
Працює лиш з рекордами. які в бд збережені

2024-11-09 17:33 UTC, SleekMutt commented on app/validators/field_validator.rb
додав

2024-11-09 21:01 UTC, NVMakarenko approved these changes

2024-11-10 09:35 UTC, ktpe approved these changes

2024-11-10 10:49 UTC, loqimean commented on spec/models/formula_spec.rb
> +      calculator.fields.build(var_name: "b")
before do end

2024-11-10 10:49 UTC, loqimean commented on spec/models/field_spec.rb
> +      calculator.formulas.build(expression: "a + b")
before

2024-12-01 12:26 UTC, loqimean reviewed
1. темплейт не заповнений
2. перший левел - ревʼю тіми (не проведений)
3. евіденсів нема

2024-12-01 12:26 UTC, loqimean commented on app/views/account/calculators/partials/_form.html.erb
> +        <%= f.error_notification message: f.object.errors[:formulas].to_sentence if f.object.errors[:formulas].present? %>
навіщо це? точно потрібно? також де скріншот, як це виглядає?

2024-12-01 12:27 UTC, loqimean requested changes
коменти написав вище

2024-12-08 10:33 UTC, closed without merging