Added flipper, so admin could enable or disable mhc calculator
ita-social-projects/ZeroWaste pull request #969
Opened 2024-11-22 16:31 UTC by SleekMutt

https://github.com/user-attachments/assets/04767cb4-f27d-416d-b335-c6c515cbc560

## Code reviewers

- [ ] @loqimean 

## Summary of issue

There is no feature flipper for the mhc calculator

## Summary of change

Added feature flipper for the mhc calculator

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-22 17:33 UTC, ktpe approved these changes

2024-11-22 21:19 UTC, loqimean requested changes

2024-11-22 21:19 UTC, loqimean commented on app/controllers/calculators_controller.rb
> +    raise ActionController::RoutingError, "Mhc calculator flipper is disabled" unless Flipper[:mhc_calculator_status].enabled?
404 має бути

2024-11-22 21:19 UTC, loqimean commented on app/controllers/calculators_controller.rb
> +    raise ActionController::RoutingError, "Mhc calculator flipper is disabled" unless Flipper[:mhc_calculator_status].enabled?
і краще спочатку умову мати з ретурном, а вже знизу от наприклад редірект, чи рейзання ерори, чи ще щось

2024-11-24 10:25 UTC, loqimean approved these changes

2024-11-24 10:46 UTC, merged