976 redirect to calculator page after creation
ita-social-projects/ZeroWaste pull request #980
Opened 2024-11-26 10:37 UTC by DanielVajnagi

## Code reviewers

- [ ] @ktpe 

### Second Level Review

- [ ] @loqimean 

## Summary of issue

After creation, the program should transfer to the page of this calculator in the admin panel

## Summary of change

Created show page for calculator on admin, added redirect

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-26 13:51 UTC, ktpe approved these changes

2024-11-26 15:19 UTC, loqimean requested changes

2024-11-26 15:19 UTC, loqimean commented on spec/requests/calculators_spec.rb
> +        calculator = Calculator.last
Ну що це таке? Я вже не один раз казав, що ми НІКОЛИ не використовуємо змінні у тестах

2024-11-26 17:44 UTC, loqimean commented on spec/requests/calculators_spec.rb
> +        expect(response).to redirect_to(account_calculator_path(slug: Calculator.last))
use let for last calculator

2024-12-01 12:15 UTC, loqimean approved these changes

2024-12-01 12:15 UTC, loqimean requested changes
порізолвай конфлікти

2024-12-04 00:11 UTC, loqimean approved these changes

2024-12-04 00:19 UTC, merged