Upload the calculator logo
ita-social-projects/ZeroWaste pull request #982
Opened 2024-11-26 14:49 UTC by KseniaGovorun

dev
* Project ticket #970 

## Code reviewers

- [ ] @loqimean  

## Summary of issue

The user should be able to upload the calculator logo

## Summary of change

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-12-11 18:54 UTC, NVMakarenko approved these changes

2025-01-20 10:28 UTC, loqimean requested changes

2025-01-20 10:28 UTC, loqimean commented on app/views/calculators/partials/_logo_picture.html.erb
> +  <%= image_tag(@calculator.logo_picture.variant(resize_to_fill: [428, 307])) %>
use constant for this dimension definition

2025-01-20 10:28 UTC, loqimean commented on app/views/calculators/show.html.erb
> +    <% end %>
move logic to get default, or attached image to model

2025-02-25 16:19 UTC, loqimean requested changes

2025-02-25 16:19 UTC, loqimean commented on app/views/account/calculators/partials/_form.html.erb
> +        <%= f.file_field :logo_picture, accept: "image/jpeg, image/png", class: "file-input mb-3" %>
це тре в константу винести, а ще краще заюзати якусь готову константу, щось таке має бути, бо тут не вистачає як мінімум ще одного типу картинки, наче jpg

2025-02-25 16:19 UTC, loqimean commented on app/views/calculators/partials/_logo_picture.html.erb
> +  <%= image_tag(@calculator.logo_placeholder) %>
підрефактори цей код, винеси в хелпер, або навіть з модельки має бути визначення, яку картинку тягнути. Я б хотів бачити щось таке:
```ruby
  <%= image_tag(@calculator.logo, class: "w-64 h-40 rounded shadow") %>
```

2025-02-25 16:19 UTC, loqimean commented on app/views/calculators/show.html.erb
> +    <%= image_tag @calculator.logo_url, class: "constructor-calculator-scales", alt: t(".image_alt") %>
а чому на адмінці один спосіб відображення, а тут інший?

2025-02-25 16:19 UTC, loqimean commented on spec/models/calculator_spec.rb
> +        logo_image = fixture_file_upload(Rails.root.join("spec", "fixtures", "icons", "favicon-181x182.png"), "image/png")
юзайте `let`, ну камон)

2025-02-26 18:18 UTC, olexandervanzuriak commented on app/views/account/calculators/partials/_form.html.erb
> +        <%= f.file_field :logo_picture, accept: "image/jpeg, image/png", class: "file-input mb-3" %>
Додав ALLOWED_LOGO_IMAGE_TYPES константу в Calculator model

2025-02-26 18:20 UTC, olexandervanzuriak commented on app/views/calculators/partials/_logo_picture.html.erb
> +  <%= image_tag(@calculator.logo_placeholder) %>
Використав @caclulator.logo_url який повертає або дефолтну картинку або картинку калькулятора

2025-02-26 18:20 UTC, olexandervanzuriak commented on app/views/calculators/show.html.erb
> +    <%= image_tag @calculator.logo_url, class: "constructor-calculator-scales", alt: t(".image_alt") %>
Зробив на адмінці такий самий спосіб

2025-02-26 18:20 UTC, olexandervanzuriak commented on spec/models/calculator_spec.rb
> +        logo_image = fixture_file_upload(Rails.root.join("spec", "fixtures", "icons", "favicon-181x182.png"), "image/png")
Використав let

2025-03-05 14:40 UTC, loqimean approved these changes

2025-03-05 14:40 UTC, merged