Style calculators constructor show page
ita-social-projects/ZeroWaste pull request #984
Opened 2024-11-26 15:54 UTC by olexandervanzuriak

#963 

## Code reviewers

- [ ] @loqimean 

## Summary of issue

 All calculators should be in the same style as the diaper and menstrual hygiene calculator

- the same colors by default
- the same font by default

![image](https://github.com/user-attachments/assets/7e709ddb-4cee-42eb-b34e-091d4ecdaaf0)

## Result

https://github.com/user-attachments/assets/445a1385-56ca-46e5-8b0e-b61ca82268b9

## Testing approach

Tested locally

## CHECK LIST
- [x]  СI passed
- [x]  Сode coverage >=95%
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [x]  I've checked new feature as logged in and logged out user if needed
- [x]  PR meets all conventions

2024-11-27 14:30 UTC, loqimean requested changes

2024-11-27 14:30 UTC, loqimean commented on app/views/calculators/show.html.erb
> +<% color = "blue" %>
колір має передаватися хексом

2024-11-27 14:30 UTC, loqimean commented on app/views/calculators/show.html.erb
> +  <h1 class="pt-6 text-2xl font-semibold text-center font-sans text-<%= color %>">Calculator <%= @calculator.name %> <%= @text %></h1>
не гуд. додай в конфіги color: { dynamic: "var(--calculator-color)" }, щось таке, тоді тут вже будеш десь зверху сетати цю змінну: `<div style="--calculator-color: <%= @calculator.color %>">`

2024-11-27 14:30 UTC, loqimean commented on config/tailwind.config.js
> +  ],
це відповідно видалиш

2024-11-27 14:30 UTC, loqimean commented on app/services/calculators/calculation_service.rb
> +  include ApplicationHelper
не гуд

2024-11-27 14:30 UTC, loqimean commented on app/services/calculators/calculation_service.rb
> +      end
тут ти можеш додати локальзацію додним рядком грубо кажучи:
```ruby
{ label: formula.public_send("#{I18n.locale}_label") }
```

2024-11-27 14:30 UTC, loqimean commented on app/services/calculators/calculation_service.rb
> +      end
та навіть прсотіше того, бо мав би бути підключений до формули концерн транслейтебел (він сам в залежності від локалі бере потрібний переклад):
```ruby
{ label: formula.label }

2024-11-27 17:17 UTC, olexandervanzuriak commented on app/views/calculators/show.html.erb
> +<% color = "blue" %>
fix

2024-11-27 17:17 UTC, olexandervanzuriak commented on app/services/calculators/calculation_service.rb
> +      end
fix

2024-11-27 17:18 UTC, olexandervanzuriak commented on app/services/calculators/calculation_service.rb
> +  include ApplicationHelper
deleted

2024-11-28 17:28 UTC, loqimean requested changes

2024-11-29 12:29 UTC, loqimean requested changes

2024-11-29 12:29 UTC, loqimean commented on app/views/calculators/partials/show/_constructor_calculator_description.erb
> +  </div>
а чому ти всі стилі видалив? ти мав залишити весь той контейнер, просто без контенту

2024-11-29 12:29 UTC, loqimean commented on app/views/calculators/partials/_calculation_results.html.erb
> +<div style="--calculator-color: <%= color %>" class="calculation-results rounded jumbotron jumbotron-fluid position-relative">
а навіщо тут також колір передавати? він зверху передається та й все, ну на шоу пейджі

2024-11-29 12:29 UTC, loqimean commented on app/views/calculators/show.html.erb
> +  <%= image_tag "#{calculator_image}", class: "scales_img", alt: "Scales" %>
а навіщо ти в стрінгу огортаєш змінну?

2024-11-29 12:29 UTC, loqimean commented on app/views/calculators/show.html.erb
> +  <%= image_tag "#{calculator_image}", class: "scales_img", alt: "Scales" %>
alt через I18n пиши

2024-11-29 16:21 UTC, loqimean approved these changes

2024-11-29 16:23 UTC, merged