Added notes to constructor
ita-social-projects/ZeroWaste pull request #987
Opened 2024-11-28 14:59 UTC by alexy78

Resolves: 

* [950](https://github.com/orgs/ita-social-projects/projects/25/views/7?pane=issue&itemId=88730048&issue=ita-social-projects%7CZeroWaste%7C981)

## Code reviewers

- [ ] @KseniaGovorun 

### Second Level Review

- [ ] @loqimean 

## Summary of issue

The current form for the calculator does not include fields for creating additional notes. 

## Summary of change

This update introduces two new Ukrainian and English note fields in the calculator form. The changes include creating a YAML file for TinyMCE styling, adding a Stimulus controller to handle TinyMCE initialization, creating a partial for the TinyMCE form, and writing tests for the new fields.

<img width="1176" alt="Знімок екрана 2024-11-28 о 16 47 00" src="https://github.com/user-attachments/assets/974c107a-acda-406d-b8ae-2a4df275ef6b">
<img width="1127" alt="Знімок екрана 2024-11-28 о 16 47 06" src="https://github.com/user-attachments/assets/a6081fdd-0b2a-494b-9ab2-84e96ffc1422">

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-28 17:42 UTC, DanielVajnagi commented on app/models/calculator.rb
> +  validates :ukranian_additional_notes, length: { maximum: 150 }
а шо коротке таке? може довше зробити?

2024-11-28 17:42 UTC, DanielVajnagi commented on app/views/account/calculators/partials/_tinymce_form.html.erb
> +      <%= f.label :ukranian_additional_notes, "Ukrainian Additional Notes" %>
l18n?

2024-11-28 17:42 UTC, DanielVajnagi commented on app/views/account/calculators/partials/_tinymce_form.html.erb
> +      <%= f.label :english_additional_notes, "English Additional Notes" %>
то саме

2024-11-29 12:22 UTC, loqimean requested changes

2024-11-29 12:22 UTC, loqimean commented on app/javascript/controllers/tinymce_controller.js
> +
порівняй тут гарно код і винеси конфіги в getter, також юзай 2 пробіли, а не 4 і думаю можна без object assign, просто обʼєкт заюзати

2024-11-29 12:22 UTC, loqimean commented on app/models/calculator.rb
> +  validates :ukranian_additional_notes, length: { maximum: 500 }
ну диви, ти молодець, що додала валідацію, але тут не враховані теги, тобто я напишу одну букву, а довжина її буде 7 символів, бо буде огорнута в як мінімум тег `p`, отож потрібно дещо специфічну валіадацію зробити

2024-11-29 12:22 UTC, loqimean commented on app/views/account/calculators/partials/_tinymce_form.html.erb
> +      <%= f.label :english_additional_notes, "English Additional Notes" %>
локалізація

2024-12-04 00:07 UTC, loqimean requested changes

2024-12-04 00:07 UTC, loqimean commented on app/models/calculator.rb
> +              tokenizer: ->(string) { ActionController::Base.helpers.strip_tags(string).chars }
use method to do that and test it

2024-12-04 00:07 UTC, loqimean commented on app/views/account/calculators/partials/_tinymce_form.html.erb
> +  <%= tinymce_assets %>
```suggestion
<%= tinymce_assets %> 
```

2024-12-04 00:07 UTC, loqimean commented on app/views/account/calculators/partials/_tinymce_form.html.erb
> +  <%= tinymce_assets %>
align that all

2024-12-04 00:07 UTC, loqimean commented on app/views/calculators/partials/show/_constructor_calculator_description.erb
> +      <% end %>
```suggestion
      <%== calculator.notes %>
```
then you have:
uk_notes
en_notes
and Translatable concern in a model

2024-12-04 00:07 UTC, loqimean commented on config/locales/uk/uk.yml
> +        english_additional_notes: "Додаткові нотатки англійською"
у нас же нема основних нотаток)

2024-12-26 11:06 UTC, KseniaGovorun approved these changes

2025-01-02 11:19 UTC, loqimean commented on spec/models/calculator_spec.rb
> +        expect(stripped_content.length).to be == 500
```suggestion
        expect(stripped_content.length).to eq(500)
```

2025-01-02 11:19 UTC, loqimean commented on app/views/calculators/partials/show/_constructor_calculator_description.erb
> +      <%== calculator.notes %>
is there any XSS protection?

2025-01-15 13:15 UTC, loqimean commented on app/views/calculators/partials/show/_constructor_calculator_description.erb
> +      <%= sanitize(calculator.notes, tags: %w[p strong em ul li a div span img], attributes: %w[href target class src alt style]) %>
перенеси це в хелпер

2025-01-15 13:15 UTC, loqimean commented on app/views/calculators/partials/show/_constructor_calculator_description.erb
> +      <%= sanitize(calculator.notes, tags: %w[p strong em ul li a div span img], attributes: %w[href target class src alt style]) %>
і не юзай цей %, то зло

2025-01-20 10:31 UTC, loqimean commented on app/views/calculators/partials/show/_constructor_calculator_description.erb
> +      <%= sanitized_notes(calculator.notes) %>
sanitize_content

2025-01-25 12:37 UTC, loqimean commented on app/views/calculators/partials/show/_constructor_calculator_description.erb
> +      <%= sanitize_content(calculator.notes) %>
а тут норм рендериться HTML?

2025-01-25 12:55 UTC, merged