Save previous calculations of the user in the storage
ita-social-projects/ZeroWaste pull request #993
Opened 2024-11-29 13:01 UTC by SleekMutt

solves #990 

## Code reviewers

- [ ] @loqimean 

## Summary of issue

Users calculations must be saved in the storage

## Summary of change

Added feature to save previous results in the session storage

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-11-29 14:36 UTC, loqimean requested changes

2024-11-29 14:36 UTC, loqimean commented on app/controllers/calculators_controller.rb
> +    session[:calculation_results]                 ||= {}
тести))

2024-11-29 14:36 UTC, loqimean commented on app/views/calculators/show.html.erb
> +    <% if session.dig(:calculation_results, @calculator.slug)&.presence %>
```suggestion
    <% if session.dig(:calculation_results, @calculator.slug).present?%>

```

2024-12-01 12:29 UTC, loqimean requested changes

2024-12-01 12:29 UTC, loqimean commented on app/views/calculators/show.html.erb
> +      <%= render "calculators/partials/calculation_results", results: session[:calculation_results][@calculator.slug].map(&:symbolize_keys) %>
1. use `with_indifferent_access`
2. use `dig`

2024-12-01 12:29 UTC, loqimean commented
1. solve conflicts
2. request team review, as it is required

2024-12-01 12:41 UTC, ktpe approved these changes

2024-12-04 00:15 UTC, loqimean approved these changes

2024-12-04 00:15 UTC, merged