add unlighthouse scan after staging
ita-social-projects/ZeroWaste pull request #996
Opened 2024-11-30 19:11 UTC by NVMakarenko

dev
## Project

* [Display Unlighthouse reports](https://github.com/ita-social-projects/ZeroWaste/issues/991)

## Code reviewers

- [ ] @ktpe 
- [ ] @SleekMutt 
- [ ] @olexandervanzuriak 
- [ ] @KseniaGovorun 
- [ ] @DanielVajnagi 

### Second Level Review

- [ ] @loqimean 

## Summary of issue

Unlighthouse scanning should start after deployment to the stage. Reports upload as action artifacts.

## Summary of change

- Change cd.yml to scan site after staging.
- reports chould be downloaded as artifacts.
- add file to convert json report into csv file.
![image](https://github.com/user-attachments/assets/163ae820-6d7d-41c0-98b0-98172847e865)

## CHECK LIST
- [x]  СI passed
- [x]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  PR meets all conventions

2024-12-01 12:46 UTC, loqimean requested changes

2024-12-01 12:46 UTC, loqimean commented on .github/workflows/cd.yml
> +        run: npm install -g @unlighthouse/cli puppeteer
this report generation should be outside deploy action, with the same conditions, but that's another thing tather deploy

2024-12-01 12:46 UTC, loqimean commented on spec/lib/convert_json_to_csv_spec.rb
> +      ConvertJsonToCsv.perform(input_file, output_file)
before hook

2024-12-01 12:46 UTC, loqimean commented on spec/lib/convert_json_to_csv_spec.rb
> +      csv_content = CSV.read(output_file, headers: true)
use let

2024-12-01 12:46 UTC, loqimean commented on app/lib/convert_json_to_csv.rb
> +    json_data = JSON.parse(File.read(input_file))
```suggestion
    json_data = JSON.parse(File.read(input_file))

```

2024-12-01 12:46 UTC, loqimean commented on app/lib/convert_json_to_csv.rb
> +    json_data = JSON.parse(File.read(input_file))
write it as service object

2024-12-01 12:46 UTC, loqimean commented on app/lib/convert_json_to_csv.rb
> +require "csv"
that should already present

2024-12-01 12:46 UTC, loqimean commented on app/lib/convert_json_to_csv.rb
> +      json_data.each { |row| csv << row.values }
that would be fine to make link available to open

2024-12-01 12:46 UTC, loqimean commented on app/lib/convert_json_to_csv.rb
> +      json_data.each { |row| csv << row.values }
if it's possible

2024-12-01 12:46 UTC, loqimean commented on bin/convert_json_to_csv.rb
use rake task for this

2024-12-01 20:05 UTC, NVMakarenko commented on .github/workflows/scan_unlighthouse.yml
> +  workflow_dispatch:
should be changed on:
```
  workflow_run:
    workflows:
      - CD
    types:
      - completed

  pull_request:
    branches:
      - develop
      - master
    types:
      - closed

  release:
    types:
      - published
```
after all checks

2024-12-01 20:15 UTC, SleekMutt approved these changes

2024-12-04 00:24 UTC, loqimean requested changes

2024-12-04 00:24 UTC, loqimean commented on spec/services/convert_json_to_csv_service_spec.rb
> +        result = ConvertJsonToCsvService.call(input_file, output_file)
ну я ж вам і не раз казав, НІКОЛИ не пишіть локал змінні в тестах

2025-02-04 15:37 UTC, loqimean requested changes

2025-02-04 15:37 UTC, loqimean commented on spec/services/convert_json_to_csv_service_spec.rb
> +        result = service
use lets

2025-02-25 16:20 UTC, loqimean approved these changes

2025-02-25 16:20 UTC, merged