Closes #988 Add color to Calculator
ita-social-projects/ZeroWaste pull request #997
Opened 2024-12-01 22:18 UTC by DanielVajnagi

## Code reviewers

- [ ] @NVMakarenko 

### Second Level Review

- [ ] @loqimean 

## Summary of issue

Add color picker to calculator 

## Summary of change

Added color field in model, created partial for picking color

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-12-02 12:56 UTC, SleekMutt approved these changes

2024-12-03 17:21 UTC, loqimean requested changes

2024-12-03 17:21 UTC, loqimean commented on app/models/calculator.rb
> +  validates :color, format: { with: /\A#[0-9a-fA-F]{6}\z/ }
а де тести?))

2024-12-04 00:14 UTC, loqimean requested changes

2024-12-04 00:14 UTC, loqimean commented on app/assets/stylesheets/components/form.css
> +    height: 3.5rem;
```suggestion
    @apply w-28 h-14;
```

2024-12-05 11:12 UTC, loqimean approved these changes

2024-12-05 11:32 UTC, merged